// todo: remove mock functionality
import milkImage from '@assets/generated_images/Fresh_milk_product_photo_f32b7242.png';
import breadImage from '@assets/generated_images/Artisan_bread_product_photo_3bce2d4e.png';
import applesImage from '@assets/generated_images/Fresh_apples_product_photo_8e2a290d.png';
import readyMealImage from '@assets/generated_images/Ready_meal_product_photo_ccde0adf.png';
import eggsImage from '@assets/generated_images/Fresh_eggs_product_photo_2a6b8195.png';
import broccoliImage from '@assets/generated_images/Fresh_broccoli_product_photo_dd14a650.png';
import produceImage from '@assets/generated_images/Fresh_produce_assortment_7dc64d24.png';
import steakImage from '@assets/generated_images/British_beef_steak_a4049cd2.png';
import bakeryImage from '@assets/generated_images/Fresh_bakery_products_f24133a0.png';
import dairyImage from '@assets/generated_images/Dairy_products_collection_6d15fc58.png';
import wineImage from '@assets/generated_images/Wine_bottles_collection_1ff2a298.png';
import deliveryImage from '@assets/generated_images/Home_delivery_service_image_af86caa0.png';
import pepsiImage from '@assets/stock_images/pepsi_cola_bottle_so_df57decf.jpg';
import energyDrinkImage from '@assets/stock_images/energy_drink_can_mon_e72c0753.jpg';
import waterImage from '@assets/stock_images/bottled_water_minera_bd871f27.jpg';
import juiceImage from '@assets/stock_images/orange_juice_bottle_db30d86c.jpg';
import sportsDrinkImage from '@assets/stock_images/sports_drink_lucozad_fa8fd46f.jpg';
import sodaImage from '@assets/stock_images/lemon_lime_soda_7up__743bc4c1.jpg';

export const mockProducts = [
  {
    id: '1',
    name: 'Organic Whole Milk 2L',
    description: 'Fresh organic milk from British farms, rich and creamy',
    category: 'dairy',
    price: 2.50,
    memberPrice: 2.25,
    image: milkImage,
    inStock: 1,
  },
  {
    id: '2',
    name: 'Artisan Sourdough Bread',
    description: 'Freshly baked sourdough with a crispy crust and soft interior',
    category: 'bakery',
    price: 2.80,
    memberPrice: 2.50,
    image: breadImage,
    inStock: 1,
  },
  {
    id: '3',
    name: 'British Red Apples (6 pack)',
    description: 'Crisp and sweet British-grown apples, perfect for snacking',
    category: 'produce',
    price: 2.00,
    memberPrice: 1.80,
    image: applesImage,
    inStock: 1,
  },
  {
    id: '4',
    name: 'Ready Meal Pasta Carbonara',
    description: 'Restaurant-quality pasta ready in minutes, made with British bacon',
    category: 'ready-meals',
    price: 4.50,
    memberPrice: 4.00,
    image: readyMealImage,
    inStock: 1,
  },
  {
    id: '5',
    name: 'Free Range Eggs (12 pack)',
    description: 'Large free-range eggs from British farms, perfect for any meal',
    category: 'dairy',
    price: 3.20,
    memberPrice: 2.90,
    image: eggsImage,
    inStock: 1,
  },
  {
    id: '6',
    name: 'Fresh Broccoli',
    description: 'Tender green broccoli florets, packed with nutrients',
    category: 'produce',
    price: 1.50,
    memberPrice: 1.30,
    image: broccoliImage,
    inStock: 1,
  },
  {
    id: '7',
    name: 'Mixed Seasonal Vegetables',
    description: 'Fresh selection of seasonal produce including carrots, peppers, and tomatoes',
    category: 'produce',
    price: 3.50,
    memberPrice: 3.20,
    image: produceImage,
    inStock: 1,
  },
  {
    id: '8',
    name: 'British Beef Steak 400g',
    description: '100% British beef, expertly aged for 21 days for maximum flavor',
    category: 'meat',
    price: 8.50,
    memberPrice: 7.90,
    image: steakImage,
    inStock: 1,
  },
  {
    id: '9',
    name: 'Bakery Selection Box',
    description: 'Assorted fresh baked goods including croissants and pastries',
    category: 'bakery',
    price: 5.00,
    memberPrice: 4.50,
    image: bakeryImage,
    inStock: 1,
  },
  {
    id: '10',
    name: 'Dairy Essentials Bundle',
    description: 'Complete dairy collection: milk, butter, cheese, and yogurt',
    category: 'dairy',
    price: 9.00,
    memberPrice: 8.00,
    image: dairyImage,
    inStock: 1,
  },
  {
    id: '11',
    name: 'Red Wine Selection',
    description: 'Premium red wine varieties from around the world',
    category: 'alcohol',
    price: 12.00,
    memberPrice: 10.50,
    image: wineImage,
    inStock: 1,
  },
  {
    id: '12',
    name: 'White Wine Selection',
    description: 'Crisp and refreshing white wines, perfect for any occasion',
    category: 'alcohol',
    price: 11.00,
    memberPrice: 9.50,
    image: wineImage,
    inStock: 1,
  },
  {
    id: '13',
    name: 'Organic Semi-Skimmed Milk 1L',
    description: 'Light and healthy organic milk from British cows',
    category: 'dairy',
    price: 1.40,
    memberPrice: 1.20,
    image: milkImage,
    inStock: 1,
  },
  {
    id: '14',
    name: 'Wholemeal Bread Loaf',
    description: 'Nutritious wholemeal bread, high in fiber',
    category: 'bakery',
    price: 1.20,
    memberPrice: 1.00,
    image: breadImage,
    inStock: 1,
  },
  {
    id: '15',
    name: 'Green Apples (6 pack)',
    description: 'Tart and crispy Granny Smith apples',
    category: 'produce',
    price: 1.90,
    memberPrice: 1.70,
    image: applesImage,
    inStock: 1,
  },
  {
    id: '16',
    name: 'Ready Meal Lasagne',
    description: 'Classic Italian lasagne with rich meat sauce',
    category: 'ready-meals',
    price: 4.80,
    memberPrice: 4.30,
    image: readyMealImage,
    inStock: 1,
  },
  
  // Soft Drinks - Pepsi & Cola Products
  {
    id: '17',
    name: 'Pepsi Cola 2L Bottle',
    description: 'Classic Pepsi cola, refreshing and bold taste',
    category: 'beverages',
    price: 7.49,
    memberPrice: 7.19,
    image: pepsiImage,
    inStock: 1,
  },
  {
    id: '18',
    name: 'Pepsi Cola 6x2L Multipack',
    description: 'Value pack of 6 Pepsi 2L bottles',
    category: 'beverages',
    price: 6.19,
    memberPrice: 5.95,
    image: pepsiImage,
    inStock: 1,
  },
  {
    id: '19',
    name: 'Pepsi Cola 12x500ml Cans',
    description: 'Pack of 12 Pepsi 500ml cans, perfect for sharing',
    category: 'beverages',
    price: 8.49,
    memberPrice: 8.19,
    image: pepsiImage,
    inStock: 1,
  },
  {
    id: '20',
    name: 'Pepsi 4x6 Pack Cans',
    description: '24 cans of Pepsi cola in convenient multipack',
    category: 'beverages',
    price: 7.99,
    memberPrice: 7.69,
    image: pepsiImage,
    inStock: 1,
  },
  
  // Mountain Dew & Citrus Sodas
  {
    id: '21',
    name: 'Mountain Dew 2L Bottle',
    description: 'Citrus-flavored carbonated drink with bold taste',
    category: 'beverages',
    price: 16.99,
    memberPrice: 16.49,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '22',
    name: 'Mountain Dew 24x330ml Cans',
    description: 'Full case of Mountain Dew 330ml cans',
    category: 'beverages',
    price: 10.99,
    memberPrice: 10.49,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '23',
    name: '7up Lemon & Lime 6x2L',
    description: 'Crisp lemon & lime flavored soda multipack',
    category: 'beverages',
    price: 6.79,
    memberPrice: 6.49,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '24',
    name: '7up Variety Pack 12x500ml',
    description: 'Mix of 7up flavors in 500ml bottles',
    category: 'beverages',
    price: 7.79,
    memberPrice: 7.45,
    image: sodaImage,
    inStock: 1,
  },
  
  // Tango & Fruit Flavored Sodas
  {
    id: '25',
    name: 'Tango Orange 6x2L Bottles',
    description: 'Bold orange flavored carbonated drink',
    category: 'beverages',
    price: 6.79,
    memberPrice: 6.49,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '26',
    name: 'Tango Variety 12x500ml',
    description: 'Assorted Tango flavors in convenient pack',
    category: 'beverages',
    price: 7.79,
    memberPrice: 7.49,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '27',
    name: 'Tango 24x330ml Cans',
    description: 'Full case of Tango 330ml cans',
    category: 'beverages',
    price: 7.89,
    memberPrice: 7.59,
    image: sodaImage,
    inStock: 1,
  },
  
  // Barr & IRN BRU
  {
    id: '28',
    name: 'Barr 1901 Traditional 6x2L',
    description: 'Traditional carbonated soft drink',
    category: 'beverages',
    price: 10.99,
    memberPrice: 10.49,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '29',
    name: 'Barr Variety 12x500ml',
    description: 'Mixed pack of Barr soft drinks',
    category: 'beverages',
    price: 5.99,
    memberPrice: 5.69,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '30',
    name: 'IRN BRU Variety Pack',
    description: 'Assorted IRN BRU flavors',
    category: 'beverages',
    price: 8.69,
    memberPrice: 8.29,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '31',
    name: 'Ka Fruit Punch 6x2L',
    description: 'Fruit flavored carbonated drinks variety pack',
    category: 'beverages',
    price: 5.89,
    memberPrice: 5.59,
    image: sodaImage,
    inStock: 1,
  },
  
  // Vimto Products
  {
    id: '32',
    name: 'Vimto Sparkling Zero 24x330ml',
    description: 'Sugar-free Vimto sparkling drink',
    category: 'beverages',
    price: 7.29,
    memberPrice: 6.99,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '33',
    name: 'Vimto Original 12x725ml',
    description: 'Classic Vimto fruity drink bottles',
    category: 'beverages',
    price: 9.99,
    memberPrice: 9.49,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '34',
    name: 'Vimto Discovery Variety 12x500ml',
    description: 'Mixed Vimto flavors discovery pack',
    category: 'beverages',
    price: 6.79,
    memberPrice: 6.49,
    image: sodaImage,
    inStock: 1,
  },
  {
    id: '35',
    name: 'Vimto Variety 12x500ml',
    description: 'Assorted Vimto flavored drinks',
    category: 'beverages',
    price: 6.95,
    memberPrice: 6.65,
    image: sodaImage,
    inStock: 1,
  },
  
  // Fruit Juices - Just Juice
  {
    id: '36',
    name: 'Just Juice Orange 12x1L',
    description: 'Premium orange juice cartons',
    category: 'beverages',
    price: 14.99,
    memberPrice: 14.29,
    image: juiceImage,
    inStock: 1,
  },
  {
    id: '37',
    name: 'Just Juice Variety 12x1L',
    description: 'Mixed fruit juice flavors',
    category: 'beverages',
    price: 12.29,
    memberPrice: 11.69,
    image: juiceImage,
    inStock: 1,
  },
  {
    id: '38',
    name: 'Just Juice Apples 24x200ml',
    description: 'Apple juice small cartons',
    category: 'beverages',
    price: 7.99,
    memberPrice: 7.59,
    image: juiceImage,
    inStock: 1,
  },
  {
    id: '39',
    name: 'Just Juice Oranges 24x200ml',
    description: 'Orange juice small cartons',
    category: 'beverages',
    price: 10.19,
    memberPrice: 9.69,
    image: juiceImage,
    inStock: 1,
  },
  {
    id: '40',
    name: 'Just Juice Pineapples Carton',
    description: 'Pineapple juice 1L carton',
    category: 'beverages',
    price: 6.39,
    memberPrice: 6.09,
    image: juiceImage,
    inStock: 1,
  },
  
  // Fruit Drinks - Rubicon & Ocean Spray
  {
    id: '41',
    name: 'Rubicon Variety 12x500ml',
    description: 'Exotic fruit drink flavors',
    category: 'beverages',
    price: 6.39,
    memberPrice: 6.09,
    image: juiceImage,
    inStock: 1,
  },
  {
    id: '42',
    name: 'Rubicon Mango 12x500ml',
    description: 'Mango flavored fruit drink',
    category: 'beverages',
    price: 5.29,
    memberPrice: 5.05,
    image: juiceImage,
    inStock: 1,
  },
  {
    id: '43',
    name: 'Ocean Spray Cranberry 12x1L',
    description: 'Cranberry juice drink cartons',
    category: 'beverages',
    price: 11.00,
    memberPrice: 10.45,
    image: juiceImage,
    inStock: 1,
  },
  {
    id: '44',
    name: 'Robinsons Variety 12x750ml',
    description: 'Robinsons fruit drink selection',
    category: 'beverages',
    price: 9.99,
    memberPrice: 9.49,
    image: juiceImage,
    inStock: 1,
  },
  {
    id: '45',
    name: 'Robinsons Variety 4x Pack',
    description: 'Robinsons fruit drinks multipack',
    category: 'beverages',
    price: 6.95,
    memberPrice: 6.65,
    image: juiceImage,
    inStock: 1,
  },
  
  // Sports & Energy Drinks - Lucozade & Oasis
  {
    id: '46',
    name: 'Lucozade Original 12x750ml',
    description: 'Energy glucose drink for sports',
    category: 'beverages',
    price: 12.79,
    memberPrice: 12.19,
    image: sportsDrinkImage,
    inStock: 1,
  },
  {
    id: '47',
    name: 'Lucozade Mango Energy 24x250ml',
    description: 'Mango flavored energy drink cans',
    category: 'beverages',
    price: 7.49,
    memberPrice: 7.15,
    image: sportsDrinkImage,
    inStock: 1,
  },
  {
    id: '48',
    name: 'Oasis Variety 12x500ml',
    description: 'Refreshing fruit flavored drinks',
    category: 'beverages',
    price: 7.79,
    memberPrice: 7.39,
    image: sportsDrinkImage,
    inStock: 1,
  },
  {
    id: '49',
    name: 'Boost Original 12x1L',
    description: 'Energy glucose drink bottles',
    category: 'beverages',
    price: 7.99,
    memberPrice: 7.59,
    image: sportsDrinkImage,
    inStock: 1,
  },
  {
    id: '50',
    name: 'Boost Energy 12x500ml',
    description: 'Boost energy drink variety',
    category: 'beverages',
    price: 5.19,
    memberPrice: 4.95,
    image: sportsDrinkImage,
    inStock: 1,
  },
  {
    id: '51',
    name: 'Boost Variety 12x500ml',
    description: 'Mixed Boost energy flavors',
    category: 'beverages',
    price: 5.69,
    memberPrice: 5.39,
    image: sportsDrinkImage,
    inStock: 1,
  },
  {
    id: '52',
    name: 'Boost 24x250ml Cans',
    description: 'Small Boost energy drink cans',
    category: 'beverages',
    price: 6.49,
    memberPrice: 6.19,
    image: sportsDrinkImage,
    inStock: 1,
  },
  
  // Energy Drinks - Emerge & Prime
  {
    id: '53',
    name: 'Emerge Energy 12x500ml',
    description: 'Budget energy drink multipack',
    category: 'beverages',
    price: 3.99,
    memberPrice: 3.79,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '54',
    name: 'Prime Hydration 12x500ml',
    description: 'Premium hydration sports drink',
    category: 'beverages',
    price: 9.79,
    memberPrice: 9.29,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '55',
    name: 'Prime Energy Variety',
    description: 'Prime energy drink flavors',
    category: 'beverages',
    price: 7.99,
    memberPrice: 7.59,
    image: energyDrinkImage,
    inStock: 1,
  },
  
  // Energy Drinks - Red Bull
  {
    id: '56',
    name: 'Red Bull Energy 24x355ml',
    description: 'Full case Red Bull energy drink',
    category: 'beverages',
    price: 26.79,
    memberPrice: 25.45,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '57',
    name: 'Red Bull Energy 12x355ml',
    description: 'Red Bull energy drink 12 pack',
    category: 'beverages',
    price: 12.59,
    memberPrice: 11.99,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '58',
    name: 'Red Bull 12x473ml',
    description: 'Large Red Bull energy cans',
    category: 'beverages',
    price: 18.39,
    memberPrice: 17.49,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '59',
    name: 'Red Bull 24x250ml',
    description: 'Standard Red Bull energy drink cans',
    category: 'beverages',
    price: 18.69,
    memberPrice: 17.79,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '60',
    name: 'Red Bull Variety 12x250ml',
    description: 'Mixed Red Bull flavor varieties',
    category: 'beverages',
    price: 9.99,
    memberPrice: 9.49,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '61',
    name: 'Red Bull Pink Edition 12x250ml',
    description: 'Red Bull special edition flavors',
    category: 'beverages',
    price: 9.39,
    memberPrice: 8.95,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '62',
    name: 'Red Bull Energy 4 Pack',
    description: 'Red Bull multipack 6x4x250ml',
    category: 'beverages',
    price: 20.49,
    memberPrice: 19.49,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '63',
    name: 'Red Bull Sugar Free 4 Pack',
    description: 'Sugar-free Red Bull 6x4x250ml',
    category: 'beverages',
    price: 18.49,
    memberPrice: 17.59,
    image: energyDrinkImage,
    inStock: 1,
  },
  
  // Energy Drinks - Monster & Rockstar
  {
    id: '64',
    name: 'Monster Energy 500ml',
    description: 'Monster energy drink variety',
    category: 'beverages',
    price: 8.95,
    memberPrice: 8.49,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '65',
    name: 'Monster Punch 500ml',
    description: 'Monster energy punch flavors',
    category: 'beverages',
    price: 9.99,
    memberPrice: 9.49,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '66',
    name: 'Rockstar Energy 12x330ml',
    description: 'Rockstar energy drink pack',
    category: 'beverages',
    price: 5.25,
    memberPrice: 4.99,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '67',
    name: 'Rockstar Variety 12x330ml',
    description: 'Mixed Rockstar energy flavors',
    category: 'beverages',
    price: 6.39,
    memberPrice: 6.09,
    image: energyDrinkImage,
    inStock: 1,
  },
  
  // Energy Drinks - C4 & Ghost
  {
    id: '68',
    name: 'C4 Energy 12x500ml',
    description: 'C4 pre-workout energy drink',
    category: 'beverages',
    price: 8.15,
    memberPrice: 7.75,
    image: energyDrinkImage,
    inStock: 1,
  },
  {
    id: '69',
    name: 'Ghost Energy Variety',
    description: 'Ghost energy drink flavors - Buy 3 Cases £18',
    category: 'beverages',
    price: 6.00,
    memberPrice: 5.70,
    image: energyDrinkImage,
    inStock: 1,
  },
  
  // Bottled Water - Volvic
  {
    id: '70',
    name: 'Volvic Natural Water 1L',
    description: 'Pure natural mineral water',
    category: 'beverages',
    price: 5.99,
    memberPrice: 5.69,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '71',
    name: 'Volvic Touch of Fruit 6x1.5L',
    description: 'Fruit flavored water bottles',
    category: 'beverages',
    price: 4.85,
    memberPrice: 4.61,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '72',
    name: 'Volvic 6x1.5L Bottles',
    description: 'Natural mineral water multipack',
    category: 'beverages',
    price: 5.19,
    memberPrice: 4.93,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '73',
    name: 'Volvic Touch of Fruit 6x750ml',
    description: 'Fruit water variety pack',
    category: 'beverages',
    price: 4.99,
    memberPrice: 4.74,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '74',
    name: 'Volvic 12x500ml',
    description: 'Small Volvic water bottles',
    category: 'beverages',
    price: 4.19,
    memberPrice: 3.98,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '75',
    name: 'Volvic 24x500ml',
    description: 'Full case of Volvic 500ml',
    category: 'beverages',
    price: 5.99,
    memberPrice: 5.69,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '76',
    name: 'Volvic 12x1.5L Bottles',
    description: 'Large Volvic water bottles',
    category: 'beverages',
    price: 6.49,
    memberPrice: 6.17,
    image: waterImage,
    inStock: 1,
  },
  
  // Bottled Water - Saka & Aqua Pura
  {
    id: '77',
    name: 'Saka Water 6x1.5L',
    description: 'Budget mineral water multipack',
    category: 'beverages',
    price: 1.99,
    memberPrice: 1.89,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '78',
    name: 'Saka Water 2x5L',
    description: 'Large Saka water bottles',
    category: 'beverages',
    price: 2.49,
    memberPrice: 2.37,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '79',
    name: 'Aqua Pura 24x750ml',
    description: 'Aqua Pura mineral water case',
    category: 'beverages',
    price: 4.59,
    memberPrice: 4.36,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '80',
    name: 'Aqua Pura 24x500ml',
    description: 'Aqua Pura water small bottles',
    category: 'beverages',
    price: 3.29,
    memberPrice: 3.13,
    image: waterImage,
    inStock: 1,
  },
  {
    id: '81',
    name: 'Aqua Pura Still Water 24x500ml',
    description: 'Still mineral water bottles',
    category: 'beverages',
    price: 3.39,
    memberPrice: 3.22,
    image: waterImage,
    inStock: 1,
  },
];

export const mockOffers = [
  {
    id: 'offer-1',
    title: 'Fresh Produce Flash Sale',
    description: 'Save big on fresh fruits and vegetables.',
    discount: '25% OFF',
    image: produceImage,
    validUntil: '31 Oct 2025',
  },
  {
    id: 'offer-2',
    title: 'Free Delivery This Week',
    description: 'Get free home delivery on all orders over £15.',
    discount: 'FREE',
    image: deliveryImage,
    validUntil: '3 Nov 2025',
  },
  {
    id: 'offer-3',
    title: 'Bakery Bundle Deal',
    description: 'Buy 2 bakery items and get 1 free.',
    discount: 'Buy 2 Get 1',
    image: bakeryImage,
    validUntil: '7 Nov 2025',
  },
  {
    id: 'offer-4',
    title: 'Premium Beef Steak',
    description: 'Quality British beef at incredible prices.',
    discount: '30% OFF',
    image: steakImage,
    validUntil: '10 Nov 2025',
  },
  {
    id: 'offer-5',
    title: 'Dairy Savings',
    description: 'Member exclusive prices on all dairy products.',
    discount: '20% OFF',
    image: dairyImage,
    validUntil: '14 Nov 2025',
  },
  {
    id: 'offer-6',
    title: 'Wine Selection',
    description: 'Premium wines at member prices.',
    discount: '15% OFF',
    image: wineImage,
    validUntil: '17 Nov 2025',
  },
];
