import { db } from './server/db';
import { products } from './shared/schema';
import { inArray } from 'drizzle-orm';

const namesToDelete = [
  "Budweiser 4x440ml","Corona Ligera 4x330ml","Croft Original Sherry 75cl","Desperados 3x330ml","Fosters 4x440ml","Guinness Original 4x440ml","Hardys Stamp Cabernet Merlot 75cl","Hardys Stamp Semillon Chardonnay 75cl","Hardys Stamp Semillon Sauvignon 75cl","Hardys Stamp Shiraz Cabernet Sauvignon 75cl","Heineken 4x440ml","Jam Shed Chardonnay 75cl","Jam Shed Malbec 75cl","Jam Shed Rose 75cl","Jam Shed Shiraz 75cl","Jam Shed Tempranillo 75cl","Stella Artois 4x440ml","Strongbow Tropical Cider 4x440ml","Villa Maria Sauvignon Blanc 75cl","Lost Lager 4x440ml","Harveys Bristol Cream Sherry 75cl",
  "Coca Cola Zero Sugar 2L","Lucozade Energy Apple 380ml","Lucozade Energy Cherry 380ml","Lucozade Energy Orange 380ml","Lucozade Energy Original 380ml","Lucozade Original 900ml","Lucozade Zero Pink Lemonade 380ml","Naked Smoothie Gold Machine 360ml","Red Bull Coconut Berry Edition 250ml","Red Bull Zero 250ml","Ribena Blackcurrant 500ml","Ribena Light Blackcurrant 500ml","Ribena No Added Sugar Mango & Lime 500ml","Ribena No Added Sugar Strawberry 500ml","Ribena Pineapple & Passionfruit 500ml","Pepsi Max Mango 2L","Costa Latte Can 250ml","Costa Caramel Latte Can 250ml","Arctic Coffee Cafe Latte 330ml","Arctic Coffee Caramel Latte 330ml","Arctic Coffee Intenso 330ml","Pepsi Diet 500ml","Pepsi Max 500ml","Nescafe Original 2in1 Coffee 6 Pack","Nescafe Original 3in1 Coffee 6 Pack","Nescafe 3in1 Caramel Coffee 6 Pack",
  "Reeses Minis Pouch 68g","Reeses Peanut Butter Cups Trio 51g","Reeses White Cup 39g","Galaxy Cake Bar 5 Pack","Galaxy Caramel Cake Bar 5 Pack","Cadbury Raspberry Mini Rolls 5 Pack","Cadbury Twinpot Buttons 2 Pack","Cadbury Twinpot Daim 2 Pack","Cadbury Twinpot Flake 2 Pack","Swizzels Squashies Drumstick Original 120g","Swizzels Squashies Bubblegum 120g","Swizzels Squashies Rhubarb & Custard 120g","Swizzels Squashies Sour Cherry & Apple 120g","Swizzels Squashies Minions 120g","Kind Dark Chocolate Nuts & Sea Salt 40g","Kind Caramel Almond & Sea Salt 40g","Kind Peanut Butter & Dark Chocolate 40g","Barebells Bar Caramel Choco 55g","Barebells Bars Peanut Caramel 55g","Barebells Caramel Cashew 55g","Barebells White Salty Peanut 55g","Barebells Cookies and Cream 55g","Barebells Banana Dream 55g","Wheat Crunchies Bacon 70g","Wheat Crunchies Spicy Tomato 70g","Mentos Mint Roll 38g","Extra Peppermint Chewing Gum 10 Pack","Extra Spearmint Chewing Gum 10 Pack","Cadbury Chocolate Mini Rolls 5 Pack","Cadbury Chocolate Cake Bars Mini Eggs 5 Pack",
  "Discos Cheese & Onion 25.5g","Discos Salt & Vinegar 25.5g","Popchips BBQ 23g","Skips Prawn Cocktail 17g","Butterkist Sweet Popcorn 76g","Jack Links Beef Jerky Original 25g","Jack Links Beef Bar Original 22.5g","Jack Links Biltong Original 25g","Jack Links Beef Jerky Sweet & Hot 25g","Peperami & Cheese Snack Box 50g",
  "Cravendale Purefilter Semi Skimmed Milk 1L","Cravendale Purefilter Whole Milk 1L","Cravendale Skimmed Milk 1L","Lactofree Semi Skimmed Milk 1L","Freshways Semi Skimmed Milk 2L","Yeo Valley Organic Skimmed Milk 1L","Yop Strawberry Yoghurt Drink 500ml","Yop Raspberry Yoghurt Drink 500ml","GU Lemon Cheesecake 2 Pack","GU Double Chocolate Vanilla Cheesecake 2 Pack","GU Salted Caramel Cheesecake 2 Pack","Cathedral City Extra Mature Cheddar 200g",
  "Chicago Town Deep Dish Pepperoni Pizza 2 Pack","Chicago Town Deep Dish Cheese Pizza 2 Pack","Chicago Town Deep Dish Four Cheese Pizza 2 Pack","Chicago Town Deep Dish Chicken & Bacon Pizza 2 Pack","Kershaws Fish & Chips 400g","Kershaws Sausage & Chips 400g","Kershaws Steaklet & Chips 400g","Kershaws Beef Dinner 400g","Kershaws Chicken Curry 400g","Kershaws Chicken Dinner 400g","Kirstys Beef Lasagne 300g","Kirstys Chicken Tikka Masala 300g","Kirstys Sweet & Sour Chicken 300g","Richmond 8 Meat Free Sausages 304g","Peperami Pizza Bun 130g",
  "Bens Original Egg Fried Rice 250g","Bens Original Special Fried Rice 250g","Bens Original Savoury Chicken Rice 250g","Bens Original Spicy Mexican Rice 250g","Rustlers Quarter Pounder Cheese 188g","Rustlers Pancake Stack","King Pot Noodle Beef & Tomato 114g","TGI Fridays BBQ Beef Brisket 400g","TGI Fridays BBQ Pulled Pork 400g","TGI Fridays Chicken Wings & Pork Ribs 580g","Paxo Sage & Onion Stuffing 85g","Oxo Chicken Cubes 12 Pack","Bisto Beef Gravy Granules 170g","Bisto Chicken Gravy Granules 170g","Encona West Indian Hot Pepper Sauce 142ml","Encona Thai Sweet Chilli Sauce 142ml",
  "Jacks Diced Beef 400g","Jacks Medium Whole Chicken 1.5kg","Jacks Premium Cumberland Sausages 400g","Jacks Premium Lincoln Sausages 400g","Jacks Premium Pork Sausages 400g","Ginsters Cornish Pasty 150g","Ginsters Large Sausage Roll 130g","Ginsters Cajun Chicken Bake 150g","Ginsters Philly Cheese Steak Bake 150g","Chicken Shop Ultimate Burger 160g","Southern Fried Chicken Burger 150g",
  "Comfort Concentrated Fabric Conditioner 1.16L","Comfort Pure Concentrated Fabric Conditioner 1.16L","Dettol Antibacterial Wipes 72 Pack","Dettol Disinfectant Spray Linen 400ml","Domestos Citrus Bleach 750ml","Domestos Original Bleach 750ml","Fairy Lemon Washing Up Liquid 383ml","Fairy Original Washing Up Liquid 383ml","Fairy Pomegranate Washing Up Liquid 383ml","Flash Kitchen Spray Fresh Citrus 800ml","Flash With Bleach Spray 800ml","Persil Non Bio Capsules 15 Pack","Plenty Kitchen Roll 2 Pack","Febreze Cotton Fresh Air Freshener 185ml","Febreze Blossom Breeze Air Freshener 185ml","Dreamies Cheese Cat Treats 60g","Dreamies Chicken Cat Treats 60g","Go-Cat Chicken & Duck 340g","Pedigree Jumbone Beef & Poultry 180g","Cesar Classic Terrine 150g","TRESemme Rich Moisture Shampoo 680ml","Head & Shoulders 2in1 Shampoo 250ml","Cif Cream Lemon Cleaner 500ml",
  "Hovis Seeds & Sensations Original 400g","Fox's Half Coated Milk Chocolate Cookie 175g","Fox's Chocolatey Rounds 130g","Fox's Milk Chocolate Chunk Cookies 175g","McVities Digestives Original 250g","Bakery Selection Hot Cross Buns 4 Pack","Whitworths Flaked Almonds 150g","Whitworths Desiccated Coconut 150g","Whitworths Walnut Pieces 150g",
  "Jacks Cauliflower Each","Dell Ugo Potato Gnocchi 350g","Bear Yoyo Strawberry Multipack 5x20g","Bear Yoyo Raspberry Multipack 5x20g"
];

async function main() {
  const before = await db.select({ name: products.name }).from(products);
  console.log(`Products before: ${before.length}`);

  const batchSize = 50;
  for (let i = 0; i < namesToDelete.length; i += batchSize) {
    const batch = namesToDelete.slice(i, i + batchSize);
    await db.delete(products).where(inArray(products.name, batch));
  }

  const after = await db.select({ name: products.name }).from(products);
  console.log(`Products after: ${after.length}`);
  console.log(`Removed: ${before.length - after.length} products`);
}

main().then(() => process.exit(0)).catch(err => { console.error(err); process.exit(1); });
