import { storage } from "./storage";
import { type InsertProduct } from "@shared/schema";

const mockProducts: Omit<InsertProduct, "id">[] = [
  {
    name: "Organic Whole Milk 2L",
    description: "Fresh organic milk from British farms, rich and creamy",
    category: "dairy",
    price: "2.50",
    memberPrice: "2.25",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "Artisan Sourdough Bread",
    description: "Freshly baked sourdough with a crispy crust and soft interior",
    category: "bakery",
    price: "2.80",
    memberPrice: "2.50",
    image: "/attached_assets/generated_images/Artisan_bread_product_photo_3bce2d4e.png",
    inStock: 1,
  },
  {
    name: "British Red Apples (6 pack)",
    description: "Crisp and sweet British-grown apples, perfect for snacking",
    category: "produce",
    price: "2.00",
    memberPrice: "1.80",
    image: "/attached_assets/generated_images/Fresh_apples_product_photo_8e2a290d.png",
    inStock: 1,
  },
  {
    name: "Ready Meal Pasta Carbonara",
    description: "Restaurant-quality pasta ready in minutes, made with British bacon",
    category: "ready-meals",
    price: "4.50",
    memberPrice: "4.00",
    image: "/attached_assets/generated_images/Ready_meal_product_photo_ccde0adf.png",
    inStock: 1,
  },
  {
    name: "Free Range Eggs (12 pack)",
    description: "Large free-range eggs from British farms, perfect for any meal",
    category: "dairy",
    price: "3.20",
    memberPrice: "2.90",
    image: "/attached_assets/generated_images/Fresh_eggs_product_photo_2a6b8195.png",
    inStock: 1,
  },
  {
    name: "Fresh Broccoli",
    description: "Tender green broccoli florets, packed with nutrients",
    category: "produce",
    price: "1.50",
    memberPrice: "1.30",
    image: "/attached_assets/generated_images/Fresh_broccoli_product_photo_dd14a650.png",
    inStock: 1,
  },
  {
    name: "Mixed Seasonal Vegetables",
    description: "Fresh selection of seasonal produce including carrots, peppers, and tomatoes",
    category: "produce",
    price: "3.50",
    memberPrice: "3.20",
    image: "/attached_assets/generated_images/Fresh_produce_assortment_7dc64d24.png",
    inStock: 1,
  },
  {
    name: "British Beef Steak 400g",
    description: "100% British beef, expertly aged for 21 days for maximum flavor",
    category: "meat",
    price: "8.50",
    memberPrice: "7.90",
    image: "/attached_assets/generated_images/British_beef_steak_a4049cd2.png",
    inStock: 1,
  },
  {
    name: "Bakery Selection Box",
    description: "Assorted fresh baked goods including croissants and pastries",
    category: "bakery",
    price: "5.00",
    memberPrice: "4.50",
    image: "/attached_assets/generated_images/Fresh_bakery_products_f24133a0.png",
    inStock: 1,
  },
  {
    name: "Dairy Essentials Bundle",
    description: "Complete dairy collection: milk, butter, cheese, and yogurt",
    category: "dairy",
    price: "9.00",
    memberPrice: "8.00",
    image: "/attached_assets/generated_images/Dairy_products_collection_6d15fc58.png",
    inStock: 1,
  },
  {
    name: "Red Wine Selection",
    description: "Premium red wine varieties from around the world",
    category: "alcohol",
    price: "12.00",
    memberPrice: "10.50",
    image: "/attached_assets/generated_images/Wine_bottles_collection_1ff2a298.png",
    inStock: 1,
  },
  {
    name: "White Wine Selection",
    description: "Crisp and refreshing white wines, perfect for any occasion",
    category: "alcohol",
    price: "11.00",
    memberPrice: "9.50",
    image: "/attached_assets/generated_images/Wine_bottles_collection_1ff2a298.png",
    inStock: 1,
  },
  {
    name: "Organic Semi-Skimmed Milk 1L",
    description: "Light and healthy organic milk from British cows",
    category: "dairy",
    price: "1.40",
    memberPrice: "1.20",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "Wholemeal Bread Loaf",
    description: "Nutritious wholemeal bread, high in fiber",
    category: "bakery",
    price: "1.20",
    memberPrice: "1.00",
    image: "/attached_assets/generated_images/Artisan_bread_product_photo_3bce2d4e.png",
    inStock: 1,
  },
  {
    name: "Green Apples (6 pack)",
    description: "Tart and crispy Granny Smith apples",
    category: "produce",
    price: "1.90",
    memberPrice: "1.70",
    image: "/attached_assets/generated_images/Fresh_apples_product_photo_8e2a290d.png",
    inStock: 1,
  },
  {
    name: "Ready Meal Lasagne",
    description: "Classic Italian lasagne with rich meat sauce",
    category: "ready-meals",
    price: "4.80",
    memberPrice: "4.30",
    image: "/attached_assets/generated_images/Ready_meal_product_photo_ccde0adf.png",
    inStock: 1,
  },
  {
    name: "Pepsi Cola 2L Bottle",
    description: "Classic Pepsi cola, refreshing and bold taste",
    category: "beverages",
    price: "2.29",
    memberPrice: "1.99",
    image: "/attached_assets/pepsi_2l.png",
    inStock: 1,
  },
  {
    name: "Coca Cola 2L Bottle",
    description: "Original Coca-Cola, the iconic cola taste",
    category: "beverages",
    price: "2.29",
    memberPrice: "1.99",
    image: "/attached_assets/coca_cola_2l.png",
    inStock: 1,
  },
  {
    name: "Sprite 2L Bottle",
    description: "Crisp lemon-lime flavored soda, refreshingly clear",
    category: "beverages",
    price: "2.19",
    memberPrice: "1.99",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "Tango Orange 500ml Bottle",
    description: "Fizzy orange soft drink with real fruit juice",
    category: "beverages",
    price: "1.25",
    memberPrice: "1.00",
    image: "/attached_assets/tango_orange_500ml.png",
    inStock: 1,
  },
  {
    name: "Vimto 500ml Bottle",
    description: "Mixed fruit flavored soft drink",
    category: "beverages",
    price: "1.25",
    memberPrice: "1.10",
    image: "/attached_assets/vimto_500ml.png",
    inStock: 1,
  },
  {
    name: "Red Bull Energy Drink 250ml Can",
    description: "Original Red Bull energy drink with caffeine and taurine",
    category: "beverages",
    price: "1.69",
    memberPrice: "1.49",
    image: "/attached_assets/red_bull_250ml.png",
    inStock: 1,
  },
  {
    name: "Monster Energy 500ml Can",
    description: "Monster energy drink for maximum energy boost",
    category: "beverages",
    price: "1.79",
    memberPrice: "1.59",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "4Kings Mojo Blackcurrant De Coco Drink 500ml",
    description: "Refreshing coconut water drink with blackcurrant flavor",
    category: "beverages",
    price: "1.99",
    memberPrice: "1.79",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "7UP Zero 500ml Bottle",
    description: "Zero sugar lemon-lime soda, crisp and refreshing",
    category: "beverages",
    price: "1.30",
    memberPrice: "1.15",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Regular 300ml Bottle",
    description: "Classic lemon-lime soda in 300ml bottle",
    category: "beverages",
    price: "0.79",
    memberPrice: "0.69",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Regular 500ml Bottle",
    description: "Classic lemon-lime refreshment in 500ml bottle",
    category: "beverages",
    price: "1.30",
    memberPrice: "1.15",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Regular 2L Bottle",
    description: "Large 2-liter bottle of classic 7UP",
    category: "beverages",
    price: "1.99",
    memberPrice: "1.79",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Tropical American 600ml",
    description: "Tropical fruit flavored 7UP variant",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/tango_orange_500ml.png",
    inStock: 1,
  },
  {
    name: "7UP Tropical 2L Bottle",
    description: "Large bottle of tropical 7UP flavor",
    category: "beverages",
    price: "1.99",
    memberPrice: "1.79",
    image: "/attached_assets/tango_orange_500ml.png",
    inStock: 1,
  },
  {
    name: "7UP Zero 330ml Can",
    description: "Zero sugar 7UP in convenient can format",
    category: "beverages",
    price: "0.79",
    memberPrice: "0.69",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Zero Pink Lemonade 330ml Can",
    description: "Zero sugar pink lemonade flavored 7UP",
    category: "beverages",
    price: "0.75",
    memberPrice: "0.65",
    image: "/attached_assets/vimto_500ml.png",
    inStock: 1,
  },
  {
    name: "7UP Zero Pink Lemonade 500ml",
    description: "Refreshing pink lemonade with zero sugar",
    category: "beverages",
    price: "1.30",
    memberPrice: "1.15",
    image: "/attached_assets/vimto_500ml.png",
    inStock: 1,
  },
  {
    name: "7UP Zero 2L Bottle",
    description: "Large zero sugar 7UP bottle",
    category: "beverages",
    price: "1.99",
    memberPrice: "1.79",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "Aloe Can American Grape 500ml",
    description: "Aloe vera drink with grape flavor",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "Aloe Can Blue Lagoon 500ml",
    description: "Refreshing blue lagoon flavored aloe drink",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "Aloe Can Energy 500ml",
    description: "Aloe vera energy drink for extra boost",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "Aloe Can Fruit Candy 500ml",
    description: "Sweet fruit candy flavored aloe drink",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "Amigo Apple and Strawberry 200ml",
    description: "Kids fruit drink with apple and strawberry",
    category: "beverages",
    price: "0.79",
    memberPrice: "0.69",
    image: "/attached_assets/tango_orange_500ml.png",
    inStock: 1,
  },
  {
    name: "Amigo Multivitamin 200ml 8-Pack",
    description: "Multivitamin fruit drinks for kids, 8 pack",
    category: "beverages",
    price: "5.49",
    memberPrice: "4.99",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "Appletiser 275ml Bottle",
    description: "Sparkling apple juice made from 100% pressed apples",
    category: "beverages",
    price: "1.79",
    memberPrice: "1.59",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "Appletiser 250ml Bottle",
    description: "Sparkling apple juice in convenient 250ml size",
    category: "beverages",
    price: "1.09",
    memberPrice: "0.99",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Still Natural Mineral Water 330ml 6-Pack",
    description: "Premium natural mineral water from Romania, pack of 6",
    category: "beverages",
    price: "9.60",
    memberPrice: "8.99",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Sparkling Natural Mineral Water 500ml",
    description: "Naturally carbonated mineral water",
    category: "beverages",
    price: "0.80",
    memberPrice: "0.70",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Sparkling Natural Mineral Water 1L",
    description: "Large bottle of sparkling mineral water",
    category: "beverages",
    price: "1.60",
    memberPrice: "1.45",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Sportscap Still Mineral Water 750ml",
    description: "Still mineral water with sport cap",
    category: "beverages",
    price: "1.10",
    memberPrice: "0.99",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Still Natural Mineral Water 1L",
    description: "Premium still mineral water in 1 liter bottle",
    category: "beverages",
    price: "1.69",
    memberPrice: "1.49",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Still Natural Mineral Water 2L",
    description: "Large 2-liter bottle of still mineral water",
    category: "beverages",
    price: "1.18",
    memberPrice: "1.09",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "7UP Regular 330ml Can",
    description: "Classic lemon-lime soda in convenient can size",
    category: "beverages",
    price: "0.75",
    memberPrice: "0.65",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
];

export async function seedProducts() {
  console.log("Seeding products...");
  
  const existingProducts = await storage.getAllProducts();
  if (existingProducts.length > 0) {
    console.log(`Already have ${existingProducts.length} products, skipping seed`);
    return;
  }

  for (const productData of mockProducts) {
    await storage.createProduct(productData);
  }

  console.log(`Seeded ${mockProducts.length} products successfully`);
}
