import { storage } from "./storage";
import { type InsertProduct } from "../shared/schema";

const mockProducts: Omit<InsertProduct, "id">[] = [
  {
    name: "Organic Whole Milk 2L",
    description: "Fresh organic milk from British farms, rich and creamy",
    category: "dairy",
    price: "2.50",
    memberPrice: "2.25",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "Artisan Sourdough Bread",
    description: "Freshly baked sourdough with a crispy crust and soft interior",
    category: "bakery",
    price: "2.80",
    memberPrice: "2.50",
    image: "/attached_assets/generated_images/Artisan_bread_product_photo_3bce2d4e.png",
    inStock: 1,
  },
  {
    name: "British Red Apples (6 pack)",
    description: "Crisp and sweet British-grown apples, perfect for snacking",
    category: "produce",
    price: "2.00",
    memberPrice: "1.80",
    image: "/attached_assets/generated_images/Fresh_apples_product_photo_8e2a290d.png",
    inStock: 1,
  },
  {
    name: "Ready Meal Pasta Carbonara",
    description: "Restaurant-quality pasta ready in minutes, made with British bacon",
    category: "ready-meals",
    price: "4.50",
    memberPrice: "4.00",
    image: "/attached_assets/generated_images/Ready_meal_product_photo_ccde0adf.png",
    inStock: 1,
  },
  {
    name: "Free Range Eggs (12 pack)",
    description: "Large free-range eggs from British farms, perfect for any meal",
    category: "dairy",
    price: "3.20",
    memberPrice: "2.90",
    image: "/attached_assets/generated_images/Fresh_eggs_product_photo_2a6b8195.png",
    inStock: 1,
  },
  {
    name: "Fresh Broccoli",
    description: "Tender green broccoli florets, packed with nutrients",
    category: "produce",
    price: "1.50",
    memberPrice: "1.30",
    image: "/attached_assets/generated_images/Fresh_broccoli_product_photo_dd14a650.png",
    inStock: 1,
  },
  {
    name: "Mixed Seasonal Vegetables",
    description: "Fresh selection of seasonal produce including carrots, peppers, and tomatoes",
    category: "produce",
    price: "3.50",
    memberPrice: "3.20",
    image: "/attached_assets/generated_images/Fresh_produce_assortment_7dc64d24.png",
    inStock: 1,
  },
  {
    name: "British Beef Steak 400g",
    description: "100% British beef, expertly aged for 21 days for maximum flavor",
    category: "meat",
    price: "8.50",
    memberPrice: "7.90",
    image: "/attached_assets/generated_images/British_beef_steak_a4049cd2.png",
    inStock: 1,
  },
  {
    name: "Bakery Selection Box",
    description: "Assorted fresh baked goods including croissants and pastries",
    category: "bakery",
    price: "5.00",
    memberPrice: "4.50",
    image: "/attached_assets/generated_images/Fresh_bakery_products_f24133a0.png",
    inStock: 1,
  },
  {
    name: "Dairy Essentials Bundle",
    description: "Complete dairy collection: milk, butter, cheese, and yogurt",
    category: "dairy",
    price: "9.00",
    memberPrice: "8.00",
    image: "/attached_assets/generated_images/Dairy_products_collection_6d15fc58.png",
    inStock: 1,
  },
  {
    name: "Red Wine Selection",
    description: "Premium red wine varieties from around the world",
    category: "alcohol",
    price: "12.00",
    memberPrice: "10.50",
    image: "/attached_assets/generated_images/Wine_bottles_collection_1ff2a298.png",
    inStock: 1,
  },
  {
    name: "White Wine Selection",
    description: "Crisp and refreshing white wines, perfect for any occasion",
    category: "alcohol",
    price: "11.00",
    memberPrice: "9.50",
    image: "/attached_assets/generated_images/Wine_bottles_collection_1ff2a298.png",
    inStock: 1,
  },
  {
    name: "Organic Semi-Skimmed Milk 1L",
    description: "Light and healthy organic milk from British cows",
    category: "dairy",
    price: "1.40",
    memberPrice: "1.20",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "Wholemeal Bread Loaf",
    description: "Nutritious wholemeal bread, high in fiber",
    category: "bakery",
    price: "1.20",
    memberPrice: "1.00",
    image: "/attached_assets/generated_images/Artisan_bread_product_photo_3bce2d4e.png",
    inStock: 1,
  },
  {
    name: "Green Apples (6 pack)",
    description: "Tart and crispy Granny Smith apples",
    category: "produce",
    price: "1.90",
    memberPrice: "1.70",
    image: "/attached_assets/generated_images/Fresh_apples_product_photo_8e2a290d.png",
    inStock: 1,
  },
  {
    name: "Ready Meal Lasagne",
    description: "Classic Italian lasagne with rich meat sauce",
    category: "ready-meals",
    price: "4.80",
    memberPrice: "4.30",
    image: "/attached_assets/generated_images/Ready_meal_product_photo_ccde0adf.png",
    inStock: 1,
  },
  {
    name: "Pepsi Cola 2L Bottle",
    description: "Classic Pepsi cola, refreshing and bold taste",
    category: "beverages",
    price: "2.29",
    memberPrice: "1.99",
    image: "/attached_assets/pepsi_2l.png",
    inStock: 1,
  },
  {
    name: "Coca Cola 2L Bottle",
    description: "Original Coca-Cola, the iconic cola taste",
    category: "beverages",
    price: "2.29",
    memberPrice: "1.99",
    image: "/attached_assets/coca_cola_2l.png",
    inStock: 1,
  },
  {
    name: "Sprite 2L Bottle",
    description: "Crisp lemon-lime flavored soda, refreshingly clear",
    category: "beverages",
    price: "2.19",
    memberPrice: "1.99",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "Tango Orange 500ml Bottle",
    description: "Fizzy orange soft drink with real fruit juice",
    category: "beverages",
    price: "1.25",
    memberPrice: "1.00",
    image: "/attached_assets/tango_orange_500ml.png",
    inStock: 1,
  },
  {
    name: "Vimto 500ml Bottle",
    description: "Mixed fruit flavored soft drink",
    category: "beverages",
    price: "1.25",
    memberPrice: "1.10",
    image: "/attached_assets/vimto_500ml.png",
    inStock: 1,
  },
  {
    name: "Red Bull Energy Drink 250ml Can",
    description: "Original Red Bull energy drink with caffeine and taurine",
    category: "beverages",
    price: "1.69",
    memberPrice: "1.49",
    image: "/attached_assets/red_bull_250ml.png",
    inStock: 1,
  },
  {
    name: "Monster Energy 500ml Can",
    description: "Monster energy drink for maximum energy boost",
    category: "beverages",
    price: "1.79",
    memberPrice: "1.59",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "4Kings Mojo Blackcurrant De Coco Drink 500ml",
    description: "Refreshing coconut water drink with blackcurrant flavor",
    category: "beverages",
    price: "1.99",
    memberPrice: "1.79",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "7UP Zero 500ml Bottle",
    description: "Zero sugar lemon-lime soda, crisp and refreshing",
    category: "beverages",
    price: "1.30",
    memberPrice: "1.15",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Regular 300ml Bottle",
    description: "Classic lemon-lime soda in 300ml bottle",
    category: "beverages",
    price: "0.79",
    memberPrice: "0.69",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Regular 500ml Bottle",
    description: "Classic lemon-lime refreshment in 500ml bottle",
    category: "beverages",
    price: "1.30",
    memberPrice: "1.15",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Regular 2L Bottle",
    description: "Large 2-liter bottle of classic 7UP",
    category: "beverages",
    price: "1.99",
    memberPrice: "1.79",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Tropical American 600ml",
    description: "Tropical fruit flavored 7UP variant",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/tango_orange_500ml.png",
    inStock: 1,
  },
  {
    name: "7UP Tropical 2L Bottle",
    description: "Large bottle of tropical 7UP flavor",
    category: "beverages",
    price: "1.99",
    memberPrice: "1.79",
    image: "/attached_assets/tango_orange_500ml.png",
    inStock: 1,
  },
  {
    name: "7UP Zero 330ml Can",
    description: "Zero sugar 7UP in convenient can format",
    category: "beverages",
    price: "0.79",
    memberPrice: "0.69",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "7UP Zero Pink Lemonade 330ml Can",
    description: "Zero sugar pink lemonade flavored 7UP",
    category: "beverages",
    price: "0.75",
    memberPrice: "0.65",
    image: "/attached_assets/vimto_500ml.png",
    inStock: 1,
  },
  {
    name: "7UP Zero Pink Lemonade 500ml",
    description: "Refreshing pink lemonade with zero sugar",
    category: "beverages",
    price: "1.30",
    memberPrice: "1.15",
    image: "/attached_assets/vimto_500ml.png",
    inStock: 1,
  },
  {
    name: "7UP Zero 2L Bottle",
    description: "Large zero sugar 7UP bottle",
    category: "beverages",
    price: "1.99",
    memberPrice: "1.79",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },
  {
    name: "Aloe Can American Grape 500ml",
    description: "Aloe vera drink with grape flavor",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "Aloe Can Blue Lagoon 500ml",
    description: "Refreshing blue lagoon flavored aloe drink",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "Aloe Can Energy 500ml",
    description: "Aloe vera energy drink for extra boost",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "Aloe Can Fruit Candy 500ml",
    description: "Sweet fruit candy flavored aloe drink",
    category: "beverages",
    price: "1.49",
    memberPrice: "1.29",
    image: "/attached_assets/monster_energy_500ml.png",
    inStock: 1,
  },
  {
    name: "Amigo Apple and Strawberry 200ml",
    description: "Kids fruit drink with apple and strawberry",
    category: "beverages",
    price: "0.79",
    memberPrice: "0.69",
    image: "/attached_assets/tango_orange_500ml.png",
    inStock: 1,
  },
  {
    name: "Amigo Multivitamin 200ml 8-Pack",
    description: "Multivitamin fruit drinks for kids, 8 pack",
    category: "beverages",
    price: "5.49",
    memberPrice: "4.99",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "Appletiser 275ml Bottle",
    description: "Sparkling apple juice made from 100% pressed apples",
    category: "beverages",
    price: "1.79",
    memberPrice: "1.59",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "Appletiser 250ml Bottle",
    description: "Sparkling apple juice in convenient 250ml size",
    category: "beverages",
    price: "1.09",
    memberPrice: "0.99",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Still Natural Mineral Water 330ml 6-Pack",
    description: "Premium natural mineral water from Romania, pack of 6",
    category: "beverages",
    price: "9.60",
    memberPrice: "8.99",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Sparkling Natural Mineral Water 500ml",
    description: "Naturally carbonated mineral water",
    category: "beverages",
    price: "0.80",
    memberPrice: "0.70",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Sparkling Natural Mineral Water 1L",
    description: "Large bottle of sparkling mineral water",
    category: "beverages",
    price: "1.60",
    memberPrice: "1.45",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Sportscap Still Mineral Water 750ml",
    description: "Still mineral water with sport cap",
    category: "beverages",
    price: "1.10",
    memberPrice: "0.99",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Still Natural Mineral Water 1L",
    description: "Premium still mineral water in 1 liter bottle",
    category: "beverages",
    price: "1.69",
    memberPrice: "1.49",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "AQUA Carpatica Still Natural Mineral Water 2L",
    description: "Large 2-liter bottle of still mineral water",
    category: "beverages",
    price: "1.18",
    memberPrice: "1.09",
    image: "/attached_assets/generated_images/Fresh_milk_product_photo_f32b7242.png",
    inStock: 1,
  },
  {
    name: "7UP Regular 330ml Can",
    description: "Classic lemon-lime soda in convenient can size",
    category: "beverages",
    price: "0.75",
    memberPrice: "0.65",
    image: "/attached_assets/sprite_2l.png",
    inStock: 1,
  },

// ===== Brochure Products (imported from PDF) =====
  {
    name: "Red Bull Energy 250ml",
    description: "Energy drink",
    category: "beverages",
    price: "1.55",
    memberPrice: "1.49",
    image: "/attached_assets/product_images/red-bull-energy-250ml-pm.jpg",
    inStock: 50,
  },
  {
    name: "Red Bull Sugar Free 250ml",
    description: "Sugar free energy drink",
    category: "beverages",
    price: "1.50",
    memberPrice: "1.46",
    image: "/attached_assets/product_images/lr-red-bull-sugar-free-250ml-pm.jpg",
    inStock: 50,
  },
  {
    name: "Red Bull Tropical 250ml",
    description: "Tropical flavour energy drink",
    category: "beverages",
    price: "1.55",
    memberPrice: "1.42",
    image: "/attached_assets/product_images/lr-red-bull-tropical-250ml-pm.jpg",
    inStock: 30,
  },
  {
    name: "Red Bull Coconut 250ml",
    description: "Coconut flavour energy drink",
    category: "beverages",
    price: "1.55",
    memberPrice: "1.42",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Red Bull Watermelon 250ml",
    description: "Watermelon flavour energy drink",
    category: "beverages",
    price: "1.55",
    memberPrice: "1.42",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Red Bull Cactus 250ml",
    description: "Cactus flavour energy drink",
    category: "beverages",
    price: "1.55",
    memberPrice: "1.42",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Red Bull Apricot Strawberry 250ml",
    description: "Apricot strawberry flavour energy drink",
    category: "beverages",
    price: "1.55",
    memberPrice: "1.42",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Red Bull Juneberry 250ml",
    description: "Juneberry flavour energy drink",
    category: "beverages",
    price: "1.55",
    memberPrice: "1.42",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Red Bull Winter Spiced Pear 250ml",
    description: "Winter spiced pear energy drink",
    category: "beverages",
    price: "1.55",
    memberPrice: "1.35",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Innocent Mango Passion Fruit Smoothie 250ml",
    description: "Fruit smoothie",
    category: "dairy",
    price: "2.29",
    memberPrice: "1.51",
    image: "/attached_assets/product_images/innocent-mango-pfruit-smooth.jpg",
    inStock: 20,
  },
  {
    name: "Innocent Strawberry Banana Smoothie 250ml",
    description: "Fruit smoothie",
    category: "dairy",
    price: "2.29",
    memberPrice: "1.51",
    image: "/attached_assets/product_images/innocent-stwbry-banana-smoot.jpg",
    inStock: 20,
  },
  {
    name: "Innocent Guava Pineapple Smoothie 250ml",
    description: "Fruit smoothie",
    category: "dairy",
    price: "2.29",
    memberPrice: "1.51",
    image: "/attached_assets/product_images/innocent-guava-pnpple-smth.jpg",
    inStock: 20,
  },
  {
    name: "Jacks Meat Feast Pizza 386g",
    description: "Frozen pizza",
    category: "frozen",
    price: "2.39",
    memberPrice: "2.24",
    image: "/attached_assets/product_images/jacks-meat-feast-pizza-pm239.jpg",
    inStock: 40,
  },
  {
    name: "Jacks Cheese Pizza 386g",
    description: "Frozen pizza",
    category: "frozen",
    price: "2.39",
    memberPrice: "2.24",
    image: "/attached_assets/product_images/jacks-cheese-pizza-pm239-386g.jpg",
    inStock: 40,
  },
  {
    name: "Jacks Skin On Fries 750g",
    description: "Frozen fries",
    category: "frozen",
    price: "1.99",
    memberPrice: "1.74",
    image: "/attached_assets/product_images/jacks-skin-on-fries-pm199.jpg",
    inStock: 40,
  },
  {
    name: "Velvet Classic Quilted Toilet Roll 16 Pack",
    description: "Toilet tissue",
    category: "household",
    price: "7.99",
    memberPrice: "5.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Walkers Cheese & Onion Crisps 150g",
    description: "Potato crisps",
    category: "crisps",
    price: "2.25",
    memberPrice: "2.12",
    image: "/attached_assets/product_images/walkers-chse-and-onin-150g.jpg",
    inStock: 50,
  },
  {
    name: "Walkers Ready Salted Crisps 150g",
    description: "Potato crisps",
    category: "crisps",
    price: "2.25",
    memberPrice: "2.12",
    image: "/attached_assets/product_images/end-1-bb-end-1-hc-walkers-ready-salted-150g.jpg",
    inStock: 50,
  },
  {
    name: "Walkers Salt & Vinegar Crisps 150g",
    description: "Potato crisps",
    category: "crisps",
    price: "2.25",
    memberPrice: "2.12",
    image: "/attached_assets/product_images/end-1-bb-end-1-hc-walkers-salt-vinegar-150g.jpg",
    inStock: 50,
  },
  {
    name: "Cadbury Milk Tray 530g",
    description: "Chocolate selection box",
    category: "treats",
    price: "14.99",
    memberPrice: "10.60",
    image: "attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Hardys Bin 161 Rose Wine 75cl",
    description: "Rose wine",
    category: "alcohol",
    price: "6.99",
    memberPrice: "6.49",
    image: "/attached_assets/product_images/hardys-bin-161-rose-pm699.jpg",
    inStock: 25,
  },
  {
    name: "Hardys Bin 161 Sauvignon Blanc 75cl",
    description: "White wine",
    category: "alcohol",
    price: "6.99",
    memberPrice: "6.49",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 25,
  },
  {
    name: "Hardys Bin 161 Chardonnay 75cl",
    description: "White wine",
    category: "alcohol",
    price: "6.99",
    memberPrice: "6.49",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 25,
  },
  {
    name: "Hardys Bin 161 Pinot Grigio 75cl",
    description: "White wine",
    category: "alcohol",
    price: "6.99",
    memberPrice: "5.79",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 25,
  },
  {
    name: "Hardys Bin 161 Shiraz 75cl",
    description: "Red wine",
    category: "alcohol",
    price: "6.99",
    memberPrice: "6.49",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 25,
  },
  {
    name: "Hardys Bin 161 Merlot 75cl",
    description: "Red wine",
    category: "alcohol",
    price: "6.99",
    memberPrice: "6.49",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 25,
  },
  {
    name: "Cruzcampo Lager 10x440ml",
    description: "Spanish lager",
    category: "alcohol",
    price: "13.99",
    memberPrice: "7.29",
    image: "/attached_assets/product_images/end-1-bb-end-1-hc.jpg",
    inStock: 20,
  },
  {
    name: "Inchs Medium Apple Cider 10x440ml",
    description: "Apple cider",
    category: "alcohol",
    price: "12.49",
    memberPrice: "7.09",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Old Mout Pineapple Raspberry Cider 10x330ml",
    description: "Fruit cider",
    category: "alcohol",
    price: "11.09",
    memberPrice: "7.29",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Sol Lager 12x330ml",
    description: "Mexican lager",
    category: "alcohol",
    price: "14.49",
    memberPrice: "7.49",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Strongbow Cider 10x440ml",
    description: "Apple cider",
    category: "alcohol",
    price: "12.49",
    memberPrice: "7.25",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Carling Lager 10x440ml",
    description: "Lager beer",
    category: "alcohol",
    price: "12.69",
    memberPrice: "6.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Coors Lager 10x440ml",
    description: "Premium lager",
    category: "alcohol",
    price: "13.99",
    memberPrice: "6.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Jacks Cooking Onions 1kg",
    description: "Fresh vegetables",
    category: "produce",
    price: "1.49",
    memberPrice: "0.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Jacks Broccoli 350g",
    description: "Fresh vegetables",
    category: "produce",
    price: "1.49",
    memberPrice: "0.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Jacks White Potatoes 2kg",
    description: "Fresh vegetables",
    category: "produce",
    price: "1.69",
    memberPrice: "1.29",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Jacks Carrots 500g",
    description: "Fresh vegetables",
    category: "produce",
    price: "0.79",
    memberPrice: "0.59",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Reeses Hollow Easter Egg 252g",
    description: "Chocolate easter egg",
    category: "treats",
    price: "6.99",
    memberPrice: "5.10",
    image: "/attached_assets/product_images/reeses-hollow-egg-3-creme.jpg",
    inStock: 15,
  },
  {
    name: "Kit Kat Chunky Biscoff Easter Egg 233g",
    description: "Chocolate easter egg",
    category: "treats",
    price: "7.49",
    memberPrice: "4.88",
    image: "/attached_assets/product_images/kit-kat-chunky-biscoff-egg.jpg",
    inStock: 15,
  },
  {
    name: "Milkybar Giant Egg with Mini Eggs 230g",
    description: "Chocolate easter egg",
    category: "treats",
    price: "7.49",
    memberPrice: "4.88",
    image: "/attached_assets/product_images/milkybar-gnt-egg-mini-eggs.jpg",
    inStock: 15,
  },
  {
    name: "Cadbury Mini Eggs XL Shell Egg 232g",
    description: "Chocolate easter egg",
    category: "treats",
    price: "6.99",
    memberPrice: "5.22",
    image: "attached_assets/placeholder-product.svg",
    inStock: 15,
  },
  {
    name: "Cadbury Creme Egg XL Easter Egg 235g",
    description: "Chocolate easter egg",
    category: "treats",
    price: "6.99",
    memberPrice: "5.22",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 15,
  },
  {
    name: "Celebrations Tub 600g",
    description: "Chocolate selection",
    category: "treats",
    price: "12.25",
    memberPrice: "6.49",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 25,
  },
  {
    name: "Twix White XL Easter Egg 316g",
    description: "Chocolate easter egg",
    category: "treats",
    price: "7.99",
    memberPrice: "6.49",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 15,
  },
  {
    name: "Cadbury Mini Egg Nests 4 Pack",
    description: "Chocolate cakes",
    category: "treats",
    price: "2.59",
    memberPrice: "2.59",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Mr Kipling Lemon Raspberry Mini Battenburgs 5 Pack",
    description: "Cakes",
    category: "bakery",
    price: "1.25",
    memberPrice: "1.25",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Cathedral City Mature Cheddar 350g",
    description: "Cheese",
    category: "dairy",
    price: "4.50",
    memberPrice: "3.85",
    image: "attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Cathedral City Extra Mature Cheddar 350g",
    description: "Extra mature cheese",
    category: "dairy",
    price: "4.75",
    memberPrice: "4.10",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Cathedral City Lighter Cheddar 350g",
    description: "Lighter cheese",
    category: "dairy",
    price: "4.50",
    memberPrice: "3.85",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Wotsits Giants Prawn Cocktail 105g",
    description: "Corn snacks",
    category: "crisps",
    price: "2.50",
    memberPrice: "2.00",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Wotsits Giants Cheese 130g",
    description: "Corn snacks",
    category: "crisps",
    price: "2.50",
    memberPrice: "1.75",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Wotsits Giants Flamin Hot 130g",
    description: "Corn snacks",
    category: "crisps",
    price: "2.50",
    memberPrice: "2.00",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Mogu Mogu Lychee Drink 320ml",
    description: "Nata de coco drink",
    category: "beverages",
    price: "1.29",
    memberPrice: "1.29",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Mogu Mogu Melon Drink 320ml",
    description: "Nata de coco drink",
    category: "beverages",
    price: "1.29",
    memberPrice: "1.29",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Mogu Mogu Mango Drink 320ml",
    description: "Nata de coco drink",
    category: "beverages",
    price: "1.29",
    memberPrice: "1.29",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Pepsi Max 2L",
    description: "Sugar free cola",
    category: "beverages",
    price: "2.29",
    memberPrice: "2.18",
    image: "attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Pepsi Diet 2L",
    description: "Diet cola",
    category: "beverages",
    price: "2.29",
    memberPrice: "2.18",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Pepsi Max Cherry 2L",
    description: "Cherry cola sugar free",
    category: "beverages",
    price: "2.29",
    memberPrice: "2.18",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Pepsi Regular 2L",
    description: "Cola",
    category: "beverages",
    price: "2.59",
    memberPrice: "2.18",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Monster Energy 4x500ml",
    description: "Energy drink multipack",
    category: "beverages",
    price: "5.49",
    memberPrice: "5.73",
    image: "attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Monster Mango Loco 4x500ml",
    description: "Mango energy drink",
    category: "beverages",
    price: "5.49",
    memberPrice: "5.73",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Monster Ultra Energy 4x500ml",
    description: "Sugar free energy drink",
    category: "beverages",
    price: "4.99",
    memberPrice: "5.06",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 30,
  },
  {
    name: "Aero Milk Chocolate Bar 36g",
    description: "Chocolate bar",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Aero Peppermint Chocolate Bar 36g",
    description: "Peppermint chocolate bar",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Kit Kat 4 Finger 41.5g",
    description: "Chocolate wafer bar",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Kit Kat 4 Finger Caramel 41.5g",
    description: "Caramel chocolate wafer",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Kit Kat Chunky 40g",
    description: "Chunky chocolate wafer",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Kit Kat Chunky Runny Caramel 43.5g",
    description: "Caramel filled chocolate wafer",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Kit Kat Chunky Peanut Butter 42g",
    description: "Peanut butter chocolate wafer",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Kit Kat 4 Finger Dark 41.5g",
    description: "Dark chocolate wafer",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Kit Kat 4 Finger White 41.5g",
    description: "White chocolate wafer",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Milkybar 25g",
    description: "White chocolate bar",
    category: "treats",
    price: "0.95",
    memberPrice: "0.83",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Rolo Tube 52g",
    description: "Chocolate caramels",
    category: "treats",
    price: "0.95",
    memberPrice: "0.83",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Smarties Tube 38g",
    description: "Chocolate beans",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 60,
  },
  {
    name: "Smarties White Tube 36g",
    description: "White chocolate beans",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Toffee Crisp Bar 38g",
    description: "Toffee chocolate bar",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Yorkie Milk Chocolate 46g",
    description: "Milk chocolate bar",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Yorkie Raisin Biscuit 44g",
    description: "Raisin biscuit chocolate bar",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Kit Kat Chunky Biscoff White 42g",
    description: "Biscoff white chocolate wafer",
    category: "treats",
    price: "0.95",
    memberPrice: "0.80",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Haribo Tangfastics 140g",
    description: "Sour sweets",
    category: "treats",
    price: "1.25",
    memberPrice: "1.33",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Haribo Starmix 140g",
    description: "Mixed sweets",
    category: "treats",
    price: "1.25",
    memberPrice: "1.33",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Haribo Supermix 140g",
    description: "Mixed sweets",
    category: "treats",
    price: "1.25",
    memberPrice: "1.33",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Haribo Giant Strawbs 140g",
    description: "Strawberry sweets",
    category: "treats",
    price: "1.25",
    memberPrice: "1.33",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 50,
  },
  {
    name: "Haribo Bubblegum Bottles Zing 160g",
    description: "Bubblegum sweets",
    category: "treats",
    price: "1.25",
    memberPrice: "1.33",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Haribo Twin Snakes 160g",
    description: "Gummy snakes",
    category: "treats",
    price: "1.25",
    memberPrice: "1.33",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Haribo Sour Sparks 160g",
    description: "Sour sweets",
    category: "treats",
    price: "1.25",
    memberPrice: "1.33",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "Haribo Soda Twist Zing 160g",
    description: "Soda flavour sweets",
    category: "treats",
    price: "1.25",
    memberPrice: "1.33",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 40,
  },
  {
    name: "McGuigan Black Label Shiraz 75cl",
    description: "Australian red wine",
    category: "alcohol",
    price: "8.69",
    memberPrice: "6.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "McGuigan Black Label Chardonnay 75cl",
    description: "Australian white wine",
    category: "alcohol",
    price: "8.69",
    memberPrice: "6.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "McGuigan Black Label Red 75cl",
    description: "Australian red wine",
    category: "alcohol",
    price: "8.69",
    memberPrice: "6.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "McGuigan Black Label Pinot Grigio 75cl",
    description: "Italian style white wine",
    category: "alcohol",
    price: "8.69",
    memberPrice: "6.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "McGuigan Black Label Sauvignon Blanc 75cl",
    description: "New Zealand style white wine",
    category: "alcohol",
    price: "8.69",
    memberPrice: "6.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Isla Negra Seashore Rose 75cl",
    description: "Chilean rose wine",
    category: "alcohol",
    price: "6.79",
    memberPrice: "5.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Isla Negra Seashore Merlot 75cl",
    description: "Chilean red wine",
    category: "alcohol",
    price: "6.79",
    memberPrice: "5.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Isla Negra Seashore Sauvignon Blanc 75cl",
    description: "Chilean white wine",
    category: "alcohol",
    price: "6.79",
    memberPrice: "5.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Isla Negra Malbec 75cl",
    description: "Chilean red wine",
    category: "alcohol",
    price: "6.79",
    memberPrice: "5.99",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 20,
  },
  {
    name: "Birra Moretti 4x440ml",
    description: "Italian lager",
    category: "alcohol",
    price: "7.79",
    memberPrice: "6.00",
    image: "/attached_assets/placeholder-product.svg",
    inStock: 25,
  },
  {
    name: "Strongbow Dark Fruit Cider 4x440ml",
    description: "Dark fruit cider",
    category: "alcohol",
    price: "6.49",
    memberPrice: "5.87",
    image: "attached_assets/placeholder-product.svg",
    inStock: 30,
  },
];

export async function seedProducts() {
  console.log("Seeding products...");
  
  const existingProducts = await storage.getAllProducts();
  if (existingProducts.length > 0) {
    console.log(`Already have ${existingProducts.length} products, skipping seed`);
    return;
  }

  for (const productData of mockProducts) {
    await storage.createProduct(productData);
  }

  console.log(`Seeded ${mockProducts.length} products successfully`);
}
