import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY);

const existingNames = new Set(JSON.parse(readFileSync('/tmp/existing_names_v2.json', 'utf8')));

function exists(name) {
  return existingNames.has(name.toLowerCase().trim());
}

let idCounter = 0;
function p(name, category, price, description = '') {
  if (exists(name)) return null;
  idCounter++;
  return {
    id: 'inv2-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '').substring(0, 55) + '-' + idCounter,
    name,
    description: description || name,
    category,
    price: price.toFixed(2),
    member_price: null,
    image: '/placeholder-product.png',
    in_stock: 1,
  };
}

// ── CONFECTIONERY ──────────────────────────────────────────────────────────────
const confectionery = [
  // Haribo
  p('Haribo Nostalgix', 'confectionery', 1.00),
  p('Haribo Giant Strawbs', 'confectionery', 1.00),
  p('Haribo Twin Snaks', 'confectionery', 1.00),
  p('Haribo Sour Twist', 'confectionery', 1.00),
  p('Haribo Gold Bears', 'confectionery', 1.00),
  p('Haribo Sour Skeletons', 'confectionery', 1.00),
  p('Haribo Bubblegum Bottle', 'confectionery', 1.00),
  p('Haribo Happy Cola', 'confectionery', 1.00),
  p('Haribo Balla Strix', 'confectionery', 1.00),
  // Bebeto
  p('Bebeto Happy Faces', 'confectionery', 1.00),
  p('Bebeto Just Beans', 'confectionery', 1.00),
  p('Bebeto Happy Laces', 'confectionery', 1.00),
  p('Bebeto Sour Rainbow', 'confectionery', 1.00),
  p('Bebeto Fizzy and Raspberry', 'confectionery', 1.00),
  p('Bebeto Watermelon', 'confectionery', 1.00),
  // Maynards
  p('Maynards Winegums', 'confectionery', 1.00),
  p('Maynards Sour Patch Kids', 'confectionery', 1.00),
  // Rowntrees
  p('Rowntrees Fruit Pastilles', 'confectionery', 1.00),
  p('Rowntrees Fruit Gums', 'confectionery', 1.00),
  p('Rowntrees Pick Mix', 'confectionery', 1.00),
  // Fruittella / Fruttella
  p('Fruttella Berries and Cherry', 'confectionery', 1.00),
  p('Fruittella Berries and Cherry', 'confectionery', 1.00),
  p('Fruittella Summer Fruit', 'confectionery', 1.00),
  // Other sweets
  p('Squashies Bubblegum Flavour', 'confectionery', 1.00),
  p('Jacks Toffees', 'confectionery', 1.00),
  p('Jacks Milk Chocolate Buttons', 'confectionery', 1.00),
  p('Toffee Crumble', 'confectionery', 1.00),
  p('Chupa Chups', 'confectionery', 0.79),
  p('Poppers', 'confectionery', 1.00),
  p('Gummy Rush', 'confectionery', 1.00),
  p('Starburst Fruit Chews', 'confectionery', 1.00),
  p('Maltesers', 'confectionery', 1.25),
  p('Chewits Cherry', 'confectionery', 0.69),
  p('Chewits Fruit Salad', 'confectionery', 0.69),
  // Tic Tac
  p('Tic Tac Berry Bliss', 'confectionery', 0.99),
  p('Tic Tac Cherry Cola', 'confectionery', 0.99),
  p('Tic Tac Lime Orange', 'confectionery', 0.99),
  p('Tic Tac Fruit Adventure', 'confectionery', 0.99),
  p('Tic Tac Fresh Mint', 'confectionery', 0.99),
  // Polo
  p('Polo Mint', 'confectionery', 0.69),
  // Halls / Hall Soothers
  p('Halls Menthol', 'confectionery', 0.99),
  p('Hall Soothers Blackcurrant', 'confectionery', 0.99),
  p('Hall Soothers Peach and Raspberry', 'confectionery', 0.99),
  p('Hall Soothers Honey and Lemon', 'confectionery', 0.99),
  p('Hall Soothers Strawberry', 'confectionery', 0.99),
  // Lockets / Extra Mints
  p('Lockets Honey Lemon', 'confectionery', 0.99),
  p('Lockets Extra Strong', 'confectionery', 0.99),
  p('Extra Mints', 'confectionery', 0.99),
  p('Extra Refreshment', 'confectionery', 0.99),
  p('Extra Strawberry Flavour', 'confectionery', 0.99),
  p('Extra Sugarfree', 'confectionery', 0.99),
  p('Double Mint', 'confectionery', 0.99),
  // Airwaves
  p('Airwaves Cherry Menthol', 'confectionery', 0.99),
  p('Airwaves Blueberry', 'confectionery', 0.99),
  // Orbit
  p('Orbit Strawberry', 'confectionery', 0.99),
  // Werthers
  p('Werthers Original', 'confectionery', 1.00),
  // Chocolate bars - Galaxy, Cadbury, Nestle etc
  p('Galaxy Salt Caramel 135g', 'confectionery', 1.99),
  p('Galaxy Smooth Milk', 'confectionery', 1.49),
  p('Nestle Milkybar Chocolate Flavour', 'confectionery', 1.00),
  p('Nestle Milkybar Smooth and Creamy', 'confectionery', 1.00),
  p('Nestle Aero', 'confectionery', 1.00),
  p('Nestle Aero Hazelnut', 'confectionery', 1.00),
  p('Aero Orange', 'confectionery', 1.00),
  p('Aero Peppermint', 'confectionery', 1.00),
  p('Twirl', 'confectionery', 0.89),
  p('Twirl X-tra', 'confectionery', 1.19),
  p('Kinder Happy Hippo', 'confectionery', 0.99),
  p('Kinder Surprise', 'confectionery', 1.29),
  p('Kinder Country', 'confectionery', 1.29),
  p('Kinder Cards', 'confectionery', 1.49),
  p('Kinder Chocolate', 'confectionery', 0.89),
  p('Kinder Bueno White', 'confectionery', 1.29),
  p('Ferrero Rocher 24pc', 'confectionery', 8.99),
  p('Ferrero Collection 15pc', 'confectionery', 6.99),
  p('Lindt Milk and White 200g', 'confectionery', 3.99),
  p('Lindt Double Choc 200g', 'confectionery', 3.99),
  p('Lindt 200g', 'confectionery', 3.99),
  p('Toblerone', 'confectionery', 2.49),
  p('Danisa Butter Cookies 375g', 'confectionery', 4.99),
  p('Plain Chocolate 100g', 'confectionery', 0.99),
  p('White Chocolate 100g', 'confectionery', 0.99),
  p('Cadbury Dairy Milk 110g', 'confectionery', 1.49),
  p('Nutella Biscuits', 'confectionery', 1.49),
  p('Nestle Damak Ala', 'confectionery', 1.49),
  p('Dairy Milk Caramel 110g', 'confectionery', 1.49),
  p('Caramille 80g', 'confectionery', 1.19),
  p('Cadbury White 90g', 'confectionery', 1.29),
  p('Ginni Sesame Bites', 'confectionery', 1.49),
  p('Crunch', 'confectionery', 0.89),
  p('Nestle Lion Duo 60g', 'confectionery', 1.00),
  p('Nestle Lion Duo 90g', 'confectionery', 1.29),
  p('McVities Club Vites', 'confectionery', 1.19),
  p('Boost 4pc Packet', 'confectionery', 1.49),
  p('Cadbury Double Decker', 'confectionery', 0.99),
  p('Nestle Toffee Crisps', 'confectionery', 0.99),
  p('Crunchie 4pc Packet', 'confectionery', 1.49),
  p('Twix 3x2', 'confectionery', 1.49),
  p('McVities Gold', 'confectionery', 1.19),
  p('Cadbury Smooth Milk', 'confectionery', 1.19),
  p('Gummi Zone Pizza', 'confectionery', 1.49),
  p('Yorkie Original', 'confectionery', 0.99),
  p('Wispa Cadbury', 'confectionery', 0.89),
  p('Twix Salted Caramel', 'confectionery', 0.99),
  p('KitKat Chunky', 'confectionery', 0.99),
  p('KitKat Peanut Butter', 'confectionery', 0.99),
  p('KitKat Funky', 'confectionery', 0.99),
  p('KitKat Cookie Dough', 'confectionery', 0.99),
  p('Cadbury Dairy Milk 45g', 'confectionery', 0.89),
  p('Star Bar Cadbury', 'confectionery', 0.89),
  p('Fudge', 'confectionery', 0.69),
  p('Reeses Peanut Butter Bar', 'confectionery', 0.99),
  p('Mars', 'confectionery', 0.89),
  p('Mars 118g', 'confectionery', 1.29),
  p('Boost', 'confectionery', 0.89),
  p('Snickers Duo', 'confectionery', 1.19),
  p('Snickers Creamy Peanut', 'confectionery', 0.99),
  p('Bounty', 'confectionery', 0.89),
  p('Bounty Crispy Roll', 'confectionery', 0.89),
  p('Tofinck Caramel Wafer', 'confectionery', 0.99),
  p('Lotte Vanilla Strawberry', 'confectionery', 1.49),
  p('Dairy Milk Freddo', 'confectionery', 0.89),
  p('Ice Cream Dips', 'confectionery', 1.19),
  p('Skittles Fruit Flavour', 'confectionery', 0.99),
  p('Skittles Tropical', 'confectionery', 0.99),
  p('M&Ms Crispy', 'confectionery', 1.29),
  p('Chocolate M&Ms', 'confectionery', 1.29),
  p('Tango Shockers', 'confectionery', 0.69),
  p('Tango Shockers Sour Fizz Chew Bar', 'confectionery', 0.99),
  p('Mentos Fanta', 'confectionery', 0.99),
  p('Dairy Milk Caramelnut', 'confectionery', 1.29),
  p('Picnic', 'confectionery', 0.89),
  p('Treat Bag Chocolate M&Ms', 'confectionery', 2.49),
  p('Smarties', 'confectionery', 0.89),
  p('Chomp', 'confectionery', 0.35),
  p('Milky Way', 'confectionery', 0.69),
  p('Milky Way Magic Stars', 'confectionery', 0.89),
  p('Nutella Biscuit Bar', 'confectionery', 0.99),
];

// ── TISSUES / PAPER / KITCHEN ROLL ────────────────────────────────────────────
const household_paper = [
  p('Freedom Inspiration 9 Rolls', 'household', 4.49),
  p('Nicky Elite 9 Rolls', 'household', 3.99),
  p('Nicky Soft Touch 9 Rolls', 'household', 3.99),
  p('Andrex 9 Rolls', 'household', 5.99),
  p('Inspiration Aloe Vera 9 Rolls', 'household', 3.99),
  p('Nicky Elite Enriched with Lotion 9 Rolls', 'household', 4.29),
  p('Regina Gentle Soft 4 Rolls', 'household', 2.49),
  p('Blossom Soft 8 Rolls', 'household', 2.99),
  p('Jacks Soft 4 Rolls', 'household', 1.99),
  p('Inspiration Double Soft Aloe Vera 4 Rolls', 'household', 2.49),
  p('Inspiration Soft White 4 Rolls', 'household', 2.49),
  p('Bloom 4 Rolls', 'household', 2.49),
  p('Andrex 2 Rolls', 'household', 1.49),
  p('Andrex 6 Rolls', 'household', 3.99),
  p('Nicky The Snowman 4 Rolls', 'household', 2.49),
  p('Cushella 4 Rolls', 'household', 2.49),
  p('Hush 4 Rolls', 'household', 2.49),
  p('Blossom Soft 24 Rolls', 'household', 6.99),
  p("Chef's Essential 24 Rolls", 'household', 5.99),
  p('Nicky Jumbo Large Roll', 'household', 1.99),
  p('Plenty Original Large Roll', 'household', 1.99),
  p('Use It 4 Kitchen Towel Roll', 'household', 1.99),
  p('Nicky Lemon Large Kitchen Towel', 'household', 1.99),
  p('Splash Kitchen Roll 2pc', 'household', 1.99),
  p('Nicky Household 2pc', 'household', 2.49),
  p('Freedom 4 Rolls', 'household', 2.49),
  p('Regina Household Towel 1 Roll', 'household', 1.49),
  p('Jacks Multi Purpose 2 Roll', 'household', 1.49),
  p('Rhino Blue 1 Roll', 'household', 0.99),
  p('Inspiration Lemon Fresh 9 Roll', 'household', 3.99),
  p('Inspiration Shea Butter 9 Rolls', 'household', 3.99),
];

// ── BEERS (additional sizes/variants) ─────────────────────────────────────────
const beers = [
  // Bottles 330ml-660ml
  p('Guinness Stout 330ml', 'alcohol', 1.79),
  p('Guinness Stout 325ml', 'alcohol', 1.79),
  p('Dragon Stout 284ml', 'alcohol', 1.79),
  p('Guinness Stout 600ml', 'alcohol', 2.49),
  p('Becks 660ml', 'alcohol', 1.99),
  p('Desperados 650ml', 'alcohol', 2.29),
  p('Budweiser 660ml', 'alcohol', 1.99),
  p('Stella Artois 660ml', 'alcohol', 1.99),
  p('Heineken 650ml', 'alcohol', 1.99),
  p('Corona 620ml', 'alcohol', 2.29),
  p('Staropramen 660ml', 'alcohol', 2.29),
  p('Tyskie 500ml', 'alcohol', 1.79),
  p('Birra Moretti 660ml', 'alcohol', 2.29),
  p('Peroni 620ml', 'alcohol', 2.29),
  p('Guinness West Indies 500ml', 'alcohol', 2.29),
  p('Erdingen Bottle', 'alcohol', 2.49),
  p('Perla 500ml', 'alcohol', 1.79),
  p('Chabbies Ginger Beer 500ml', 'alcohol', 1.79),
  p('Carib Lager 330ml', 'alcohol', 1.79),
  p('San Miguel 330ml', 'alcohol', 1.79),
  p('Thatchers Katy 500ml', 'alcohol', 2.29),
  // VK
  p('VK Strawberry and Lime 70cl', 'alcohol', 2.49),
  p('VK Orange and Passionfruit 70cl', 'alcohol', 2.49),
  // Kopparberg
  p('Kopparberg Raspberry 500ml', 'alcohol', 2.49),
  p('Kopparberg Mixed Fruit 500ml', 'alcohol', 2.49),
  p('Kopparberg Strawberry Lime 500ml', 'alcohol', 2.49),
  p('Thatchers Gold 500ml', 'alcohol', 2.49),
  // Small cans 275-330ml
  p('Budweiser 300ml', 'alcohol', 1.29),
  p('Heineken 330ml', 'alcohol', 1.49),
  p('Heineken 0.0% 330ml', 'alcohol', 1.49),
  p('San Miguel 330ml Can', 'alcohol', 1.49),
  p('Becks Alcohol Free 275ml', 'alcohol', 1.29),
  p('Becks 275ml', 'alcohol', 1.29),
  p('Corona Extra 330ml', 'alcohol', 1.59),
  p('Stella Artois 330ml', 'alcohol', 1.49),
  p('EFES Draft 500ml', 'alcohol', 1.99),
  p('Modelo 355ml', 'alcohol', 1.99),
  p('Peroni 330ml', 'alcohol', 1.79),
  p('Peroni Gluten Free 330ml', 'alcohol', 1.99),
  p('Desperados Original 330ml', 'alcohol', 1.79),
  p('Desperados 250ml', 'alcohol', 1.49),
  p('EFES Draft Can 500ml', 'alcohol', 1.99),
  p('Kampackie 500ml', 'alcohol', 1.79),
  p('Debowa 500ml', 'alcohol', 1.79),
  p('Lech 500ml', 'alcohol', 1.79),
  p('Zywiec 500ml', 'alcohol', 1.79),
  // Big cans 440-568ml
  p('Zubr 500ml', 'alcohol', 1.79),
  p('1664 568ml', 'alcohol', 1.99),
  p('Holsten 568ml', 'alcohol', 1.99),
  p('Holsten 500ml', 'alcohol', 1.79),
  p('Heineken 568ml', 'alcohol', 2.29),
  p('San Miguel 568ml', 'alcohol', 2.29),
  p('Stella Artois 568ml', 'alcohol', 2.29),
  p('Budweiser 568ml', 'alcohol', 2.29),
  p('Birra Moretti 440ml', 'alcohol', 1.99),
  p('Carlsberg 440ml', 'alcohol', 1.79),
  p('Fosters 568ml', 'alcohol', 1.99),
  p('Peroni 440ml Can', 'alcohol', 1.99),
  p('Skol 500ml', 'alcohol', 1.49),
  p('Corona Extra 440ml Can', 'alcohol', 1.99),
  p('1664 440ml Can', 'alcohol', 1.79),
  p('Holsten 440ml', 'alcohol', 1.79),
  p('Desperados 440ml', 'alcohol', 1.99),
  p('Heineken 440ml', 'alcohol', 1.79),
  p('Stella Artois 440ml', 'alcohol', 1.79),
  p('Budweiser 440ml', 'alcohol', 1.79),
  p('Amstel 440ml', 'alcohol', 1.79),
  p('Carlsberg 568ml', 'alcohol', 1.99),
  p('Fosters 440ml', 'alcohol', 1.79),
  p('Guinness 440ml', 'alcohol', 1.99),
  p('Guinness Original 440ml', 'alcohol', 1.99),
  p('Becks 440ml', 'alcohol', 1.79),
  p('Red Stripe 568ml', 'alcohol', 2.29),
  p('Cobra 440ml', 'alcohol', 1.99),
  p('Red Stripe 440ml', 'alcohol', 1.99),
  p('Cruz Campo 568ml', 'alcohol', 1.99),
  p('Black Union Black 500ml', 'alcohol', 1.99),
  p('K Cider 580ml', 'alcohol', 1.99),
  p('Magners 500ml', 'alcohol', 2.29),
  p('Inch\'s 440ml', 'alcohol', 1.99),
  p('Frosty Jakes 500ml', 'alcohol', 1.49),
  p('Omega 500ml Can', 'alcohol', 1.29),
  p('Knight Cider 500ml', 'alcohol', 1.29),
  p('White Storm 500ml', 'alcohol', 1.49),
  p('Black Storm 500ml', 'alcohol', 1.49),
  // Strongbow
  p('Strongbow Strawberry Cider 330ml', 'alcohol', 1.79),
  p('Strongbow Dark Fruit Cider 568ml', 'alcohol', 2.29),
  p('Strongbow 940ml', 'alcohol', 3.49),
  p('Strongbow Cloudy Apple 440ml', 'alcohol', 1.99),
  p('Strongbow Rose Cider 440ml', 'alcohol', 1.99),
  p('Strongbow Original 940ml', 'alcohol', 3.49),
  p('Strongbow Original 568ml', 'alcohol', 2.29),
  p('Crumpton Oaks 568ml', 'alcohol', 1.79),
  p('Staropramen 440ml', 'alcohol', 1.99),
  p('Omega White Cider 1 Litre', 'alcohol', 2.49),
  // Large format ciders
  p('White Storm White Cider 2.5 Litre', 'alcohol', 3.99),
  p('Lambrini Original 1.25 Litre', 'alcohol', 3.49),
  p('Lambrini Original 750ml', 'alcohol', 2.99),
  p('Omega White Cider 2.5 Litre', 'alcohol', 3.99),
  p('Strongbow Original Cider 2 Litre', 'alcohol', 4.49),
  p('Crumpton Oak Apple Cider 2.5 Litre', 'alcohol', 3.99),
  // RTD / premixed
  p('Smirnoff Ice Original 250ml', 'alcohol', 1.99),
  p('Smirnoff Ice Original 275ml', 'alcohol', 1.99),
  p('Smirnoff Vodka Kola 250ml', 'alcohol', 1.99),
  p('Smirnoff Tropical 70cl', 'alcohol', 3.99),
  p('Smirnoff Original 70cl Bottle', 'alcohol', 3.99),
  p('WKD Blue Vodka 275ml', 'alcohol', 1.99),
  p('WKD Iron Brew Vodka 700ml', 'alcohol', 3.99),
  p('Absolut Raspberry Lemonade 250ml', 'alcohol', 2.29),
  p('Captain Morgan 250ml RTD', 'alcohol', 2.29),
  p('Jack Daniels 330ml RTD', 'alcohol', 2.29),
  p('Gordons Gin and Tonic 250ml', 'alcohol', 2.29),
  p('Bacardi Mango 250ml', 'alcohol', 2.29),
  p('Malibu Cola 250ml', 'alcohol', 2.29),
  p('Ciroc Summer Citrus 258ml', 'alcohol', 2.49),
  p('Absolut Cocktails 250ml', 'alcohol', 2.49),
  p('Absolut Cocktails Espresso Martini 250ml', 'alcohol', 2.49),
];

// ── WINES (additional variants not yet in DB) ──────────────────────────────────
const wines = [
  p('Entwine Sauvignon 750ml', 'alcohol', 6.99),
  p('Entwine Shiraz Rose 750ml', 'alcohol', 6.99),
  p('Rosemount Estate Chardonnay 750ml', 'alcohol', 8.99),
  p('Saint Mania Gold Liebtraum 750ml', 'alcohol', 6.99),
  p('Marco Maci Cinque Lune 750ml', 'alcohol', 8.99),
  p('PC Cream 75cl', 'alcohol', 6.99),
  p('Vendicco Classico 750ml', 'alcohol', 7.99),
  p('El Bombeno 70cl', 'alcohol', 6.99),
  p('Bannock Pink Moscato 750ml', 'alcohol', 6.99),
  p('Inkosi Sauvignon Blanc 750ml', 'alcohol', 6.99),
  p('Yaarunga Field Bin 303 750ml', 'alcohol', 7.99),
  p('Lime Leaf Verde Jo 75cl', 'alcohol', 6.99),
  p('Pink Damner White 75cl', 'alcohol', 6.99),
  p('Cascata Vinho Verde 750ml', 'alcohol', 6.99),
  p('Stones and Bones 750ml', 'alcohol', 7.99),
  p('Lunatic Fringe 75cl', 'alcohol', 7.99),
  p('Cable de France 75cl', 'alcohol', 6.99),
  p('Raspberry Bush 75cl', 'alcohol', 6.99),
  p('Rex Mudi Shiraz 75cl', 'alcohol', 7.99),
  p('Lindemans Chardonnay 75cl', 'alcohol', 7.49),
  p('Lindemans Sauvignon Blanc 750ml', 'alcohol', 7.49),
  p('Lindemans Merlot B40 750ml', 'alcohol', 7.49),
  p('Lindemans Rose Bin 750ml', 'alcohol', 7.49),
  p('Western Cape Chardonnay 750ml', 'alcohol', 6.99),
  p('Opi Malbec 75cl', 'alcohol', 8.99),
  p('Bills and Sons Shiraz Durif 750ml', 'alcohol', 7.99),
  p('Pattes Noines Merlot 750ml', 'alcohol', 7.99),
  p('Queen Bee 750ml', 'alcohol', 7.99),
  p('Bees Knees Blanc 750ml', 'alcohol', 7.99),
  p('Cable MMXXI 750ml', 'alcohol', 7.99),
  p('Nozeco Sparkling Non Alcoholic 750ml', 'alcohol', 4.99),
  p('Brass Monkey 750ml', 'alcohol', 7.99),
  p('Leimoin Tree 750ml', 'alcohol', 7.99),
  p('Vertiges Paradis 750ml', 'alcohol', 7.99),
  p('Cinzano Bianco 750ml', 'alcohol', 7.49),
  p('Most Wanted Malbac 750ml', 'alcohol', 7.99),
  p('I Heart Merlot 750ml', 'alcohol', 7.49),
  p('I Heart Rose Fruity 70cl', 'alcohol', 7.49),
  p('I Heart Chardonnay 750ml', 'alcohol', 7.49),
  p('Kumala Pinotage 750ml', 'alcohol', 6.99),
  p('Kumala Rose 750ml', 'alcohol', 6.99),
  p('Hardy\'s Merlot 750ml', 'alcohol', 7.49),
  p("Hardy's Rose 75cl", 'alcohol', 7.49),
  p("Hardy's VR Pinot Grigio 750ml", 'alcohol', 7.49),
  p('McGuigan Black Label Red 750ml', 'alcohol', 7.49),
  p('El Bombero 750ml', 'alcohol', 6.99),
  p('The Black Trump 750ml', 'alcohol', 7.49),
  p('Fine and Foul Sauvignon Blanc 750ml', 'alcohol', 7.99),
  p('Alessandro Gallici Pinot Grigio 750ml', 'alcohol', 8.99),
  p('First Cape Chips and Fruity 750ml', 'alcohol', 6.99),
  p('7 Heart Chardonnay 750ml', 'alcohol', 7.49),
  p('Purato Pinot Grigio 750ml', 'alcohol', 7.99),
  p('Mateus Rose 750ml', 'alcohol', 6.99),
  p('Mateus Rose Original 187ml', 'alcohol', 2.99),
  p('Isla Negra Sauvignon Blanc 750ml', 'alcohol', 7.49),
  p('Isla Negra Malbac 750ml', 'alcohol', 7.49),
  p('Isla Negra Rose 750ml', 'alcohol', 7.49),
  p('BIN 201 750ml', 'alcohol', 7.99),
  p('Quickly Bird Shiraz Red 750ml', 'alcohol', 7.49),
  p('Oxford Landing Pinot 750ml', 'alcohol', 7.99),
  p('JP Chenet Colombard Chardonnay 750ml', 'alcohol', 6.99),
  p('Gallo Merlot 70cl', 'alcohol', 6.99),
  p('Gallo Family Cabernet 750ml', 'alcohol', 7.49),
  p('Gallo Family Moscato 750ml', 'alcohol', 7.49),
  p('Gallo Family Pineapple and Passionfruit 750ml', 'alcohol', 7.49),
  p('Red Label Aperitif 750ml', 'alcohol', 5.99),
  p('Campo Viejo Boamistuna 750ml', 'alcohol', 7.99),
  p('Casillero de Diablo 750ml', 'alcohol', 8.49),
  p('Casillero del Malbac 750ml', 'alcohol', 8.49),
  p('Casillero de Diablo Rose', 'alcohol', 8.49),
  p('Casillero del Diablo Pinot Grigio 750ml', 'alcohol', 8.49),
  p('Eisberg Rose Non Alcoholic 750ml', 'alcohol', 4.99),
  p('Casillero de Diablo Pinot Grigio 750ml', 'alcohol', 8.49),
  p('Blossom Hill Oak Rose 750ml', 'alcohol', 6.49),
  p('Black Tower 750ml', 'alcohol', 6.99),
  p('Black Tower White 750ml', 'alcohol', 6.99),
  p('Black Tower Pinot Grigio 750ml', 'alcohol', 6.99),
  p('Black Tower Rose 750ml', 'alcohol', 6.99),
  p('Barefoot Pinot Grigio 750ml', 'alcohol', 7.49),
  p('Barefoot White 187ml', 'alcohol', 2.99),
  p('Distant Vines Pinot Grigio 750ml', 'alcohol', 6.99),
  p('Blossom Hill Sauvignon Blanc 750ml', 'alcohol', 6.49),
  p('Central Merlot 750ml', 'alcohol', 6.99),
  p('Barefoot Cabernet Sauvignon 750ml', 'alcohol', 7.49),
  p('Maria Fadista Rose 75cl', 'alcohol', 7.49),
  // Sparkling / Champagne / Prosecco
  p('Moet Chandon 750ml', 'alcohol', 34.99),
  p('Paul Longies 750ml', 'alcohol', 18.99),
  p('Prosecco Rossi 750ml', 'alcohol', 8.99),
  p('Cortissier 750ml', 'alcohol', 14.99),
  p('Martini Asti 750ml', 'alcohol', 8.99),
  p('GP Chenet 750ml', 'alcohol', 7.99),
  p('Fili Prosecco 70cl', 'alcohol', 8.99),
  p('Bottega Nella 70cl', 'alcohol', 9.99),
  p('Echo Falls Sparkling 187ml', 'alcohol', 2.99),
];

// ── SPIRITS ───────────────────────────────────────────────────────────────────
const spirits = [
  // Absolut
  p('Absolut Mango 70cl', 'alcohol', 18.99),
  p('Absolut Passionfruit 70cl', 'alcohol', 18.99),
  p('Absolut Vanilla 70cl', 'alcohol', 18.99),
  p('Absolut Mandarin 70cl', 'alcohol', 18.99),
  p('Absolut Raspberry 70cl', 'alcohol', 18.99),
  p('Absolut Wild Berry 70cl', 'alcohol', 18.99),
  p('Absolut Pears 70cl', 'alcohol', 18.99),
  p('Absolut Watermelon 70cl', 'alcohol', 18.99),
  p('Absolut Citron 70cl', 'alcohol', 18.99),
  p('Absolut Original 70cl', 'alcohol', 18.99),
  p('Absolut Vodka 35cl', 'alcohol', 10.99),
  p('Absolut Vodka 20cl', 'alcohol', 7.99),
  p('Absolut Vodka 5cl', 'alcohol', 2.49),
  // Grey Goose
  p('Grey Goose 35cl', 'alcohol', 19.99),
  p('Grey Goose 70cl', 'alcohol', 34.99),
  // AU Vodka
  p('AU Vodka Blue Raspberry 35cl', 'alcohol', 14.99),
  p('AU Vodka Bubble Gum 70cl', 'alcohol', 24.99),
  p('AU Vodka Grape 5cl', 'alcohol', 2.99),
  p('AU Strawberry Vodka 5cl', 'alcohol', 2.99),
  // Ciroc
  p('Ciroc Apple 70cl', 'alcohol', 29.99),
  p('Ciroc Pineapple 70cl', 'alcohol', 29.99),
  p('Ciroc Limonato 70cl', 'alcohol', 29.99),
  p('Ciroc Mango 70cl', 'alcohol', 29.99),
  p('Ciroc Coconut 70cl', 'alcohol', 29.99),
  p('Ciroc Pomegranate 70cl', 'alcohol', 29.99),
  p('Ciroc Mango French Vodka 70cl', 'alcohol', 29.99),
  p('Ciroc Original 70cl', 'alcohol', 29.99),
  // MD 20/20
  p('MD 20/20 Golden Pineapple 75cl', 'alcohol', 3.99),
  p('MD 20/20 Dragon Fruit 75cl', 'alcohol', 3.99),
  p('MD 20/20 Kiwi 75cl', 'alcohol', 3.99),
  // Campari
  p('Campari 70cl', 'alcohol', 17.99),
  // Smirnoff
  p('Smirnoff Vanilla 70cl', 'alcohol', 14.99),
  p('Smirnoff Vodka 1 Litre', 'alcohol', 22.99),
  p('Smirnoff Vodka 35cl', 'alcohol', 10.99),
  p('Smirnoff Vodka 70cl', 'alcohol', 16.99),
  p('Smirnoff Vodka 20cl', 'alcohol', 7.99),
  p('Smirnoff Vodka 5cl', 'alcohol', 1.99),
  p('Smirnoff Spicy Tamarind 70cl', 'alcohol', 16.99),
  p('Smirnoff Peach 70cl', 'alcohol', 16.99),
  // Vodka generic / other
  p('Vodka Prince Consort 70cl', 'alcohol', 9.99),
  p('Prince Consort Vodka 20cl', 'alcohol', 4.99),
  p("Glen's Vodka 35cl", 'alcohol', 7.99),
  p("Glen's Vodka 1 Litre", 'alcohol', 14.99),
  p("Glen's Vodka 70cl", 'alcohol', 10.99),
  p("Glen's Vodka 20cl", 'alcohol', 4.99),
  p("Glen's Vodka 5cl", 'alcohol', 1.49),
  p('Wray and Nephew 70cl', 'alcohol', 19.99),
  p('Wray Nephew 35cl', 'alcohol', 10.99),
  p('Wray Nephew 20cl', 'alcohol', 7.49),
  p('Wray Nephew 5cl', 'alcohol', 1.99),
  p('Zubrowka Vodka 70cl', 'alcohol', 14.99),
  p('Zubrowka 35cl', 'alcohol', 8.99),
  p('Zubrowka 20cl', 'alcohol', 5.99),
  p('Finlandia Vodka 70cl', 'alcohol', 14.99),
  p('Russian Standard 70cl', 'alcohol', 16.99),
  p('Russian Standard 1 Litre', 'alcohol', 22.99),
  // Rum
  p('Bacardi 1 Litre', 'alcohol', 19.99),
  p('Bacardi Rum 70cl', 'alcohol', 14.99),
  p('Bacardi 35cl', 'alcohol', 9.99),
  p('Bacardi 20cl', 'alcohol', 6.99),
  p('Bacardi 5cl', 'alcohol', 1.99),
  p('Captain Morgan White Rum 70cl', 'alcohol', 14.99),
  p('Captain Morgan Dark Rum 70cl', 'alcohol', 14.99),
  p('Captain Morgan Dark Rum 1 Litre', 'alcohol', 21.99),
  p('Captain Morgan Dark Rum 35cl', 'alcohol', 9.99),
  p('Captain Morgan Dark Rum 20cl', 'alcohol', 6.99),
  p('Captain Morgan Spice Gold 70cl', 'alcohol', 14.99),
  p('Captain Morgan Spice Gold 1 Litre', 'alcohol', 21.99),
  p('Captain Morgan Spice Gold 35cl', 'alcohol', 9.99),
  p('Captain Morgan Spice Gold 20cl', 'alcohol', 6.99),
  p('Captain Morgan Black Spiced 70cl', 'alcohol', 16.99),
  p('Kopparberg Rum 70cl', 'alcohol', 14.99),
  p('Sandeman Fine Wine 70cl', 'alcohol', 9.99),
  p('Cocspuz Fine Rum 70cl', 'alcohol', 9.99),
  p('WHA GWAV Rum Cream 20cl', 'alcohol', 4.99),
  // Brandy
  p('Bols Apricot Brandy 500ml', 'alcohol', 12.99),
  p('Jules Claizon Brandy 70cl', 'alcohol', 12.99),
  p('Jules Claizon 35cl', 'alcohol', 7.99),
  p('Jules Claizon 20cl', 'alcohol', 5.49),
  p('Jules Claizon 5cl', 'alcohol', 1.49),
  p('EJ Brandy 70cl', 'alcohol', 9.99),
  p('EJ Brandy 35cl', 'alcohol', 5.99),
  p('EJ Brandy 20cl', 'alcohol', 3.99),
  p('Three Barrels Brandy 70cl', 'alcohol', 12.99),
  p('Three Barrels 35cl', 'alcohol', 7.49),
  p('Prince Consort Brandy 35cl', 'alcohol', 6.99),
  p('Prince Consort Brandy 20cl', 'alcohol', 4.49),
  // Whiskey
  p('Red Label 70cl', 'alcohol', 19.99),
  p('Black Label 70cl', 'alcohol', 29.99),
  p('Black Label 5cl', 'alcohol', 2.99),
  p('Jameson Whiskey 35cl', 'alcohol', 14.99),
  p('Jameson Whiskey 70cl', 'alcohol', 22.99),
  p('Jameson 20cl', 'alcohol', 8.99),
  p('Jameson 5cl', 'alcohol', 2.49),
  p('Southern Comfort 70cl', 'alcohol', 14.99),
  p('Southern Comfort 35cl', 'alcohol', 8.99),
  p('Southern Comfort 20cl', 'alcohol', 6.49),
  p('Grants Whiskey 70cl', 'alcohol', 13.99),
  p('Grants 35cl', 'alcohol', 7.99),
  p('Grants 20cl', 'alcohol', 5.49),
  p('Bells Whiskey 70cl', 'alcohol', 14.99),
  p('Bells Whiskey 1 Litre', 'alcohol', 20.99),
  p('Bells 35cl', 'alcohol', 8.99),
  p('Bells 20cl', 'alcohol', 5.99),
  p('Bells 5cl', 'alcohol', 1.99),
  p('High Commissioner Whiskey 70cl', 'alcohol', 11.99),
  p('High Commissioner 35cl', 'alcohol', 6.99),
  p('High Commissioner 20cl', 'alcohol', 4.49),
  p('High Commissioner 5cl', 'alcohol', 1.49),
  p('The Famous Grouse Whiskey 70cl', 'alcohol', 17.99),
  p('The Famous Grouse Whiskey 1 Litre', 'alcohol', 24.99),
  p('The Famous Grouse 35cl', 'alcohol', 10.99),
  p('The Famous Grouse 5cl', 'alcohol', 2.49),
  p('Claymore 20cl', 'alcohol', 4.49),
  p('Claymore 35cl', 'alcohol', 6.99),
  p('Woodford Reserve Whisky 70cl', 'alcohol', 34.99),
  p('Jura Whiskey 70cl', 'alcohol', 29.99),
  p('Glenfiddich 35cl', 'alcohol', 19.99),
  p('Glenmorangie 70cl', 'alcohol', 34.99),
  p('HAIG Club 70cl', 'alcohol', 29.99),
  p('Chivas Regal 70cl', 'alcohol', 24.99),
  p('Chivas Regal 35cl', 'alcohol', 14.99),
  p('Jack Daniels Original 70cl', 'alcohol', 22.99),
  p('Jack Daniels Original 1 Litre', 'alcohol', 29.99),
  p('Jack Daniels Apple 70cl', 'alcohol', 22.99),
  p('Jack Daniels Apple 35cl', 'alcohol', 12.99),
  p('Jack Daniels Cinnamon Spice 70cl', 'alcohol', 22.99),
  p('Jack Daniels Honey 35cl', 'alcohol', 12.99),
  p('Jack Daniels Honey 5cl', 'alcohol', 2.49),
  p('Jack Daniels Original 35cl', 'alcohol', 12.99),
  p('Jack Daniels Original 5cl', 'alcohol', 2.49),
  p('Jack Daniels Original 20cl', 'alcohol', 7.99),
  p('Jack Daniels 10cl', 'alcohol', 4.99),
  p('Jim Beam Whiskey 70cl', 'alcohol', 17.99),
  p('Jim Beam 20cl', 'alcohol', 6.99),
  p('White Mackay Whiskey 70cl', 'alcohol', 11.99),
  p('White Mackay 20cl', 'alcohol', 4.99),
  p('White Mackay 3cl', 'alcohol', 2.49),
  p('Remy Martin 70cl', 'alcohol', 29.99),
  p('Remy Martin Cognac 1738 70cl', 'alcohol', 39.99),
  p('Taylors 70cl', 'alcohol', 14.99),
  // Cognac
  p('Courvoisier Cognac 70cl', 'alcohol', 22.99),
  p('Courvoisier 35cl', 'alcohol', 12.99),
  p('Courvoisier 20cl', 'alcohol', 8.49),
  p('Courvoisier 5cl', 'alcohol', 2.49),
  p('Hennessy Cognac 70cl', 'alcohol', 29.99),
  p('Hennessy 35cl', 'alcohol', 16.99),
  p('Hennessy 20cl', 'alcohol', 10.49),
  p('Mortell 70cl', 'alcohol', 9.99),
  p('Mortell 35cl', 'alcohol', 5.99),
  p('Mortell 20cl', 'alcohol', 4.49),
  p('Mortell 5cl', 'alcohol', 1.49),
  p('Mortel Cognac 70cl', 'alcohol', 14.99),
  // Gin
  p('Gordons Pink 70cl', 'alcohol', 17.99),
  p('Gordons Dry Gin 70cl', 'alcohol', 17.99),
  p('Gordons Dry Gin 1 Litre', 'alcohol', 23.99),
  p('Gordons Pink 35cl', 'alcohol', 10.99),
  p('Gordons Dry Gin 35cl', 'alcohol', 10.99),
  p('Gordons Dry Gin 20cl', 'alcohol', 7.49),
  p('Gordons Dry Gin 5cl', 'alcohol', 1.99),
  p('London Dry Gin 70cl', 'alcohol', 9.99),
  p('Bombay Sapphire 70cl', 'alcohol', 22.99),
  // Tequila / Liqueurs
  p('Sierra Tropical Chilli 70cl', 'alcohol', 16.99),
  p('Sierra Tequila 70cl', 'alcohol', 16.99),
  p('Sierra Tequila 35cl', 'alcohol', 9.99),
  p('Alize Gold Passion 70cl', 'alcohol', 17.99),
  p('Alize Red Passion 70cl', 'alcohol', 17.99),
  p('Faustino Wine 75cl', 'alcohol', 9.99),
  p('Jagermeister 35cl', 'alcohol', 12.99),
  p('Jagermeister 50cl', 'alcohol', 17.99),
  p('Jagermeister 70cl', 'alcohol', 22.99),
  p('Malibu 70cl', 'alcohol', 14.99),
  p('Malibu 35cl', 'alcohol', 8.99),
  p('Malibu 20cl', 'alcohol', 5.99),
  p('Malibu 5cl', 'alcohol', 1.49),
  p('Malibu Red 70cl', 'alcohol', 14.99),
  p('Baileys Original 70cl', 'alcohol', 14.99),
  p('Baileys Orange 50cl', 'alcohol', 11.99),
  p('Baileys 35cl', 'alcohol', 9.99),
  p('Baileys 5cl', 'alcohol', 1.99),
  p('Tia Maria Coffee Liqueur 35cl', 'alcohol', 12.99),
  p('Glenfildich 35cl', 'alcohol', 19.99),
  p('Bollinger Champagne 750ml', 'alcohol', 44.99),
  // Buzz Bolz
  p('Buzz Bolz Passionfruit Martini 20cl', 'alcohol', 4.49),
  p('Buzz Bolz Strawberry 20cl', 'alcohol', 4.49),
  p('Buzz Bolz Espresso Martini 20cl', 'alcohol', 4.49),
  p('Buzz Bolz Tequila Rita 20cl', 'alcohol', 4.49),
  p('Buzz Bolz Lotta Colada 20cl', 'alcohol', 4.49),
  p('Buzz Bolz Chili Mango 20cl', 'alcohol', 4.49),
  // Tonic wine
  p('Magnum Tonic Wine 20cl', 'alcohol', 2.49),
  p('Rude Boy Tonic Wine 20cl', 'alcohol', 2.49),
  p('Red Label Tonic Wine 20cl', 'alcohol', 2.49),
  p('Ragga Tonic Wine 20cl', 'alcohol', 2.49),
  p('Cherry B Tonic Wine 20cl', 'alcohol', 2.49),
  // Other
  p('Martini Rosso 70cl', 'alcohol', 9.99),
  p('Martini Bianco 70cl', 'alcohol', 9.99),
  p('Martini Asti 75cl', 'alcohol', 8.99),
];

// ── TOBACCO / CIGARETTES ──────────────────────────────────────────────────────
const tobacco = [
  // HEETS
  p('Heets Green', 'tobacco', 5.99),
  p('Heets Selection', 'tobacco', 5.99),
  p('Heets Mauve', 'tobacco', 5.99),
  p('Heets Yellow', 'tobacco', 5.99),
  p('Heets Russet', 'tobacco', 5.99),
  p('Heets Teak', 'tobacco', 5.99),
  p('Heets Siena', 'tobacco', 5.99),
  // Terea
  p('Terea Amber', 'tobacco', 5.99),
  p('Terea Mauve', 'tobacco', 5.99),
  p('Terea Yellow', 'tobacco', 5.99),
  p('Terea Blue', 'tobacco', 5.99),
  p('Terea Pearl', 'tobacco', 5.99),
  p('Terea Turquoise', 'tobacco', 5.99),
  p('Terea Russet', 'tobacco', 5.99),
  // Cigarettes - Embassy
  p('Embassy Filter K/S', 'tobacco', 11.50),
  p('Embassy Gold K/S', 'tobacco', 11.50),
  p('Embassy Gold S/K', 'tobacco', 11.50),
  p('Embassy Signature S/K', 'tobacco', 11.50),
  p('Embassy Signature K/S', 'tobacco', 11.50),
  // Vogue
  p('Vogue Cigarettes', 'tobacco', 11.50),
  // Marlboro
  p('Marlboro Gold', 'tobacco', 12.50),
  p('Marlboro Touch', 'tobacco', 12.50),
  p('Marlboro Red', 'tobacco', 12.50),
  p('Marlboro 30gr', 'tobacco', 11.99),
  // Rothmans
  p('Rothmans Silver', 'tobacco', 11.50),
  p('Rothmans Blue', 'tobacco', 11.50),
  p('Rothmans Silver K/S', 'tobacco', 11.50),
  p('Rothmans Blue S/K', 'tobacco', 11.50),
  // Silkcut
  p('Silkcut Purple', 'tobacco', 11.50),
  p('Silkcut Silver', 'tobacco', 11.50),
  // Players
  p('Players Red S/K', 'tobacco', 11.00),
  p('Players Bright', 'tobacco', 11.00),
  p('Players Bright S/K', 'tobacco', 11.00),
  // Carlton
  p('Carlton Original', 'tobacco', 10.99),
  p('Carlton Original S/K', 'tobacco', 10.99),
  // YMB
  p('YMB Blue', 'tobacco', 10.99),
  p('YMB Silver', 'tobacco', 10.99),
  // American Spirit
  p('American Spirit Yellow', 'tobacco', 12.99),
  p('American Spirit Blue 30gr', 'tobacco', 11.99),
  // Pall Mall
  p('Pall Mall Red S/K', 'tobacco', 10.99),
  p('Pall Mall Blue S/K', 'tobacco', 10.99),
  p('Pall Mall Blue K/S', 'tobacco', 10.99),
  p('Pall Mall Red K/S', 'tobacco', 10.99),
  p('Pall Mall 30gr', 'tobacco', 11.99),
  // Richmond
  p('Richmond Original S/K', 'tobacco', 10.99),
  p('Richmond Green S/K', 'tobacco', 10.99),
  p('Richmond Original K/S', 'tobacco', 10.99),
  p('Richmond Compact', 'tobacco', 10.99),
  // Sovereign
  p('Sovereign Blue S/K', 'tobacco', 10.50),
  p('Sovereign Blue K/S', 'tobacco', 10.50),
  p('Sovereign Sky Blue', 'tobacco', 10.50),
  p('Sovereign Black', 'tobacco', 10.50),
  // Lucky Strike
  p('Lucky Strike', 'tobacco', 11.50),
  p('Lucky Strike S/K', 'tobacco', 11.50),
  // Benson
  p('Benson Gold', 'tobacco', 11.50),
  p('Benson Silver K/S', 'tobacco', 11.50),
  p('Benson Dual', 'tobacco', 11.50),
  p('Benson Blue Dual', 'tobacco', 11.50),
  p('Benson Sky Blue', 'tobacco', 11.50),
  p('Benson Blue S/K', 'tobacco', 11.50),
  p('Benson Sky Blue S/K', 'tobacco', 11.50),
  p('Benson Green S/K', 'tobacco', 11.50),
  p('Benson Blue 30gr', 'tobacco', 11.99),
  p('Benson Silver 30gr', 'tobacco', 11.99),
  // Sterling
  p('Sterling K/S', 'tobacco', 10.99),
  p('Sterling Double Capsules', 'tobacco', 10.99),
  p('Sterling 50gr', 'tobacco', 19.99),
  p('Sterling 3 in 1 30gr', 'tobacco', 11.99),
  // Mayfair
  p('Mayfair Silver', 'tobacco', 10.50),
  p('Mayfair Gold', 'tobacco', 10.50),
  p('Mayfair Blue Sky K/S', 'tobacco', 10.50),
  p('Mayfair Sky Blue S/K', 'tobacco', 10.50),
  p('Mayfair Blue', 'tobacco', 10.50),
  p('Mayfair 30gr', 'tobacco', 11.99),
  // Chesterfield
  p('Chesterfield Blue', 'tobacco', 10.99),
  p('Chesterfield Red S/K', 'tobacco', 10.99),
  // Winston
  p('Winston Blue', 'tobacco', 11.50),
  // Rolling tobacco
  p('Golden Virginia 30gr', 'tobacco', 11.99),
  p('Golden Virginia Yellow 30gr', 'tobacco', 11.99),
  p('Golden Virginia Yellow', 'tobacco', 11.99),
  p('Old Holborn 30gr', 'tobacco', 11.99),
  p('Riverston 30gr', 'tobacco', 10.99),
  p('Amber Leaf 30gr', 'tobacco', 11.99),
  p('Amber Leaf Original 30gr', 'tobacco', 11.99),
  p('Amber Leaf 3 in 1 30gr', 'tobacco', 11.99),
  p('Amber Leaf 50gr', 'tobacco', 18.99),
  p('Gold Leaf 30gr', 'tobacco', 10.99),
  p('Gold Leaf 50gr', 'tobacco', 17.99),
  // Rolling papers / accessories
  p('OSB Black Rolling Papers', 'tobacco', 0.99),
  p('OSB Brown Rolling Papers', 'tobacco', 0.99),
  p('OSB Blue Rolling Papers', 'tobacco', 0.99),
  p('Rizla Red', 'tobacco', 0.99),
  p('Rizla Rich Liquorice', 'tobacco', 0.99),
  p('Rizla Blue K/S', 'tobacco', 0.99),
  p('Rizla Blue', 'tobacco', 0.99),
  p('Rizla Green K/S', 'tobacco', 0.99),
  p('Rizla Green', 'tobacco', 0.99),
  p('Rizla Silver K/S', 'tobacco', 0.99),
  p('Rizla Silver', 'tobacco', 0.99),
  p('Rizla Elements', 'tobacco', 0.99),
  p('Raw Tips', 'tobacco', 0.99),
  p('Raw Papers', 'tobacco', 0.99),
  p('Raw Slim', 'tobacco', 0.99),
  p('Raw with Tips', 'tobacco', 0.99),
  p('Raw K/S', 'tobacco', 0.99),
  p('Raw Black', 'tobacco', 0.99),
  p('Raw Black Tips', 'tobacco', 0.99),
  p('Raw Black No Tips', 'tobacco', 0.99),
  p('Swan Extra Slim', 'tobacco', 0.99),
  p('Swan Menthol Extra Slim', 'tobacco', 0.99),
  p('Jumbo Cone', 'tobacco', 1.49),
  p('Jumbo Brown Cone', 'tobacco', 1.49),
  p('OCB Cone Black', 'tobacco', 1.49),
  p('OCB Cone Brown', 'tobacco', 1.49),
  p('Extra Slim Menthol Filter', 'tobacco', 1.49),
  p('Ultra Slim Filter', 'tobacco', 1.49),
  p('Crystal Polar Blast Filter', 'tobacco', 1.49),
  p('Blunt Wrap Red', 'tobacco', 1.49),
  p('Blunt Wrap Pink', 'tobacco', 1.49),
  p('Blunt Wrap Blue', 'tobacco', 1.49),
  p('Blunt Wrap Yellow', 'tobacco', 1.49),
  // Velo / Nicotine pouches
  p('Velo Watermelon Ice', 'tobacco', 5.99),
  p('Velo Freezing Peppermint', 'tobacco', 5.99),
  p('Velo Purple Grape', 'tobacco', 5.99),
  p('Nordic Spirit', 'tobacco', 5.99),
  p('Nordic Spirit Sweet Mint', 'tobacco', 5.99),
  p('Nordic Spirit Spearmint', 'tobacco', 5.99),
  p('Nordic Spirit Mint', 'tobacco', 5.99),
];

// ── VAPE ──────────────────────────────────────────────────────────────────────
const vape = [
  p('Lost Mary Pineapple Ice', 'vape', 5.99),
  p('Lost Mary Cherry Ice', 'vape', 5.99),
  p('Lost Mary Double Apple', 'vape', 5.99),
  p('Lost Mary Grape', 'vape', 5.99),
  p('Lost Mary Blue Razz Ice', 'vape', 5.99),
  p('Lost Mary Watermelon Ice', 'vape', 5.99),
  p('Lost Mary Triple Mango', 'vape', 5.99),
  p('Lost Mary Strawberry Ice', 'vape', 5.99),
  p('Lost Mary Juice Peach', 'vape', 5.99),
  p('Lost Mary Blueberry Sour Raspberry', 'vape', 5.99),
  p('Lost Mary Fizzy Cherry', 'vape', 5.99),
  p('Side Lemon Lime Vape', 'vape', 4.99),
  p('Side Watermelon Ice Vape', 'vape', 4.99),
];

// ── MEDICINES ─────────────────────────────────────────────────────────────────
const medicines = [
  p('Strepsils Original Lozenges', 'medicine', 3.99),
  p('Ibuprofen Pain Relief', 'medicine', 1.99),
  p('Gaviscon Double Action', 'medicine', 5.99),
  p('Nurofen', 'medicine', 3.49),
  p('Lemsip Cold and Flu', 'medicine', 3.99),
  p('Lemsip Blackcurrant', 'medicine', 3.99),
  p('Calpol Six Plus Paracetamol', 'medicine', 4.99),
  p('Nurofen Strawberry', 'medicine', 4.49),
  p('Calpol Sugar Free', 'medicine', 4.49),
  p('Benylin Non Drowsy 150ml', 'medicine', 5.99),
  p('Benylin Dry Tickle Cough Syrup', 'medicine', 5.99),
  p('Benylin Mussle Cough Max', 'medicine', 5.99),
  p("Benylin Infant's Cough Syrup", 'medicine', 5.99),
  p('Deep Heat Pain Relief', 'medicine', 4.99),
  p('Children Cough Relief', 'medicine', 3.99),
  p('Galpharm Diarrhoea Relief', 'medicine', 2.99),
  p('Aspirin Pain Relief', 'medicine', 1.99),
  p('Pho Plus Caffeine', 'medicine', 1.99),
  p('Galpharms Blocked Nose Relief', 'medicine', 2.99),
  p('Paracetamol Pain Relief', 'medicine', 1.49),
  p('Vapour Rub Clear Breathing', 'medicine', 3.99),
  p('Paracetamol 500mg Tablet', 'medicine', 1.49),
  p('Galpharm Allergy and Fever Relief', 'medicine', 2.99),
  p('Rennie Peppermint', 'medicine', 3.49),
  p('Durex Original 3pc', 'medicine', 3.99),
  p('Durex Pleasure Me 6pc', 'medicine', 5.99),
  p('Durex Thinfeel 6pc', 'medicine', 5.99),
  p('Durex Original Extra Safe 6pc', 'medicine', 5.99),
  p('Pregnancy Test 2 Pack', 'medicine', 4.99),
  p('Swift Pregnancy Test 1 Pack', 'medicine', 3.99),
  p('Vaseline 85g', 'medicine', 2.49),
  p('Vaseline Original 20g', 'medicine', 1.49),
  p('Vaseline Aloe 20g', 'medicine', 1.49),
];

// ── BATTERIES / LIGHTERS ──────────────────────────────────────────────────────
const batteries = [
  p('Duracell D2', 'household', 3.99),
  p('Duracell AAA', 'household', 3.99),
  p('Duracell AA', 'household', 3.99),
  p('Panasonic D2', 'household', 2.99),
  p('Panasonic AA', 'household', 2.99),
  p('Clipper Butane Gas 300ml', 'household', 3.49),
  p('Clipper Lighter Fluid 100ml', 'household', 2.49),
  p('ZigZag Utility Lighter', 'household', 1.49),
  p('Swan Lighter Flint', 'household', 0.99),
  p('Clear Adhesive Tape', 'household', 0.99),
];

// ── TOILETRIES (additional from Second Scan p26) ───────────────────────────────
const toiletries_extra = [
  p('Cotton Wool 120 Pieces', 'toiletries', 1.99),
  p('Kotex Night Time', 'toiletries', 2.99),
  p('Kotex Softness', 'toiletries', 2.99),
  p('Anti-Bac Wipes', 'toiletries', 1.49),
  p('Bathroom Anti-Bac Wipes', 'toiletries', 1.49),
  p('Green Shield Wipes', 'toiletries', 1.49),
];

// ── COMBINE ALL ───────────────────────────────────────────────────────────────
const allProducts = [
  ...confectionery,
  ...household_paper,
  ...beers,
  ...wines,
  ...spirits,
  ...tobacco,
  ...vape,
  ...medicines,
  ...batteries,
  ...toiletries_extra,
].filter(Boolean);

console.log(`Total new products to insert: ${allProducts.length}`);

// Insert in batches of 200
async function insertBatch(batch) {
  const { data, error } = await supabase.from('products').upsert(batch, { onConflict: 'id' });
  if (error) {
    console.error('Batch error:', error.message);
    return 0;
  }
  return batch.length;
}

async function main() {
  let total = 0;
  const batchSize = 200;
  for (let i = 0; i < allProducts.length; i += batchSize) {
    const batch = allProducts.slice(i, i + batchSize);
    const count = await insertBatch(batch);
    total += count;
    console.log(`Inserted batch ${Math.floor(i / batchSize) + 1}: ${count} products (running total: ${total})`);
  }
  console.log(`\nDone! Inserted ${total} new products.`);

  // Verify new total
  const { count } = await supabase.from('products').select('*', { count: 'exact', head: true });
  console.log(`Total products now in database: ${count}`);
}

main().catch(console.error);
