import { createClient } from '@supabase/supabase-js';
import { readFileSync } from 'fs';

const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_KEY);

const existingNames = new Set(JSON.parse(readFileSync('/tmp/existing_names.json', 'utf8')));

function exists(name) {
  return existingNames.has(name.toLowerCase().trim());
}

function p(name, category, price, description = '') {
  if (exists(name)) return null;
  return {
    id: 'inv-' + name.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/-+$/, '').substring(0, 60),
    name,
    description: description || name,
    category,
    price,
    member_price: null,
    image: "/placeholder-product.png",
    in_stock: 1
  };
}

// ── WINES ──────────────────────────────────────────────────────────────────────
const wines = [
  p('Blossom Hill Red Wine 70cl', 'alcohol', 6.49),
  p('Blossom Hill White Wine 750ml', 'alcohol', 6.49),
  p('Blossom Hill Dark Rose 750ml', 'alcohol', 6.49),
  p('Blossom Hill Pinot Grigio 750ml', 'alcohol', 6.49),
  p('Blossom Hill Sauvignon Blanc 750ml', 'alcohol', 6.49),
  p('Blossom Hill Red Wine 187ml', 'alcohol', 3.29),
  p('Blossom Hill White 187ml', 'alcohol', 3.29),
  p('Blossom Hill Pinot Grigio 187ml', 'alcohol', 3.29),
  p('Blossom Hill White 70cl', 'alcohol', 6.49),
  p('Echo Falls Merlot 750ml', 'alcohol', 6.49),
  p('Echo Falls Sparkling 750ml', 'alcohol', 6.99),
  p('Echo Falls Rose 750ml', 'alcohol', 6.49),
  p('Echo Falls White Zinfandel 750ml', 'alcohol', 6.49),
  p('Echo Falls Summer Berries 750ml', 'alcohol', 6.49),
  p('Echo Falls Raspberry and Cassis 750ml', 'alcohol', 6.49),
  p('Echo Falls Merlot 187ml', 'alcohol', 3.29),
  p('Echo Falls White 187ml', 'alcohol', 3.29),
  p("Jacob's Creek Merlot 750ml", 'alcohol', 7.49),
  p("Jacob's Creek Chardonnay 750ml", 'alcohol', 7.49),
  p('Barefoot Merlot 750ml', 'alcohol', 7.49),
  p('Barefoot Shiraz 750ml', 'alcohol', 7.49),
  p('Barefoot Cabernet Sauvignon 750ml', 'alcohol', 7.49),
  p('Barefoot Pinot Grigio 750ml', 'alcohol', 7.49),
  p('Barefoot Sauvignon Blanc 750ml', 'alcohol', 7.49),
  p('Barefoot Moscato 750ml', 'alcohol', 7.49),
  p('Barefoot White 187ml', 'alcohol', 3.49),
  p('Barefoot Jimmy Rose Calit 750ml', 'alcohol', 7.49),
  p('Campo Viejo Reserva 750ml', 'alcohol', 8.99),
  p('Campo Viejo Gran Reserva 750ml', 'alcohol', 10.99),
  p('Campo Viejo Tempranillo 750ml', 'alcohol', 7.99),
  p('Campo Viejo Garnacha 750ml', 'alcohol', 7.99),
  p('Campo Viejo Rose 750ml', 'alcohol', 7.99),
  p('Campo Viejo Boamistuna 750ml', 'alcohol', 7.99),
  p('Casillero del Diablo 750ml', 'alcohol', 8.49),
  p('Casillero del Diablo Malbec 750ml', 'alcohol', 8.49),
  p('Casillero del Diablo Rose 750ml', 'alcohol', 8.49),
  p('Casillero del Diablo Pinot Grigio 750ml', 'alcohol', 8.49),
  p('Gallo Merlot 70cl', 'alcohol', 6.49),
  p('Gallo Family Cabernet 750ml', 'alcohol', 7.49),
  p('Gallo Family Moscato 750ml', 'alcohol', 7.49),
  p('Gallo Family Pineapple and Passionfruit 750ml', 'alcohol', 7.49),
  p('Mateus Rose 750ml', 'alcohol', 6.99),
  p('Mateus Rose Original 187ml', 'alcohol', 3.49),
  p('Kumala Pinotage 750ml', 'alcohol', 6.99),
  p('Kumala Rose 750ml', 'alcohol', 6.99),
  p('Isla Negra Sauvignon Blanc 750ml', 'alcohol', 7.49),
  p('Isla Negra Malbec 750ml', 'alcohol', 7.49),
  p('Isla Negra Rose 750ml', 'alcohol', 7.49),
  p('Lindemans Chardonnay 75cl', 'alcohol', 6.99),
  p("Lindemans Sauvignon Blanc 750ml", 'alcohol', 6.99),
  p("Lindemans Merlot B40 750ml", 'alcohol', 6.99),
  p("Lindemans Rose Bin 750ml", 'alcohol', 6.99),
  p('Black Tower 750ml', 'alcohol', 6.49),
  p('Black Tower White 750ml', 'alcohol', 6.49),
  p('Black Tower Pinot Grigio 750ml', 'alcohol', 6.49),
  p('Black Tower Rose 750ml', 'alcohol', 6.49),
  p('I Heart Merlot 750ml', 'alcohol', 7.49),
  p('I Heart Chardonnay 750ml', 'alcohol', 7.49),
  p('I Heart Rose Fruity 70cl', 'alcohol', 7.49),
  p('Most Wanted Malbec 750ml', 'alcohol', 7.49),
  p('JP Chenet Colombard Chardonnay 750ml', 'alcohol', 6.49),
  p('Entwine Sauvignon 750ml', 'alcohol', 6.99),
  p('Entwine Shiraz Rose 750ml', 'alcohol', 6.99),
  p('Rosemount Estate Chardonnay 750ml', 'alcohol', 7.99),
  p('El Bombero 70cl', 'alcohol', 6.49),
  p('Bannrock Pink Moscato 750ml', 'alcohol', 6.99),
  p('Distant Vines Pinot Grigio 750ml', 'alcohol', 6.99),
  p('Oxford Landing Pinot 750ml', 'alcohol', 7.99),
  p('Quickly Bird Shiraz Red 750ml', 'alcohol', 6.99),
  p('Handys Merlot 750ml', 'alcohol', 7.49),
  p("Handy's VR Pinot Grigio 750ml", 'alcohol', 7.49),
  p("Handy's Rose 75cl", 'alcohol', 7.49),
  p('Meguigan Black Label Red 750ml', 'alcohol', 7.99),
  p('Fine and Foul Sauvignon Blanc 750ml', 'alcohol', 7.49),
  p('Alessandro Gallici Pinot Grigio 750ml', 'alcohol', 7.49),
  p('First Cape Chardonnay 750ml', 'alcohol', 6.99),
  p('Purato Pinot Grigio 750ml', 'alcohol', 7.49),
  p('Western Cape Chardonnay 750ml', 'alcohol', 6.99),
  p('Nozeco Sparkling Non Alcoholic 750ml', 'alcohol', 5.99),
  p('Bisberg Rose Non Alcohol 750ml', 'alcohol', 5.99),
  p('Red Label Apperitif 750ml', 'alcohol', 6.49),
  p('Central Merlot 750ml', 'alcohol', 6.49),
  p('Maria Fadista Rose 75cl', 'alcohol', 6.99),
  p('Brass Monkey 750ml', 'alcohol', 6.99),
  p('Lime Leaf Verde Jo 75cl', 'alcohol', 6.99),
  p('Pink Diamond White 75cl', 'alcohol', 6.99),
  p('Cascata Vinho Verde 750ml', 'alcohol', 6.49),
  p('Stones and Bones 750ml', 'alcohol', 7.49),
  p('Lunatic Fringe 75cl', 'alcohol', 6.99),
  p('Cablie de France 75cl', 'alcohol', 6.99),
  p('Raspberry Bush 75cl', 'alcohol', 6.99),
  p('Rex Mudi Shiraz 75cl', 'alcohol', 6.99),
  p('Opi Malbec 75cl', 'alcohol', 7.99),
  p('Bills and Sons Shiraz Durif 750ml', 'alcohol', 7.49),
  p('Patties Merlot 750ml', 'alcohol', 6.99),
  p('Queen Bee 750ml', 'alcohol', 6.99),
  p('Bees Knees Blanc 750ml', 'alcohol', 6.99),
  p('Cablie MMXXI 750ml', 'alcohol', 6.99),
  p('Vertiges Paradis 750ml', 'alcohol', 7.49),
  p('Cinzano Bianco 750ml', 'alcohol', 7.99),
  p('Inkosi Sauvignon Blanc 750ml', 'alcohol', 6.99),
];

// ── BEERS ──────────────────────────────────────────────────────────────────────
const beers = [
  p('Guinness Stout 330ml', 'alcohol', 1.79),
  p('Guinness Stout 325ml', 'alcohol', 1.79),
  p('Guinness Stout 440ml', 'alcohol', 2.19),
  p('Guinness Stout 500ml', 'alcohol', 2.49),
  p('Guinness Stout 600ml', 'alcohol', 2.79),
  p('Guinness West Indies Porter 500ml', 'alcohol', 2.69),
  p('Guinness Original 440ml', 'alcohol', 2.19),
  p('Dragon Stout 284ml', 'alcohol', 1.89),
  p('Heineken 330ml', 'alcohol', 1.69),
  p('Heineken 440ml', 'alcohol', 2.09),
  p('Heineken 500ml', 'alcohol', 2.49),
  p('Heineken 568ml', 'alcohol', 2.69),
  p('Heineken 650ml', 'alcohol', 2.99),
  p('Heineken 0.0% 330ml', 'alcohol', 1.69),
  p('Stella Artois 330ml', 'alcohol', 1.79),
  p('Stella Artois 440ml', 'alcohol', 2.19),
  p('Stella Artois 568ml', 'alcohol', 2.79),
  p('Stella Artois 660ml', 'alcohol', 2.99),
  p('Budweiser 275ml', 'alcohol', 1.49),
  p('Budweiser 300ml', 'alcohol', 1.69),
  p('Budweiser 440ml', 'alcohol', 2.09),
  p('Budweiser 568ml', 'alcohol', 2.59),
  p('Budweiser 660ml', 'alcohol', 2.79),
  p("Beck's 440ml", 'alcohol', 2.09),
  p("Beck's 660ml", 'alcohol', 2.69),
  p("Beck's 275ml Alcohol Free", 'alcohol', 1.49),
  p('Corona 330ml', 'alcohol', 1.99),
  p('Corona 440ml Can', 'alcohol', 2.09),
  p('Corona Extra 620ml', 'alcohol', 2.79),
  p('Peroni 330ml', 'alcohol', 2.09),
  p('Peroni 440ml Can', 'alcohol', 2.19),
  p('Peroni 620ml', 'alcohol', 2.79),
  p('Peroni Gluten Free 330ml', 'alcohol', 2.19),
  p('San Miguel 330ml', 'alcohol', 1.89),
  p('San Miguel 440ml', 'alcohol', 2.09),
  p('San Miguel 568ml', 'alcohol', 2.59),
  p('Desperados 330ml', 'alcohol', 2.09),
  p('Desperados 440ml', 'alcohol', 2.29),
  p('Desperados 650ml', 'alcohol', 2.99),
  p('Birra Moretti 440ml', 'alcohol', 2.29),
  p('Birra Moretti 660ml', 'alcohol', 2.79),
  p('Amstel 440ml', 'alcohol', 2.19),
  p('Carlsberg 440ml', 'alcohol', 2.09),
  p('Carlsberg 568ml', 'alcohol', 2.49),
  p('Fosters 440ml', 'alcohol', 1.99),
  p('Fosters 568ml', 'alcohol', 2.39),
  p('Holsten 440ml', 'alcohol', 2.09),
  p('Holsten 500ml', 'alcohol', 2.29),
  p('Holsten 568ml', 'alcohol', 2.49),
  p('1664 440ml Can', 'alcohol', 2.19),
  p('1664 568ml', 'alcohol', 2.59),
  p('Tyskie 500ml', 'alcohol', 2.09),
  p('Zubr 500ml', 'alcohol', 2.09),
  p('Lech 500ml', 'alcohol', 2.09),
  p('Zywiec 500ml', 'alcohol', 2.19),
  p('Debowa 500ml', 'alcohol', 2.19),
  p('Kanpackie 500ml', 'alcohol', 2.09),
  p('Efes Draft 500ml', 'alcohol', 2.29),
  p('Efes Draft Can 500ml', 'alcohol', 2.29),
  p('Modelo 355ml', 'alcohol', 1.99),
  p('Red Stripe 440ml', 'alcohol', 2.09),
  p('Red Stripe 568ml', 'alcohol', 2.49),
  p('Cobra 440ml', 'alcohol', 2.09),
  p('Cruz Campo 568ml', 'alcohol', 2.29),
  p('Black Union Black 500ml', 'alcohol', 2.19),
  p('Staropramen 440ml', 'alcohol', 2.09),
  p('Skol 500l', 'alcohol', 1.89),
  p('Erdinger Bottle', 'alcohol', 2.99),
  p('Perla 500ml', 'alcohol', 2.09),
  p("Thatchers Gold 500ml", 'alcohol', 2.49),
  p("Thatchers Katy 500ml", 'alcohol', 2.49),
];

// ── CIDERS ─────────────────────────────────────────────────────────────────────
const ciders = [
  p('Kopparberg Raspberry 500ml', 'alcohol', 2.29),
  p('Kopparberg Mixed Fruit 500ml', 'alcohol', 2.29),
  p('Kopparberg Strawberry Lime 500ml', 'alcohol', 2.29),
  p('Kopparberg Rum 70cl', 'alcohol', 9.99),
  p('Strongbow Original 330ml', 'alcohol', 1.79),
  p('Strongbow Original 440ml', 'alcohol', 2.09),
  p('Strongbow Original 568ml', 'alcohol', 2.39),
  p('Strongbow Original 940ml', 'alcohol', 3.49),
  p('Strongbow Dark Fruit Cider 568ml', 'alcohol', 2.49),
  p('Strongbow Strawberry Cider 330ml', 'alcohol', 1.99),
  p('Strongbow Cloudy Apple 440ml', 'alcohol', 2.19),
  p('Strongbow Rose Cider 440ml', 'alcohol', 2.19),
  p('Strongbow Original Cider 2 Litre', 'alcohol', 4.99),
  p('Magners 500ml', 'alcohol', 2.29),
  p('Chabbies Ginger Beer 500ml', 'alcohol', 2.49),
  p('Carib Lager 330ml', 'alcohol', 1.99),
  p('K-Cider 500ml', 'alcohol', 1.99),
  p('Crumpton Oaks 568ml', 'alcohol', 1.99),
  p('Crumpton Oak Cider Apple 2.5 Litre', 'alcohol', 5.99),
  p('Omega White Cider 500ml Can', 'alcohol', 1.79),
  p('Omega White Cider 1 Litre', 'alcohol', 2.99),
  p('Omega White Cider 2.5 Litre', 'alcohol', 5.49),
  p('Knight Cider 500ml', 'alcohol', 1.79),
  p('White Storm 500ml', 'alcohol', 1.79),
  p('White Storm White Cider 2.5 Litre', 'alcohol', 5.49),
  p('Lambrini Original 750ml', 'alcohol', 3.49),
  p('Lambrini Original 1.25 Litre', 'alcohol', 4.99),
  p('Frosty Jakes 500ml', 'alcohol', 1.79),
  p('Black Storm 500ml', 'alcohol', 1.79),
  p('Inchs 440ml', 'alcohol', 1.99),
  p('VK Strawberry and Lime 70cl', 'alcohol', 3.49),
  p('VK Orange and Passionfruit 70cl', 'alcohol', 3.49),
  p('WKD Blue Vodka 275ml', 'alcohol', 1.89),
  p('WKD Iron Brew Vodka 700ml', 'alcohol', 8.99),
  p('Smirnoff Ice Original 250ml', 'alcohol', 1.89),
  p('Smirnoff Ice Original 275ml', 'alcohol', 1.99),
  p('XF Dark Fruit', 'alcohol', 1.79),
  p('XF Strawberry', 'alcohol', 1.79),
];

// ── SPIRITS ────────────────────────────────────────────────────────────────────
const spirits = [
  p('Absolut Original Vodka 70cl', 'alcohol', 18.99),
  p('Absolut Mango 70cl', 'alcohol', 18.99),
  p('Absolut Passionfruit 70cl', 'alcohol', 18.99),
  p('Absolut Vanilla 70cl', 'alcohol', 18.99),
  p('Absolut Mandarin 70cl', 'alcohol', 18.99),
  p('Absolut Raspberry 70cl', 'alcohol', 18.99),
  p('Absolut Wild Berry 70cl', 'alcohol', 18.99),
  p('Absolut Pears 70cl', 'alcohol', 18.99),
  p('Absolut Watermelon 70cl', 'alcohol', 18.99),
  p('Absolut Citron 70cl', 'alcohol', 18.99),
  p('Absolut Vodka 35cl', 'alcohol', 11.99),
  p('Absolut Vodka 20cl', 'alcohol', 7.99),
  p('Absolut Vodka 5cl', 'alcohol', 2.49),
  p('Absolut Raspberry Lemonade 250ml', 'alcohol', 2.49),
  p('Absolut Cocktails 250ml', 'alcohol', 2.99),
  p('Absolut Cocktails Espresso Martini 250ml', 'alcohol', 2.99),
  p('Ciroc Original 70cl', 'alcohol', 32.99),
  p('Ciroc Apple 70cl', 'alcohol', 32.99),
  p('Ciroc Pineapple 70cl', 'alcohol', 32.99),
  p('Ciroc Limonato 70cl', 'alcohol', 32.99),
  p('Ciroc Mango 70cl', 'alcohol', 32.99),
  p('Ciroc Coconut 70cl', 'alcohol', 32.99),
  p('Ciroc Pomegranate 70cl', 'alcohol', 32.99),
  p('Ciroc Mango French Vodka 70cl', 'alcohol', 32.99),
  p('Ciroc Summer Citrus 25cl', 'alcohol', 14.99),
  p('Smirnoff Vodka 70cl', 'alcohol', 16.99),
  p('Smirnoff Vodka 35cl', 'alcohol', 9.99),
  p('Smirnoff Vodka 20cl', 'alcohol', 6.99),
  p('Smirnoff Vodka 5cl', 'alcohol', 1.99),
  p('Smirnoff Vodka 1 Litre', 'alcohol', 22.99),
  p('Smirnoff Vanilla 70cl', 'alcohol', 17.99),
  p('Smirnoff Spicy Tamarind 70cl', 'alcohol', 17.99),
  p('Smirnoff Peach 70cl', 'alcohol', 17.99),
  p('Smirnoff Tropical 70cl', 'alcohol', 17.99),
  p('Smirnoff Original 70cl', 'alcohol', 16.99),
  p('Smirnoff Vodka Kola 250ml', 'alcohol', 1.99),
  p("Glen's Vodka 70cl", 'alcohol', 13.99),
  p("Glen's Vodka 35cl", 'alcohol', 7.99),
  p("Glen's Vodka 1 Litre", 'alcohol', 18.99),
  p("Glen's Vodka 20cl", 'alcohol', 5.99),
  p("Glen's Vodka 5cl", 'alcohol', 1.79),
  p('Vodka Prince Consort 70cl', 'alcohol', 12.99),
  p('Prince Consort Vodka 20cl', 'alcohol', 5.99),
  p('Finlandia Vodka 70cl', 'alcohol', 16.99),
  p('Russian Standard 70cl', 'alcohol', 17.99),
  p('Russian Standard 1 Litre', 'alcohol', 23.99),
  p('Zubrowka Vodka 70cl', 'alcohol', 17.99),
  p('Zubrowka Vodka 35cl', 'alcohol', 9.99),
  p('Zubrowka Vodka 20cl', 'alcohol', 6.99),
  p('Wray and Nephew 70cl', 'alcohol', 19.99),
  p('Wray and Nephew 35cl', 'alcohol', 11.99),
  p('Wray and Nephew 20cl', 'alcohol', 7.99),
  p('Wray and Nephew 5cl', 'alcohol', 2.29),
  p('AU Vodka Blue Raspberry 35cl', 'alcohol', 16.99),
  p('AU Vodka Bubble Gum 70cl', 'alcohol', 24.99),
  p('AU Vodka Grape 5cl', 'alcohol', 2.99),
  p('AU Strawberry Vodka 5cl', 'alcohol', 2.99),
  p('Captain Morgan Dark Rum 250ml', 'alcohol', 3.49),
  p('Captain Morgan Dark Rum 70cl', 'alcohol', 17.99),
  p('Captain Morgan Dark Rum 35cl', 'alcohol', 10.99),
  p('Captain Morgan Dark Rum 20cl', 'alcohol', 6.99),
  p('Captain Morgan Dark Rum 5cl', 'alcohol', 1.99),
  p('Captain Morgan White Rum 70cl', 'alcohol', 17.99),
  p('Captain Morgan Spiced Gold 70cl', 'alcohol', 17.99),
  p('Captain Morgan Spiced Gold 35cl', 'alcohol', 10.99),
  p('Captain Morgan Spiced Gold 20cl', 'alcohol', 6.99),
  p('Captain Morgan Spiced Gold 1 Litre', 'alcohol', 23.99),
  p('Captain Morgan Black Spiced 70cl', 'alcohol', 17.99),
  p('Captain Morgan Dark Rum 1 Litre', 'alcohol', 23.99),
  p('Bacardi Rum 70cl', 'alcohol', 16.99),
  p('Bacardi Rum 35cl', 'alcohol', 9.99),
  p('Bacardi Rum 20cl', 'alcohol', 6.49),
  p('Bacardi Rum 5cl', 'alcohol', 1.89),
  p('Bacardi Rum 1 Litre', 'alcohol', 22.99),
  p('Bacardi Mango 250ml', 'alcohol', 2.49),
  p('Malibu 250ml', 'alcohol', 2.49),
  p('Malibu Cola 250ml', 'alcohol', 2.49),
  p('Malibu 70cl', 'alcohol', 14.99),
  p('Malibu 35cl', 'alcohol', 8.99),
  p('Malibu 20cl', 'alcohol', 5.99),
  p('Malibu 5cl', 'alcohol', 1.79),
  p('Jack Daniels Original 70cl', 'alcohol', 22.99),
  p('Jack Daniels Original 35cl', 'alcohol', 13.99),
  p('Jack Daniels Original 20cl', 'alcohol', 8.99),
  p('Jack Daniels Original 10cl', 'alcohol', 5.99),
  p('Jack Daniels Original 5cl', 'alcohol', 2.49),
  p('Jack Daniels Original 1 Litre', 'alcohol', 29.99),
  p('Jack Daniels Apple 70cl', 'alcohol', 21.99),
  p('Jack Daniels Apple 35cl', 'alcohol', 13.49),
  p('Jack Daniels Cinnamon Spice 70cl', 'alcohol', 21.99),
  p('Jack Daniels Honey 35cl', 'alcohol', 13.49),
  p('Jack Daniels Honey 5cl', 'alcohol', 2.49),
  p('Jack Daniels 330ml', 'alcohol', 2.49),
  p('Jim Beam Whiskey 70cl', 'alcohol', 18.99),
  p('Jim Beam Whiskey 20cl', 'alcohol', 7.49),
  p('Jameson Whiskey 70cl', 'alcohol', 22.99),
  p('Jameson Whiskey 35cl', 'alcohol', 13.99),
  p('Jameson Whiskey 20cl', 'alcohol', 7.99),
  p('Jameson Whiskey 5cl', 'alcohol', 2.49),
  p("Grant's Whisky 70cl", 'alcohol', 16.99),
  p("Grant's Whisky 35cl", 'alcohol', 9.99),
  p("Grant's Whisky 20cl", 'alcohol', 6.49),
  p('Bells Whisky 70cl', 'alcohol', 16.99),
  p('Bells Whisky 35cl', 'alcohol', 9.49),
  p('Bells Whisky 20cl', 'alcohol', 5.99),
  p('Bells Whisky 5cl', 'alcohol', 1.79),
  p('Bells Whisky 1 Litre', 'alcohol', 22.99),
  p('The Famous Grouse Whisky 70cl', 'alcohol', 18.99),
  p('The Famous Grouse Whisky 35cl', 'alcohol', 10.99),
  p('The Famous Grouse Whisky 5cl', 'alcohol', 2.19),
  p('The Famous Grouse Whisky 1 Litre', 'alcohol', 24.99),
  p('High Commissioner Whisky 70cl', 'alcohol', 14.99),
  p('High Commissioner Whisky 35cl', 'alcohol', 8.99),
  p('High Commissioner Whisky 20cl', 'alcohol', 5.99),
  p('High Commissioner Whisky 5cl', 'alcohol', 1.79),
  p('Chivas Regal 70cl', 'alcohol', 29.99),
  p('Chivas Regal 35cl', 'alcohol', 16.99),
  p('Chivas Regal 20cl', 'alcohol', 9.99),
  p('Haig Club 70cl', 'alcohol', 29.99),
  p('Glenmorangie 70cl', 'alcohol', 34.99),
  p('Glenfiddich 35cl', 'alcohol', 19.99),
  p('Jura Whisky 70cl', 'alcohol', 28.99),
  p('Woodford Reserve Whisky 70cl', 'alcohol', 34.99),
  p('White Mascay Whisky 70cl', 'alcohol', 12.99),
  p('White Mascay Whisky 20cl', 'alcohol', 5.99),
  p('Claymore Whisky 20cl', 'alcohol', 5.49),
  p('Claymore Whisky 35cl', 'alcohol', 8.99),
  p("Gordon's Dry Gin 70cl", 'alcohol', 17.99),
  p("Gordon's Dry Gin 35cl", 'alcohol', 10.99),
  p("Gordon's Dry Gin 20cl", 'alcohol', 6.99),
  p("Gordon's Dry Gin 5cl", 'alcohol', 1.99),
  p("Gordon's Dry Gin 1 Litre", 'alcohol', 23.99),
  p("Gordon's Pink Gin 70cl", 'alcohol', 18.99),
  p("Gordon's Pink Gin 35cl", 'alcohol', 10.99),
  p("Gordon's Gin and Tonic 250ml", 'alcohol', 2.49),
  p('London Dry Gin 70cl', 'alcohol', 14.99),
  p('Bombay Sapphire Gin 70cl', 'alcohol', 22.99),
  p('Southern Comfort 70cl', 'alcohol', 17.99),
  p('Southern Comfort 35cl', 'alcohol', 10.49),
  p('Southern Comfort 20cl', 'alcohol', 6.99),
  p('Hennessy Cognac 70cl', 'alcohol', 29.99),
  p('Hennessy Cognac 35cl', 'alcohol', 17.99),
  p('Hennessy Cognac 20cl', 'alcohol', 9.99),
  p('Hennessy Cognac 5cl', 'alcohol', 2.99),
  p('Courvoisier Cognac 70cl', 'alcohol', 24.99),
  p('Courvoisier Cognac 35cl', 'alcohol', 14.99),
  p('Courvoisier Cognac 20cl', 'alcohol', 8.99),
  p('Courvoisier Cognac 5cl', 'alcohol', 2.49),
  p('Remy Martin 70cl', 'alcohol', 34.99),
  p('Remy Martin Cognac 1738 70cl', 'alcohol', 44.99),
  p('Martell Cognac 70cl', 'alcohol', 29.99),
  p('Martell Cognac 35cl', 'alcohol', 17.99),
  p('Martell Cognac 20cl', 'alcohol', 9.99),
  p('Martell Cognac 5cl', 'alcohol', 2.49),
  p('EJ Brandy 70cl', 'alcohol', 12.99),
  p('EJ Brandy 35cl', 'alcohol', 7.99),
  p('EJ Brandy 20cl', 'alcohol', 5.49),
  p('Prince Consort Brandy 35cl', 'alcohol', 7.99),
  p('Prince Consort Brandy 20cl', 'alcohol', 5.49),
  p('Jules Claizon Brandy 70cl', 'alcohol', 13.99),
  p('Jules Claizon Brandy 35cl', 'alcohol', 8.49),
  p('Jules Claizon Brandy 20cl', 'alcohol', 5.99),
  p('Jules Claizon Brandy 5cl', 'alcohol', 1.99),
  p('Three Barrels Brandy 70cl', 'alcohol', 14.99),
  p('Three Barrels Brandy 35cl', 'alcohol', 8.99),
  p('Bols Apricot Brandy 500ml', 'alcohol', 12.99),
  p('Red Label Whisky 70cl', 'alcohol', 22.99),
  p('Black Label Whisky 70cl', 'alcohol', 34.99),
  p('Black Label Whisky 5cl', 'alcohol', 2.99),
  p('Jagermeister 35cl', 'alcohol', 12.99),
  p('Jagermeister 50cl', 'alcohol', 16.99),
  p('Jagermeister 70cl', 'alcohol', 19.99),
  p('Baileys Original 70cl', 'alcohol', 14.99),
  p('Baileys Original 35cl', 'alcohol', 8.99),
  p('Baileys Original 5cl', 'alcohol', 1.79),
  p('Baileys Orange 50cl', 'alcohol', 13.99),
  p('Tia Maria Coffee Liqueur 35cl', 'alcohol', 9.99),
  p('Martini Asti 750cl', 'alcohol', 9.99),
  p('Martini Rosso 70cl', 'alcohol', 9.99),
  p('Martini Bianco 70cl', 'alcohol', 9.99),
  p('Moet Chandon 750ml', 'alcohol', 34.99),
  p('Paul Longier 750ml', 'alcohol', 12.99),
  p('Prosecco Rossi 750ml', 'alcohol', 8.99),
  p('Bollinger Champagne 750ml', 'alcohol', 44.99),
  p('GP Chenet 750cl', 'alcohol', 7.99),
  p('Fili Prosecco 70cl', 'alcohol', 8.99),
  p('Bottega Nella 70cl', 'alcohol', 11.99),
  p('Faustino Wine 75cl', 'alcohol', 8.99),
  p('Sandeman Fine Wine 70cl', 'alcohol', 14.99),
  p('Taylors Port 70cl', 'alcohol', 12.99),
  p('Sierra Tropical Chilli 70cl', 'alcohol', 16.99),
  p('Sierra Tequila 70cl', 'alcohol', 16.99),
  p('Alize Gold Passion 70cl', 'alcohol', 19.99),
  p('Alize Red Passion 70cl', 'alcohol', 19.99),
  p('Campari 70cl', 'alcohol', 19.99),
  p('MD 20/20 Golden Pineapple 75cl', 'alcohol', 3.99),
  p('MD 20/20 Dragon Fruit 75cl', 'alcohol', 3.99),
  p('MD 20/20 Kiwi 75cl', 'alcohol', 3.99),
  p('Buzz Balz Passionfruit Martini 20cl', 'alcohol', 3.49),
  p('Buzz Balz Strawberry 20cl', 'alcohol', 3.49),
  p('Buzz Balz Espresso Martini 20cl', 'alcohol', 3.49),
  p('Buzz Balz Tequila Rita 20cl', 'alcohol', 3.49),
  p('Buzz Balz Lotta Colada 20cl', 'alcohol', 3.49),
  p('Buzz Balz Chili Mango 20cl', 'alcohol', 3.49),
  p('Magnum Tonic Wine 20cl', 'alcohol', 2.99),
  p('Rudder Boy Tonic Wine 20cl', 'alcohol', 2.99),
  p('Red Label Tonic Wine 20cl', 'alcohol', 2.99),
  p('Koppo Tonic Wine 20cl', 'alcohol', 2.99),
  p('Cherry B Tonic Wine 20cl', 'alcohol', 2.99),
  p('WHA GWAV Rum Cream 20cl', 'alcohol', 3.49),
  p('Moliby Red 20cl', 'alcohol', 3.49),
  p('Moliby Original 20cl', 'alcohol', 3.49),
];

// ── CIGARETTES ─────────────────────────────────────────────────────────────────
const cigarettes = [
  p('Embassy Filter K/S', 'tobacco', 12.49),
  p('Embassy Gold K/S', 'tobacco', 12.49),
  p('Embassy Gold S/K', 'tobacco', 12.49),
  p('Embassy Signature S/K', 'tobacco', 12.49),
  p('Embassy Signature K/S', 'tobacco', 12.49),
  p('Vogue Cigarettes', 'tobacco', 12.99),
  p('Marlboro Gold', 'tobacco', 13.49),
  p('Marlboro Touch', 'tobacco', 13.49),
  p('Marlboro Red', 'tobacco', 13.49),
  p('Rothmans Silver', 'tobacco', 11.99),
  p('Rothmans Blue', 'tobacco', 11.99),
  p('Rothmans Silver K/S', 'tobacco', 11.99),
  p('Rothmans Blue S/K', 'tobacco', 11.99),
  p('Silkcut Purple', 'tobacco', 12.99),
  p('Silkcut Silver', 'tobacco', 12.99),
  p('Players Red S/K', 'tobacco', 11.99),
  p('Players Bright', 'tobacco', 11.99),
  p('Players Bright S/K', 'tobacco', 11.99),
  p('Carlton Original', 'tobacco', 11.49),
  p('Carlton Original S/K', 'tobacco', 11.49),
  p('YMB Blue', 'tobacco', 11.49),
  p('YMB Silver', 'tobacco', 11.49),
  p('American Spirit Yellow', 'tobacco', 14.99),
  p('Pall Mall Red S/K', 'tobacco', 11.49),
  p('Pall Mall Blue S/K', 'tobacco', 11.49),
  p('Pall Mall Blue K/S', 'tobacco', 11.49),
  p('Pall Mall Red K/S', 'tobacco', 11.49),
  p('Richmond Original S/K', 'tobacco', 11.49),
  p('Richmond Green S/K', 'tobacco', 11.49),
  p('Richmond Original K/S', 'tobacco', 11.49),
  p('Richmond Compact', 'tobacco', 11.49),
  p('Sovereign Blue S/K', 'tobacco', 10.99),
  p('Sovereign Blue K/S', 'tobacco', 10.99),
  p('Sovereign Sky Blue', 'tobacco', 10.99),
  p('Sovereign Black', 'tobacco', 10.99),
  p('Lucky Strike S/K', 'tobacco', 11.99),
  p('Lucky Strike', 'tobacco', 11.99),
  p('Benson Gold', 'tobacco', 12.49),
  p('Benson Silver K/S', 'tobacco', 12.49),
  p('Benson Dual', 'tobacco', 12.49),
  p('Benson Blue Dual', 'tobacco', 12.49),
  p('Benson Sky Blue', 'tobacco', 12.49),
  p('Benson Blue S/K', 'tobacco', 12.49),
  p('Benson Sky Blue S/K', 'tobacco', 12.49),
  p('Benson Green S/K', 'tobacco', 12.49),
  p('Sterling K/S', 'tobacco', 10.99),
  p('Mayfair Silver', 'tobacco', 10.99),
  p('Mayfair Gold', 'tobacco', 10.99),
  p('Mayfair Blue Sky K/S', 'tobacco', 10.99),
  p('Mayfair Sky Blue S/K', 'tobacco', 10.99),
  p('Mayfair Blue', 'tobacco', 10.99),
  p('Chesterfield Blue', 'tobacco', 11.49),
  p('Chesterfield Red S/K', 'tobacco', 11.49),
  p('Sterling Double Capsules', 'tobacco', 10.99),
  p('Winston Blue', 'tobacco', 11.99),
];

// ── ROLLING TOBACCO / POUCHES ──────────────────────────────────────────────────
const rollingTobacco = [
  p('Pall Mall 30g', 'tobacco', 12.49),
  p('American Spirit Blue 30g', 'tobacco', 14.99),
  p('Mayfair 30g', 'tobacco', 11.99),
  p('Golden Virginia 30g', 'tobacco', 13.49),
  p('Benson Blue 30g', 'tobacco', 12.49),
  p('Riverston 30g', 'tobacco', 11.49),
  p('Amber Leaf 30g', 'tobacco', 13.49),
  p('Old Holborn 30g', 'tobacco', 13.49),
  p('Golden Virginia Yellow 30g', 'tobacco', 13.49),
  p('Sterling 50g', 'tobacco', 17.49),
  p('Gold Leaf 50g', 'tobacco', 14.49),
  p('Sterling 3 in 1 30g', 'tobacco', 11.99),
  p('Marlboro Tobacco 30g', 'tobacco', 13.49),
  p('Gold Leaf 30g', 'tobacco', 13.49),
  p('Benson Silver 30g', 'tobacco', 12.49),
  p('Pall Mall 30g Rolling', 'tobacco', 12.49),
  p('Amber Leaf Original 30g', 'tobacco', 13.49),
  p('Amber Leaf 3 in 1 30g', 'tobacco', 13.49),
  p('Sterling 50g Tobacco', 'tobacco', 17.49),
  p('Amber Leaf 50g', 'tobacco', 18.99),
];

// ── HEETS / TEREA ──────────────────────────────────────────────────────────────
const heets = [
  p('HEETS Green', 'tobacco', 6.49),
  p('HEETS Selection', 'tobacco', 6.49),
  p('HEETS Mauve', 'tobacco', 6.49),
  p('HEETS Yellow', 'tobacco', 6.49),
  p('HEETS Russet', 'tobacco', 6.49),
  p('HEETS Teak', 'tobacco', 6.49),
  p('HEETS Siena', 'tobacco', 6.49),
  p('Terea Ambela', 'tobacco', 6.99),
  p('Terea Mauve', 'tobacco', 6.99),
  p('Terea Yellow', 'tobacco', 6.99),
  p('Terea Blue', 'tobacco', 6.99),
  p('Terea Pearl', 'tobacco', 6.99),
  p('Terea Turquoise', 'tobacco', 6.99),
  p('Terea Russet', 'tobacco', 6.99),
];

// ── VAPES ──────────────────────────────────────────────────────────────────────
const vapes = [
  p('Lost Mary Pineapple Ice', 'tobacco', 5.99),
  p('Lost Mary Cherry Ice', 'tobacco', 5.99),
  p('Lost Mary Double Apple', 'tobacco', 5.99),
  p('Lost Mary Grape', 'tobacco', 5.99),
  p('Lost Mary Blue Razz Ice', 'tobacco', 5.99),
  p('Lost Mary Watermelon Ice', 'tobacco', 5.99),
  p('Lost Mary Triple Mango', 'tobacco', 5.99),
  p('Lost Mary Strawberry Ice', 'tobacco', 5.99),
  p('Lost Mary Juice Peach', 'tobacco', 5.99),
  p('Lost Mary Blueberry Sour Raspberry', 'tobacco', 5.99),
  p('Lost Mary Fizzy Cherry', 'tobacco', 5.99),
  p('Side Lemon Lime', 'tobacco', 4.99),
  p('Side Watermelon Ice', 'tobacco', 4.99),
];

// ── ROLLING ACCESSORIES ────────────────────────────────────────────────────────
const rollingAccessories = [
  p('Rizla Red', 'tobacco', 0.99),
  p('Rizla Rich Liquorice', 'tobacco', 0.99),
  p('Rizla Blue K/S', 'tobacco', 0.99),
  p('Rizla Blue', 'tobacco', 0.99),
  p('Rizla Green K/S', 'tobacco', 0.99),
  p('Rizla Green', 'tobacco', 0.99),
  p('Rizla Silver K/S', 'tobacco', 0.99),
  p('Rizla Silver', 'tobacco', 0.99),
  p('Rizla Elements', 'tobacco', 0.99),
  p('Raw Tips', 'tobacco', 0.99),
  p('Raw Paper', 'tobacco', 0.99),
  p('Raw Slim', 'tobacco', 0.99),
  p('Raw with Tips', 'tobacco', 0.99),
  p('Raw K/S', 'tobacco', 0.99),
  p('Raw Black', 'tobacco', 0.99),
  p('Raw Black Tips', 'tobacco', 0.99),
  p('Raw Black No Tips', 'tobacco', 0.99),
  p('Swan Extra Slim', 'tobacco', 0.99),
  p('Swan Menthol Extra Slim', 'tobacco', 0.99),
  p('Jumbo Cone', 'tobacco', 1.49),
  p('Jumbo Brown Cone', 'tobacco', 1.49),
  p('OCB Cone Black', 'tobacco', 1.49),
  p('OCB Cone Brown', 'tobacco', 1.49),
  p('Velo Watermelon Ice', 'tobacco', 4.99),
  p('Velo Freezing Peppermint', 'tobacco', 4.99),
  p('Velo Purple Grape', 'tobacco', 4.99),
  p('Nordic Spirit Sweet Mint', 'tobacco', 4.99),
  p('Nordic Spirit Spearmint', 'tobacco', 4.99),
  p('Nordic Spirit Mint', 'tobacco', 4.99),
  p('Nordic Spirit', 'tobacco', 4.99),
  p('Blunt Wrap Red', 'tobacco', 1.49),
  p('Blunt Wrap Pink', 'tobacco', 1.49),
  p('Blunt Wrap Blue', 'tobacco', 1.49),
  p('Blunt Wrap Yellow', 'tobacco', 1.49),
  p('Extra Slim Menthol Filter', 'tobacco', 1.49),
  p('Ultra Slim Filter', 'tobacco', 1.49),
  p('Crystal Polar Blast Filter', 'tobacco', 1.49),
  p('Clipper Butane Gas 300ml', 'tobacco', 2.49),
  p('Clipper Lighter Fluid 100ml', 'tobacco', 2.49),
  p('Zig Zag Utility Lighter', 'tobacco', 1.49),
  p('Swan Lighter Flint', 'tobacco', 0.49),
];

// ── NICOTINE POUCHES ───────────────────────────────────────────────────────────
const nicotinePouches = [
  p('OSB Black', 'tobacco', 5.49),
  p('OSB Brown', 'tobacco', 5.49),
  p('OSB Blue', 'tobacco', 5.49),
];

// ── BATTERIES / MISC ──────────────────────────────────────────────────────────
const batteries = [
  p('Duracell D2', 'misc', 4.99),
  p('Duracell AAA', 'misc', 2.99),
  p('Duracell AA', 'misc', 2.99),
  p('Panasonic D2', 'misc', 3.99),
  p('Panasonic AA', 'misc', 2.49),
  p('Vaseline 85g', 'toiletries', 2.49),
  p('Vaseline Original 20g', 'toiletries', 1.29),
  p('Vaseline Aloe 20g', 'toiletries', 1.29),
  p('Clear Adhesive Tape', 'misc', 0.99),
  p('Pregnancy Test 2 Pack', 'medicine', 4.99),
  p('Swift Pregnancy Test 1 Pack', 'medicine', 3.99),
];

// ── TISSUES / PAPER PRODUCTS ──────────────────────────────────────────────────
const tissues = [
  p('Freedom Inspiration 9 Rolls', 'household', 3.49),
  p('Nicky Elite 9 Rolls', 'household', 3.49),
  p('Nicky Soft Touch 9 Rolls', 'household', 3.49),
  p('Andrex 9 Rolls', 'household', 3.99),
  p('Inspiration Aloe Vera 9 Rolls', 'household', 3.49),
  p('Nicky Elite Enriched with Lotion 9 Rolls', 'household', 3.79),
  p('Regina Gentle Soft 4 Rolls', 'household', 2.99),
  p('Blossom Soft 8 Rolls', 'household', 2.49),
  p('Jacks Soft 4 Rolls', 'household', 1.99),
  p('Inspiration Double Soft Aloe Vera 4 Rolls', 'household', 2.49),
  p('Inspiration Soft White 4 Rolls', 'household', 2.29),
  p('Bloom 4 Rolls', 'household', 1.99),
  p('Andrex 2 Rolls', 'household', 1.49),
  p('Andrex 6 Rolls', 'household', 2.99),
  p('Nicky The Snowman 4 Rolls', 'household', 2.49),
  p('Cushella 4 Rolls', 'household', 1.99),
  p('Hush 4 Rolls', 'household', 1.99),
  p('Blossom Soft 24 Rolls', 'household', 7.49),
  p("Chef's Essential 24 Rolls", 'household', 5.99),
  p('Nicky Jumbo Large Roll', 'household', 1.99),
  p('Plenty Original Large Roll', 'household', 1.79),
  p('Use It 4 Kitchen Towel Roll', 'household', 1.99),
  p('Nicky Lemon Large Kitchen Towel', 'household', 1.99),
  p('Splash Kitchen Roll 2 Pack', 'household', 1.49),
  p('Nicky Household 2 Pack', 'household', 1.29),
  p('Freedom 4 Rolls', 'household', 1.99),
  p('Regina Household Towel 1 Roll', 'household', 1.29),
  p('Jacks Multi Purpose 2 Roll', 'household', 1.49),
  p('Rhino Blue 1 Roll', 'household', 1.49),
  p('Inspiration Lemon Fresh 9 Roll', 'household', 3.49),
  p('Inspiration Aloe Vera 9 Rolls Regular', 'household', 3.29),
  p('Inspiration Shea Butter 9 Rolls', 'household', 3.49),
];

// ── MEDICINE ──────────────────────────────────────────────────────────────────
const medicine = [
  p('Strepsils Original Lozenges', 'medicine', 3.49),
  p('Ibuprofen Pain Relief', 'medicine', 1.99),
  p('Gaviscon Double Action', 'medicine', 4.99),
  p('Nurofen', 'medicine', 3.49),
  p('Lemsip Cold and Flu', 'medicine', 3.99),
  p('Calpol Six Plus Paracetamol', 'medicine', 4.49),
  p('Lemsip Blackcurrant', 'medicine', 3.99),
  p('Nurofen Strawberry', 'medicine', 4.49),
  p('Calpol Sugar Free', 'medicine', 4.49),
  p('Benylin Non Drowsy 150ml', 'medicine', 5.49),
  p('Benylin Day and Night Cough Syrup', 'medicine', 5.99),
  p('Benylin Mussile Cough Max', 'medicine', 5.99),
  p("Benylin Infant's Cough Syrup", 'medicine', 4.99),
  p('Deep Heat Pain Relief', 'medicine', 3.99),
  p('Children Cough Relief', 'medicine', 3.49),
  p('Galpharm Diarrhoea Relief', 'medicine', 2.99),
  p('Aspirin Pain Relief', 'medicine', 1.99),
  p('Pho Plus Caffeine', 'medicine', 2.49),
  p('Galpharm Blocked Nose Relief', 'medicine', 2.99),
  p('Paracetamol Pain Relief', 'medicine', 0.99),
  p('Vapour Rub Clear Breathing', 'medicine', 2.99),
  p('Paracetamol 500mg Tablet', 'medicine', 0.99),
  p('Galpharm Allergy and Fever Relief', 'medicine', 2.99),
  p('Durex Original 3 Pack', 'medicine', 3.99),
  p('Durex 6 Pack Pleasure Me', 'medicine', 6.99),
  p('Durex 6 Pack Thin Feel', 'medicine', 6.99),
  p('Durex 6 Pack Original Extra Safe', 'medicine', 6.99),
  p('Rennie Peppermint', 'medicine', 2.49),
];

// ── GROCERIES / DRY GOODS ──────────────────────────────────────────────────────
const groceries = [
  p('Batchelors Mushy Peas', 'grocery', 0.89),
  p('Batchelors Cup a Soup Chicken Noodle', 'grocery', 1.29),
  p('Batchelors Cup a Soup Tomato', 'grocery', 1.29),
  p('Knorr Chicken Stock Cubes', 'grocery', 1.49),
  p('Knorr Beef Stock Cubes', 'grocery', 1.49),
  p('Knorr Vegetable Stock Cubes', 'grocery', 1.49),
  p('Tilda Basmati Rice 1kg', 'grocery', 3.49),
  p('Tilda Basmati Rice 2kg', 'grocery', 6.49),
  p("Ben's Original Long Grain Rice", 'grocery', 2.49),
  p('Old El Paso Taco Kit', 'grocery', 2.99),
  p('Old El Paso Tortilla Wraps', 'grocery', 2.49),
  p('KTC Sunflower Oil 1 Litre', 'grocery', 1.99),
  p('KTC Vegetable Oil 1 Litre', 'grocery', 1.99),
  p('Heinz Baked Beans', 'grocery', 0.99),
  p('Heinz Tomato Ketchup', 'grocery', 2.49),
  p('Heinz Tomato Soup', 'grocery', 1.29),
  p('Heinz Cream of Tomato Soup', 'grocery', 1.29),
  p('Pot Noodle Chicken and Mushroom', 'grocery', 0.99),
  p('Pot Noodle Beef and Tomato', 'grocery', 0.99),
  p('Pot Noodle Bombay Badboy', 'grocery', 0.99),
  p('Super Noodles Chicken', 'grocery', 0.79),
  p('Super Noodles Bacon', 'grocery', 0.79),
  p('Maggi 2 Minute Noodles', 'grocery', 0.59),
  p('Smash Instant Mash', 'grocery', 0.99),
  p('Oxo Chicken Stock Cubes', 'grocery', 0.99),
  p('Oxo Beef Stock Cubes', 'grocery', 0.99),
  p('HP Sauce', 'grocery', 2.49),
  p('Marmite', 'grocery', 2.99),
  p('Branston Pickle', 'grocery', 2.49),
  p('Lea and Perrins Worcestershire Sauce', 'grocery', 1.99),
  p('Hartley Strawberry Jam', 'grocery', 1.79),
  p("Robertson's Strawberry Jam", 'grocery', 1.99),
  p('Golden Syrup', 'grocery', 1.49),
  p('Honey', 'grocery', 2.49),
  p('Peanut Butter', 'grocery', 1.99),
  p('Nutella 200g', 'grocery', 2.99),
  p('Biscoff Spread', 'grocery', 2.99),
  p('White Sugar 1kg', 'grocery', 1.29),
  p('Brown Sugar 500g', 'grocery', 1.49),
  p('Plain Flour 1.5kg', 'grocery', 1.29),
  p('Self Raising Flour 1.5kg', 'grocery', 1.29),
  p('Cornflour 500g', 'grocery', 0.89),
  p('Baking Powder', 'grocery', 0.79),
  p('Cocoa Powder', 'grocery', 1.99),
  p('Custard Powder', 'grocery', 1.29),
  p('Jelly Strawberry', 'grocery', 0.49),
  p('Jelly Raspberry', 'grocery', 0.49),
  p('Angel Delight Butterscotch', 'grocery', 0.99),
  p('Ambrosia Rice Pudding', 'grocery', 1.29),
  p('Carnation Condensed Milk', 'grocery', 1.29),
  p('Evaporated Milk', 'grocery', 0.99),
  p('Coconut Milk 400ml', 'grocery', 1.29),
  p('Coconut Cream 400ml', 'grocery', 1.29),
  p('Chopped Tomatoes 400g', 'grocery', 0.59),
  p('Tomato Puree', 'grocery', 0.59),
  p('Passata 500g', 'grocery', 0.99),
  p('Tuna in Brine 185g', 'grocery', 1.29),
  p('Tuna in Sunflower Oil 185g', 'grocery', 1.29),
  p('Sardines in Tomato Sauce', 'grocery', 0.89),
  p('Pilchards in Tomato Sauce', 'grocery', 0.89),
  p('Corned Beef 340g', 'grocery', 2.99),
  p('Spam 340g', 'grocery', 2.99),
  p('Mixed Herbs', 'grocery', 0.89),
  p('Paprika', 'grocery', 0.89),
  p('Cumin', 'grocery', 0.89),
  p('Turmeric', 'grocery', 0.89),
  p('Curry Powder', 'grocery', 0.99),
  p('Saxa Rock Salt 350g', 'grocery', 1.29),
  p('Malt Vinegar', 'grocery', 0.79),
  p('White Vinegar', 'grocery', 0.79),
  p('Pickled Onions', 'grocery', 1.29),
  p('Pickled Gherkins', 'grocery', 1.29),
  p('Stuffing Mix', 'grocery', 0.89),
  p('Bisto Gravy Granules', 'grocery', 1.99),
];

// ── SOFT DRINKS ────────────────────────────────────────────────────────────────
const softDrinks = [
  p('Lucozade Original 380ml', 'soft-drinks', 1.39),
  p('Lucozade Orange 380ml', 'soft-drinks', 1.39),
  p('Lucozade Tropical 380ml', 'soft-drinks', 1.39),
  p('Lucozade Sport Orange 500ml', 'soft-drinks', 1.49),
  p('Lucozade Energy Orange 500ml', 'soft-drinks', 1.49),
  p('BARR Lemonade 330ml', 'soft-drinks', 0.79),
  p('BARR Cherryade 330ml', 'soft-drinks', 0.79),
  p('Tango Orange 330ml', 'soft-drinks', 0.89),
  p('Tango Apple 330ml', 'soft-drinks', 0.89),
  p('Tango Strawberry 330ml', 'soft-drinks', 0.89),
  p('Tango Dark Berry 500ml', 'soft-drinks', 1.29),
  p('Rubicon Mango 330ml', 'soft-drinks', 0.99),
  p('Rubicon Guava 330ml', 'soft-drinks', 0.99),
  p('Rubicon Lychee 330ml', 'soft-drinks', 0.99),
  p('Rubicon Passion 330ml', 'soft-drinks', 0.99),
  p('KA Fruit Punch 330ml', 'soft-drinks', 0.79),
  p('KA Grape 330ml', 'soft-drinks', 0.79),
  p('KA Watermelon 330ml', 'soft-drinks', 0.79),
  p('Fanta Orange 330ml', 'soft-drinks', 0.89),
  p('Fanta Lemon 330ml', 'soft-drinks', 0.89),
  p('Fanta Fruit Twist 330ml', 'soft-drinks', 0.89),
  p('Pepsi Cola 330ml', 'soft-drinks', 0.89),
  p('Pepsi Max 330ml', 'soft-drinks', 0.89),
  p('Pepsi Max Cherry 330ml', 'soft-drinks', 0.89),
  p('Pepsi Cola 500ml', 'soft-drinks', 1.29),
  p('Pepsi Max 500ml', 'soft-drinks', 1.29),
  p('Coca-Cola 330ml', 'soft-drinks', 0.99),
  p('Coca-Cola Zero 330ml', 'soft-drinks', 0.99),
  p('Diet Coke 330ml', 'soft-drinks', 0.99),
  p('Coca-Cola 500ml', 'soft-drinks', 1.39),
  p('Coca-Cola 1.5 Litre', 'soft-drinks', 1.99),
  p('Coca-Cola 2 Litre', 'soft-drinks', 2.49),
  p('Red Bull 250ml', 'soft-drinks', 1.69),
  p('Red Bull Sugar Free 250ml', 'soft-drinks', 1.69),
  p('Boost Energy 250ml', 'soft-drinks', 0.69),
  p('Monster Energy 500ml', 'soft-drinks', 1.69),
  p('Monster Ultra 500ml', 'soft-drinks', 1.69),
  p('Relentless 500ml', 'soft-drinks', 1.49),
  p('Sprite 330ml', 'soft-drinks', 0.89),
  p('Sprite 500ml', 'soft-drinks', 1.29),
  p('7UP 330ml', 'soft-drinks', 0.89),
  p('Dr Pepper 330ml', 'soft-drinks', 0.89),
  p('Irn Bru 330ml', 'soft-drinks', 0.89),
  p('Irn Bru Sugar Free 330ml', 'soft-drinks', 0.89),
  p('Vimto 330ml', 'soft-drinks', 0.79),
  p('Ribena Blackcurrant 330ml', 'soft-drinks', 0.89),
  p('Oasis Citrus Punch 500ml', 'soft-drinks', 0.99),
  p('Oasis Summer Fruits 500ml', 'soft-drinks', 0.99),
  p('Mountain Dew 330ml', 'soft-drinks', 0.89),
  p('Capri-Sun Orange 330ml', 'soft-drinks', 0.89),
  p('Capri-Sun Strawberry 330ml', 'soft-drinks', 0.89),
  p('Tropicana Orange 330ml', 'soft-drinks', 1.29),
  p('Arizona Iced Tea 500ml', 'soft-drinks', 1.49),
  p('Lipton Ice Tea 500ml', 'soft-drinks', 1.29),
  p('San Pellegrino 330ml', 'soft-drinks', 0.99),
  p('Fever-Tree Tonic 200ml', 'soft-drinks', 1.29),
  p('Fever-Tree Ginger Beer 200ml', 'soft-drinks', 1.29),
  p('D&G Ginger Beer 330ml', 'soft-drinks', 0.99),
  p('Big H Grapefruit 330ml', 'soft-drinks', 0.79),
  p('Grace Coconut Water 330ml', 'soft-drinks', 1.29),
  p('Volvic 500ml', 'water', 0.99),
  p('Highland Spring Still 500ml', 'water', 0.89),
  p('Evian 500ml', 'water', 0.99),
];

// ── BISCUITS / CONFECTIONERY ──────────────────────────────────────────────────
const biscuits = [
  p('Maryland Chocolate Chip Cookies', 'confectionery', 1.29),
  p("Fox's Golden Crunch Creams", 'confectionery', 1.49),
  p("Fox's Party Rings", 'confectionery', 1.29),
  p('Ritz Crackers', 'confectionery', 1.49),
  p("Paterson's Shortbread", 'confectionery', 1.99),
  p('Bourbon Biscuits', 'confectionery', 0.99),
  p('Biscoff Original Biscuits', 'confectionery', 1.49),
  p('Hobnobs', 'confectionery', 1.29),
  p('Digestive Biscuits', 'confectionery', 1.09),
  p("McVitie's Digestives", 'confectionery', 1.29),
  p("McVitie's Jaffa Cakes", 'confectionery', 1.49),
  p("McVitie's Rich Tea", 'confectionery', 0.99),
  p('Custard Creams', 'confectionery', 0.99),
  p('Garibaldi Biscuits', 'confectionery', 0.99),
  p('Ginger Nuts', 'confectionery', 0.89),
  p('Rich Tea Biscuits', 'confectionery', 0.89),
  p('Shortbread Biscuits', 'confectionery', 1.29),
  p('Oreo Original', 'confectionery', 1.49),
  p('Oreo Double Stuf', 'confectionery', 1.69),
  p("Jacob's Cream Crackers", 'confectionery', 0.99),
  p('TUC Crackers', 'confectionery', 1.29),
  p('Club Milk Chocolate Biscuit', 'confectionery', 1.49),
  p('Penguin Chocolate Biscuit', 'confectionery', 1.29),
  p('Rocky Biscuit Bar', 'confectionery', 1.29),
  p('Malted Milk Biscuits', 'confectionery', 0.89),
  p('Jammie Dodgers', 'confectionery', 1.29),
  p('Wagon Wheels', 'confectionery', 1.29),
  p('Viscount Biscuits', 'confectionery', 1.49),
];

// ── SWEETS / CHOCOLATES ────────────────────────────────────────────────────────
const sweets = [
  p('Haribo Starmix', 'confectionery', 1.29),
  p('Haribo Tangfastics', 'confectionery', 1.29),
  p('Haribo Gold Bears', 'confectionery', 0.99),
  p('Haribo Happy Cola', 'confectionery', 1.29),
  p('Haribo Supermix', 'confectionery', 1.29),
  p('Haribo Sour Mix', 'confectionery', 1.29),
  p('Bebeto Watermelon', 'confectionery', 0.99),
  p('Bebeto Cola', 'confectionery', 0.99),
  p('Maynards Bassetts Wine Gums', 'confectionery', 1.49),
  p('Maynards Bassetts Jelly Babies', 'confectionery', 1.49),
  p('Maynards Bassetts Fruit Pastilles', 'confectionery', 1.49),
  p('Galaxy Milk Chocolate Bar', 'chocolates', 1.49),
  p('Galaxy Caramel Bar', 'chocolates', 1.49),
  p('Galaxy Ripple Bar', 'chocolates', 0.99),
  p('Cadbury Dairy Milk', 'chocolates', 1.49),
  p('Cadbury Wispa', 'chocolates', 0.99),
  p('Cadbury Crunchie', 'chocolates', 0.99),
  p('Cadbury Flake', 'chocolates', 0.99),
  p('Cadbury Twirl', 'chocolates', 0.99),
  p('Twix', 'chocolates', 0.99),
  p('Kinder Bueno', 'chocolates', 1.29),
  p('Kinder Chocolate', 'chocolates', 1.29),
  p('Ferrero Rocher 3 Pack', 'chocolates', 1.79),
  p('Toblerone 100g', 'chocolates', 1.99),
  p('Maltesers', 'chocolates', 0.99),
  p('M&Ms Peanut', 'chocolates', 1.29),
  p('M&Ms Milk Chocolate', 'chocolates', 1.29),
  p('Skittles Original', 'confectionery', 0.99),
  p('Starburst Original', 'confectionery', 0.99),
  p('Snickers', 'chocolates', 0.89),
  p('Mars Bar', 'chocolates', 0.89),
  p('Milky Way', 'chocolates', 0.79),
  p('Bounty', 'chocolates', 0.99),
  p('Lion Bar', 'chocolates', 0.99),
  p('Dime Bar', 'chocolates', 0.89),
  p('Roses Chocolate Box', 'chocolates', 4.99),
  p('Quality Street', 'chocolates', 4.99),
  p('After Eight', 'chocolates', 2.99),
  p("Reese's Peanut Butter Cups", 'chocolates', 1.49),
  p('Lindt Milk Chocolate 100g', 'chocolates', 2.49),
  p('Extra Strong Mints', 'confectionery', 0.79),
  p('Polo Mints Original', 'confectionery', 0.79),
  p('Polo Mints Spearmint', 'confectionery', 0.79),
  p('Tic Tac Orange', 'confectionery', 0.89),
  p('Tic Tac Mint', 'confectionery', 0.89),
  p('Mentos Fruit', 'confectionery', 0.99),
  p('Mentos Strawberry', 'confectionery', 0.99),
  p("Extra Spearmint Gum", 'confectionery', 0.99),
  p('Orbit Spearmint Gum', 'confectionery', 0.99),
  p('Airwaves Menthol Gum', 'confectionery', 0.99),
  p('Wrigley Juicy Fruit Gum', 'confectionery', 0.99),
  p('Trebor Softmints Peppermint', 'confectionery', 0.99),
  p('Trebor Softmints Spearmint', 'confectionery', 0.99),
  p('Chupa Chups Lollipop', 'confectionery', 0.49),
  p('Lollipops Assorted', 'confectionery', 0.49),
];

// ── CRISPS / SNACKS ────────────────────────────────────────────────────────────
const crisps = [
  p('Walkers Ready Salted 32.5g', 'snacks', 0.99),
  p('Walkers Cheese and Onion 32.5g', 'snacks', 0.99),
  p('Walkers Salt and Vinegar 32.5g', 'snacks', 0.99),
  p('Walkers Prawn Cocktail 32.5g', 'snacks', 0.99),
  p('KP Original Peanuts', 'snacks', 0.99),
  p('KP Salted Peanuts', 'snacks', 0.99),
  p('Pringles Original 200g', 'snacks', 1.99),
  p('Pringles Sour Cream and Onion 200g', 'snacks', 1.99),
  p('Pringles Cheese and Onion 200g', 'snacks', 1.99),
  p('Pringles Salt and Vinegar 200g', 'snacks', 1.99),
  p('Doritos Chilli Heatwave', 'snacks', 1.29),
  p('Doritos Tangy Cheese', 'snacks', 1.29),
  p('Doritos Cool Original', 'snacks', 1.29),
  p('Golden Wonder Ready Salted', 'snacks', 0.79),
  p('Golden Wonder Cheese and Onion', 'snacks', 0.79),
  p('Lorenz Crinkle Chips', 'snacks', 1.29),
  p('Sensations Thai Sweet Chilli', 'snacks', 1.29),
  p('Sensations Caramelised Onion', 'snacks', 1.29),
  p('Kettle Chips Sea Salt', 'snacks', 1.49),
  p('Tyrells Sea Salt', 'snacks', 1.49),
  p('Hula Hoops Original', 'snacks', 0.79),
  p('Hula Hoops Cheese', 'snacks', 0.79),
  p('Mini Cheddars Original', 'snacks', 0.99),
  p('Skips Prawn Cocktail', 'snacks', 0.79),
  p('Quavers Cheese', 'snacks', 0.79),
  p('Wotsits Cheese', 'snacks', 0.79),
  p('Nik Naks Rib n Saucy', 'snacks', 0.79),
  p('Monster Munch Pickled Onion', 'snacks', 0.79),
  p('Monster Munch Flamin Hot', 'snacks', 0.79),
  p('Popchips Original', 'snacks', 1.29),
  p('Butterkist Popcorn Sweet', 'snacks', 1.49),
  p('Butterkist Popcorn Toffee', 'snacks', 1.49),
  p('Plantain Chips', 'snacks', 1.29),
];

// ── CEREALS ────────────────────────────────────────────────────────────────────
const cereals = [
  p('Weetabix 24 Pack', 'grocery', 2.99),
  p('Weetabix 12 Pack', 'grocery', 1.89),
  p("Kellogg's Corn Flakes", 'grocery', 2.29),
  p("Kellogg's Frosties", 'grocery', 2.49),
  p("Kellogg's Crunchy Nut", 'grocery', 2.69),
  p("Kellogg's Rice Krispies", 'grocery', 2.29),
  p("Kellogg's Coco Pops", 'grocery', 2.49),
  p("Kellogg's Special K", 'grocery', 2.99),
  p("Kellogg's All Bran", 'grocery', 2.49),
  p('Nestle Shreddies', 'grocery', 2.49),
  p('Nestle Cheerios', 'grocery', 2.49),
  p('Nestle Shredded Wheat', 'grocery', 2.29),
  p('Alpen Muesli', 'grocery', 2.99),
  p('Porridge Oats 1kg', 'grocery', 1.49),
  p("Scott's Oats Porridge", 'grocery', 1.79),
  p('Bran Flakes', 'grocery', 1.99),
  p('Fruit n Fibre', 'grocery', 2.49),
  p('Quaker Oat So Simple', 'grocery', 2.99),
];

// ── TEA / COFFEE ────────────────────────────────────────────────────────────────
const teaCoffee = [
  p('Nescafe Original 100g', 'tea', 3.99),
  p('Nescafe Original 200g', 'tea', 5.99),
  p('Nescafe Gold Blend 100g', 'tea', 4.99),
  p('Nescafe Gold Blend 200g', 'tea', 7.99),
  p('Kenco Smooth 100g', 'tea', 4.49),
  p('Red Mountain Coffee 100g', 'tea', 3.49),
  p('Lavazza Ground Coffee 250g', 'tea', 3.99),
  p('Twinings English Breakfast 80 Bags', 'tea', 3.49),
  p('Twinings Earl Grey 80 Bags', 'tea', 3.49),
  p('Twinings Green Tea 20 Bags', 'tea', 2.49),
  p('Yorkshire Tea 80 Bags', 'tea', 3.49),
  p('Yorkshire Tea 160 Bags', 'tea', 5.99),
  p('PG Tips 80 Bags', 'tea', 2.99),
  p('PG Tips 160 Bags', 'tea', 4.99),
  p('Typhoo 80 Bags', 'tea', 2.49),
  p('Tetley Original 80 Bags', 'tea', 2.49),
  p('Tetley Original 160 Bags', 'tea', 4.49),
  p('Tatly Tea Bags', 'tea', 1.99),
  p('Tropical Sun Tea Bags', 'tea', 2.49),
  p('Cadbury Drinking Chocolate 250g', 'tea', 2.99),
  p('Horlicks 500g', 'tea', 3.99),
  p('Ovaltine 300g', 'tea', 2.99),
  p('Coffee Mate 200g', 'tea', 2.49),
  p('Clipper Organic Tea 80 Bags', 'tea', 3.49),
  p('Peppermint Tea 20 Bags', 'tea', 1.99),
  p('Chamomile Tea 20 Bags', 'tea', 1.99),
];

// ── BAKERY ─────────────────────────────────────────────────────────────────────
const bakery = [
  p('Antonelli Wafer', 'bakery', 1.29),
  p('St Michel Madeleine Cakes', 'bakery', 2.49),
  p('Lago Wafer', 'bakery', 0.99),
  p('Balconi Mini Rolls', 'bakery', 2.49),
  p('Balconi Snack Cake', 'bakery', 1.49),
  p('Tago Wafer', 'bakery', 0.99),
  p('Jays Cakes', 'bakery', 1.29),
  p('Dulcesol Croissant', 'bakery', 1.49),
  p('Kingsmill White Bread 800g', 'bakery', 1.49),
  p('Kingsmill Toastie Bread', 'bakery', 1.79),
  p('Hovis Wholemeal Bread 800g', 'bakery', 1.49),
  p('Hovis Best of Both 800g', 'bakery', 1.79),
  p('Warburtons White Bread 800g', 'bakery', 1.49),
  p('Pitta Bread', 'bakery', 0.99),
  p('Naan Bread', 'bakery', 0.99),
  p('Wraps Tortilla', 'bakery', 1.49),
  p('Croissant 4 Pack', 'bakery', 1.49),
  p('Hot Cross Buns 4 Pack', 'bakery', 0.99),
  p('Muffins 4 Pack', 'bakery', 1.29),
  p('Mr Kipling Apple Pies', 'bakery', 1.49),
  p('Mr Kipling Jam Tarts', 'bakery', 1.49),
  p('Swiss Roll', 'bakery', 1.29),
  p('Battenberg Cake', 'bakery', 1.79),
  p('Crumpets 6 Pack', 'bakery', 0.99),
  p('Flapjack', 'bakery', 0.99),
  p('Brownie', 'bakery', 0.99),
];

// ── DAIRY ─────────────────────────────────────────────────────────────────────
const dairy = [
  p('Cravendale Fresh Whole Milk 2L', 'dairy', 1.79),
  p('Arla Organic Whole Milk 1L', 'dairy', 1.49),
  p('Onken Natural Yoghurt 500g', 'dairy', 1.99),
  p('Anchor Butter 250g', 'dairy', 2.49),
  p('Lurpak Spreadable 500g', 'dairy', 3.49),
  p('Flora Original 500g', 'dairy', 2.49),
  p('Utterly Butterly 500g', 'dairy', 1.99),
  p('Clover Spread 500g', 'dairy', 2.49),
  p('Stork Spread 500g', 'dairy', 1.49),
  p('Activia Natural Yoghurt 4 Pack', 'dairy', 2.49),
  p('Muller Light Strawberry', 'dairy', 0.79),
  p('Cheddar Cheese 400g', 'dairy', 2.99),
  p('Edam Cheese 300g', 'dairy', 2.49),
  p('Mozzarella 125g', 'dairy', 0.99),
  p('Feta Cheese 200g', 'dairy', 1.99),
  p('Double Cream 300ml', 'dairy', 1.49),
  p('Single Cream 300ml', 'dairy', 1.29),
  p('Soured Cream 300ml', 'dairy', 0.99),
  p('Creme Fraiche 300ml', 'dairy', 1.29),
  p('Free Range Eggs 6 Pack', 'dairy', 1.99),
  p('Free Range Eggs 12 Pack', 'dairy', 3.49),
];

// ── MEAT ──────────────────────────────────────────────────────────────────────
const meat = [
  p('Zaad Chicken', 'meat', 3.99),
  p('Peperami Original', 'meat', 1.29),
  p('Peperami Hot', 'meat', 1.29),
  p('Tikka Bites', 'meat', 1.99),
  p('Rustlers Burger', 'meat', 2.49),
  p('Rustlers Chicken Sandwich', 'meat', 2.49),
  p('Peperami Firestick', 'meat', 1.29),
];

// ── HOUSEHOLD / CLEANING ──────────────────────────────────────────────────────
const household = [
  p('Fairy Liquid Original 433ml', 'household', 1.99),
  p('Fairy Liquid Lemon 433ml', 'household', 1.99),
  p('Flash All Purpose Cleaner', 'household', 1.49),
  p('Flash Spray Lemon', 'household', 1.79),
  p('Finish Dishwasher Tablets 20 Pack', 'household', 3.49),
  p('Finish Rinse Aid', 'household', 1.99),
  p('Brillo Pads 10 Pack', 'household', 1.49),
  p('Dettol Surface Spray', 'household', 2.49),
  p('Dettol Antibacterial Original', 'household', 2.99),
  p('Cif Cream Original', 'household', 1.49),
  p('Cif Lemon Spray', 'household', 1.79),
  p('Comfort Blue Fabric Conditioner', 'household', 2.49),
  p('Comfort Intense Fabric Conditioner', 'household', 2.99),
  p('Ariel Washing Powder 1.3kg', 'household', 5.99),
  p('Persil Non Bio Liquid', 'household', 4.99),
  p('Bold 2in1 Liquid', 'household', 4.49),
  p('Surf Tropical Lily Powder', 'household', 2.99),
  p('Fairy Non Bio Pods 12 Pack', 'household', 3.99),
  p('Domestos Thick Bleach', 'household', 1.49),
  p('Harpic Toilet Cleaner', 'household', 1.79),
  p('Mr Muscle Drain Gel', 'household', 2.49),
  p('Febreze Air Freshener', 'household', 2.49),
  p('Ambi Pur Air Freshener', 'household', 2.49),
  p('Bin Bags 20 Pack', 'household', 1.49),
  p('Cling Film', 'household', 0.99),
  p('Kitchen Foil', 'household', 1.49),
  p('Baking Parchment', 'household', 1.29),
  p('Zoflora Disinfectant', 'household', 1.99),
  p('Vanish Stain Remover', 'household', 3.49),
  p('Easy Off Bam Bathroom Cleaner', 'household', 1.49),
  p('Cilit Bang Power Cleaner', 'household', 1.99),
  p('Sponge Scourers 3 Pack', 'household', 0.99),
  p('Rubber Gloves', 'household', 0.99),
  p('Lenor Fabric Conditioner', 'household', 2.99),
];

// ── PERSONAL CARE / TOILETRIES ────────────────────────────────────────────────
const toiletries = [
  p('Carex Original Hand Wash 250ml', 'toiletries', 1.49),
  p('Carex Moisture Plus Hand Wash', 'toiletries', 1.49),
  p('Palmolive Original Shower Gel', 'toiletries', 1.99),
  p('Colgate Total Toothpaste', 'toiletries', 2.49),
  p('Colgate Whitening Toothpaste', 'toiletries', 2.49),
  p('Lynx Africa Body Spray', 'toiletries', 2.99),
  p('Lynx Dark Temptation Body Spray', 'toiletries', 2.99),
  p('Radox Shower Gel', 'toiletries', 1.99),
  p('Sanex Zero Body Wash', 'toiletries', 2.49),
  p('Gillette Fusion Razor', 'toiletries', 4.99),
  p('Gillette Foam Sensitive', 'toiletries', 1.99),
  p('Dove Original Deodorant', 'toiletries', 2.49),
  p('Sure Original Deodorant', 'toiletries', 2.49),
  p('Nivea Original Deodorant', 'toiletries', 2.29),
  p('Old Spice Deodorant', 'toiletries', 1.99),
  p('Imperial Leather Original Bar Soap', 'toiletries', 0.89),
  p('Head and Shoulders Shampoo', 'toiletries', 2.99),
  p('Pantene Pro-V Shampoo', 'toiletries', 2.99),
  p('Alberto Balsam Shampoo', 'toiletries', 0.99),
  p('VO5 Shampoo', 'toiletries', 0.99),
  p('Veet Hair Removal Cream', 'toiletries', 3.99),
  p('Cotton Buds 100 Pack', 'toiletries', 0.99),
  p('Cotton Wool 100g', 'toiletries', 0.99),
  p('Always Ultra Normal Pads', 'toiletries', 2.49),
  p('Tampax Regular', 'toiletries', 2.99),
  p('Bodyform Ultra Pads', 'toiletries', 2.49),
  p('Listerine Cool Mint 500ml', 'toiletries', 2.99),
  p('Corsodyl Mouthwash 300ml', 'toiletries', 3.49),
  p('Wet Wipes 72 Pack', 'toiletries', 1.49),
  p("Johnson's Baby Lotion", 'toiletries', 2.49),
  p("Johnson's Baby Powder", 'toiletries', 1.99),
  p('Sudocrem 60g', 'toiletries', 2.49),
  p('Pampers Size 1 Nappies', 'toiletries', 4.99),
  p('Pampers Size 2 Nappies', 'toiletries', 4.99),
  p('E45 Cream 125g', 'toiletries', 3.49),
  p('Savlon Antiseptic Cream', 'toiletries', 1.99),
  p('TCP Antiseptic Liquid', 'toiletries', 1.99),
  p('Clearasil Spot Cream', 'toiletries', 2.99),
  p('Germolene Antiseptic Cream', 'toiletries', 2.49),
  p('Hair Gel', 'toiletries', 1.49),
  p('Foot Cream', 'toiletries', 1.99),
  p('Sun Cream SPF30', 'toiletries', 3.99),
];

// ── PET FOOD ──────────────────────────────────────────────────────────────────
const petFood = [
  p('Dreamies Cat Treats Chicken', 'grocery', 1.49),
  p('Dreamies Cat Treats Cheese', 'grocery', 1.49),
  p('Dreamies Cat Treats Salmon', 'grocery', 1.49),
  p('Webbox Cat Treats', 'grocery', 1.29),
  p('Felix As Good As It Looks', 'grocery', 0.69),
  p('Whiskas Pouches Mixed', 'grocery', 3.49),
  p('Whiskas Dry Cat Food', 'grocery', 2.99),
  p('Sheba Pouches', 'grocery', 3.49),
  p("Go-Cat Dry Cat Food", 'grocery', 2.49),
  p('Winalot Dog Food', 'grocery', 0.99),
  p('Pedigree Dog Food', 'grocery', 0.89),
  p('Pedigree Dentastix', 'grocery', 2.49),
  p('Bakers Dog Treats', 'grocery', 1.99),
  p('Chappie Wet Dog Food', 'grocery', 0.79),
];

// ── AFRICAN / ASIAN ITEMS ─────────────────────────────────────────────────────
const africanAsian = [
  p('Tropical Sun Coconut Milk Powder 50g', 'grocery', 1.29),
  p('Tropical Sun Jerk Seasoning', 'grocery', 1.99),
  p('Tropical Sun Grace Scotch Bonnet Sauce', 'grocery', 1.99),
  p('TRS Basmati Rice 5kg', 'rice', 6.99),
  p('TRS Moong Dal', 'grocery', 1.99),
  p('TRS Masoor Dal', 'grocery', 1.99),
  p('TRS Chana Dal', 'grocery', 1.99),
  p('Aachi Tomato Rice Powder', 'grocery', 1.49),
  p('Aachi Rice Powder 200g', 'grocery', 1.49),
  p('Grace Hot Pepper Sauce', 'grocery', 1.99),
  p('Encona West Indian Hot Pepper Sauce', 'grocery', 1.99),
  p('Maggi Jerk Seasoning', 'grocery', 1.29),
  p('KTC Coconut Oil 1L', 'grocery', 3.49),
  p('Noor Katira Gond 100g', 'grocery', 1.99),
  p('TRS Green Raising 750g', 'grocery', 2.49),
];

// ── ICE CREAM / FRIDGE ────────────────────────────────────────────────────────
const iceCream = [
  p('Solero Mango Ice Cream', 'frozen-foods', 1.49),
  p('Magnum Classic Ice Cream', 'frozen-foods', 1.99),
  p('Cornetto Original', 'frozen-foods', 1.49),
  p('Calippo Orange', 'frozen-foods', 0.99),
  p('Twister Lolly', 'frozen-foods', 0.99),
  p('Ben & Jerry Cookie Dough 465ml', 'frozen-foods', 5.49),
  p('Carte Dor Vanilla 900ml', 'frozen-foods', 4.49),
  p('Haagen-Dazs Strawberry 460ml', 'frozen-foods', 4.99),
  p('Walls Vanilla Ice Cream 1L', 'frozen-foods', 2.99),
];

// ────────────────────────────────────────────────────────────────────────────
// INSERT ALL PRODUCTS
// ────────────────────────────────────────────────────────────────────────────
const allProducts = [
  ...wines, ...beers, ...ciders, ...spirits,
  ...cigarettes, ...rollingTobacco, ...heets, ...vapes,
  ...rollingAccessories, ...nicotinePouches,
  ...batteries, ...tissues, ...medicine,
  ...groceries, ...softDrinks, ...biscuits, ...sweets,
  ...crisps, ...cereals, ...teaCoffee, ...bakery,
  ...dairy, ...meat, ...household, ...toiletries,
  ...petFood, ...africanAsian, ...iceCream,
].filter(Boolean);

// De-duplicate by id
const seen = new Set();
const unique = allProducts.filter(p => {
  if (seen.has(p.id)) return false;
  seen.add(p.id);
  return true;
});

console.log(`Products to insert: ${unique.length}`);

const BATCH = 100;
let inserted = 0;
let errors = 0;

for (let i = 0; i < unique.length; i += BATCH) {
  const batch = unique.slice(i, i + BATCH);
  const { error } = await supabase.from('products').upsert(batch, { onConflict: 'id' });
  if (error) {
    console.error(`Batch ${Math.floor(i/BATCH)+1} error:`, error.message);
    errors++;
  } else {
    inserted += batch.length;
    process.stdout.write(`  Inserted batch ${Math.floor(i/BATCH)+1}: ${inserted}/${unique.length}\n`);
  }
}

console.log(`\nDone! Inserted ${inserted} products. Errors: ${errors}`);

// Final count by category
const { data: finalCount } = await supabase.from('products').select('category');
const cats = {};
finalCount.forEach(p => { cats[p.category] = (cats[p.category]||0)+1; });
console.log('\nFinal count by category:');
Object.entries(cats).sort((a,b)=>b[1]-a[1]).forEach(([k,v]) => console.log(`  ${k}: ${v}`));
